{
  delib,
  host,
  pkgs,
  ...
}:
delib.module {
  name = "services.sketchybar";

  options.services.sketchybar = with delib; {
    enable = boolOption host.isDesktop;
    colors = {
      rosewater = strOption "";
      flamingo = strOption "";
      pink = strOption "";
      mauve = strOption "";
      red = strOption "";
      maroon = strOption "";
      peach = strOption "";
      yellow = strOption "";
      green = strOption "";
      teal = strOption "";
      sky = strOption "";
      sapphire = strOption "";
      blue = strOption "";
      lavender = strOption "";
      text = strOption "";
      subtext1 = strOption "";
      subtext0 = strOption "";
      overlay2 = strOption "";
      overlay1 = strOption "";
      overlay0 = strOption "";
      surface2 = strOption "";
      surface1 = strOption "";
      surface0 = strOption "";
      base = strOption "";
      mantle = strOption "";
      crust = strOption "";
    };
    # App-specific icon colors (separate from theme colors)
    appColors = {
      arc = strOption "";
      ghostty = strOption "";
      obsidian = strOption "";
      kitty = strOption "";
    };
    # Semantic colors for specific UI elements
    electricity = strOption ""; # AC power indicator
    # CPU graph colors by usage level
    cpuColors = {
      low = strOption ""; # 1-25%
      medium = strOption ""; # 26-50%
      high = strOption ""; # 51-75%
      critical = strOption ""; # 76-100%
    };
  };

  darwin.ifEnabled.services = {
    sketchybar = {
      enable = true;
      extraPackages = with pkgs; [nushell];
    };
  };

  home.ifEnabled = {cfg, ...}: let
    colorsNu = pkgs.writeText "colors.nu" ''
      #!/usr/bin/env nu
      # Generated by Nix from rice configuration
      export const rosewater = "${cfg.colors.rosewater}"
      export const flamingo  = "${cfg.colors.flamingo}"
      export const pink      = "${cfg.colors.pink}"
      export const mauve     = "${cfg.colors.mauve}"
      export const red       = "${cfg.colors.red}"
      export const maroon    = "${cfg.colors.maroon}"
      export const peach     = "${cfg.colors.peach}"
      export const yellow    = "${cfg.colors.yellow}"
      export const green     = "${cfg.colors.green}"
      export const teal      = "${cfg.colors.teal}"
      export const sky       = "${cfg.colors.sky}"
      export const sapphire  = "${cfg.colors.sapphire}"
      export const blue      = "${cfg.colors.blue}"
      export const lavender  = "${cfg.colors.lavender}"
      export const text      = "${cfg.colors.text}"
      export const subtext1  = "${cfg.colors.subtext1}"
      export const subtext0  = "${cfg.colors.subtext0}"
      export const overlay2  = "${cfg.colors.overlay2}"
      export const overlay1  = "${cfg.colors.overlay1}"
      export const overlay0  = "${cfg.colors.overlay0}"
      export const surface2  = "${cfg.colors.surface2}"
      export const surface1  = "${cfg.colors.surface1}"
      export const surface0  = "${cfg.colors.surface0}"
      export const base      = "${cfg.colors.base}"
      export const mantle    = "${cfg.colors.mantle}"
      export const crust     = "${cfg.colors.crust}"

      # App-specific icon colors
      export const app_arc     = "${cfg.appColors.arc}"
      export const app_ghostty = "${cfg.appColors.ghostty}"
      export const app_obsidian = "${cfg.appColors.obsidian}"
      export const app_kitty   = "${cfg.appColors.kitty}"

      # Semantic colors
      export const electricity = "${cfg.electricity}"

      # CPU graph colors by usage level
      export const cpu_low      = "${cfg.cpuColors.low}"
      export const cpu_medium   = "${cfg.cpuColors.medium}"
      export const cpu_high     = "${cfg.cpuColors.high}"
      export const cpu_critical = "${cfg.cpuColors.critical}"
    '';
    sketchybarConfig = pkgs.runCommand "sketchybar-config" {} ''
      mkdir -p $out
      cp -r ${./rc}/* $out/
      chmod -R +w $out
      cp ${colorsNu} $out/colors.nu
    '';
  in {
    home.file = {
      ".config/sketchybar" = {
        source = sketchybarConfig;
        recursive = true;
      };
    };
    xdg.configFile."sketchybar_icon_map.sh" = {
      source = pkgs.replaceVars ./sketchybar_icon_map.sh {
        sketchybar-app-font = "${pkgs.sketchybar-app-font}/bin/icon_map.sh";
      };
    };
    home.packages = with pkgs; [
      sketchybar-app-font
      nerd-fonts.hack
    ];
  };
}
