import assert from "node:assert/strict";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { Value } from "typebox/value";
import { createSubagentRunTool, validateAgentReuseAuthorization } from "../extensions_src/orchestration.ts";
import { AGENT_ARTIFACT_EXTENSION, buildLaunchEnvelope, projectLaunchEnvelope, settledAgentCatalog, validateAgentCatalog, validateDelegationConfig, validateLaunchEnvelope } from "../extensions_src/utilities/agent_types.ts";
import { promptSummary } from "../extensions_src/utilities/orchestration_types.ts";
import { prepareAgent, publishAgent, readAgentSnapshot } from "../extensions_src/utilities/orchestration_store.ts";
import { composeAgentRow, splitPaletteColumns, SubagentPaletteComponent } from "../extensions_src/utilities/orchestration_palette.ts";
import { emptyUsage } from "../extensions_src/utilities/orchestration_types.ts";
import { visibleWidth } from "@earendil-works/pi-tui";
const definition = (description: string) => ({ model: "provider/model", description, thinkingLevel: "medium" as const, tools: ["read"], skillOptIns: [], instructions: "Do the bounded work.", harness: "pi" as const, childExtensionContributions: [] });
void test("caller policy projects an immutable transitive launch closure", () => {
    const catalog = settledAgentCatalog(); const envelope = buildLaunchEnvelope("reviewer", catalog, { "agent:reviewer": ["critic"] }, ["/popup.ts", "/orchestration.ts", "/bridge.ts"]); catalog.agents.critic!.model = "changed/model";
    assert.deepEqual(Object.keys(envelope.catalog).sort(), ["critic", "reviewer"]); assert.equal(envelope.catalog.critic!.model, "openai-codex/gpt-5.6-terra"); assert.deepEqual(envelope.delegation["agent:reviewer"], ["critic"]); assert.deepEqual(envelope.childExtensions.reviewer, ["/popup.ts", "/orchestration.ts", AGENT_ARTIFACT_EXTENSION, "/bridge.ts"]); assert.equal(validateLaunchEnvelope(envelope).identity, "agent:reviewer");
});
void test("the exact seven-agent capability matrix includes the read-only Codex research leaf and rejects broadened capabilities", () => {
    const catalog = validateAgentCatalog(settledAgentCatalog());
    assert.deepEqual(catalog.agents.codex, { model: "codex/gpt-5.6-luna", description: "Read-only, source-backed Web research leaf through Codex ACP.", thinkingLevel: "high", tools: [], skillOptIns: [], instructions: "Use Codex's built-in Web search to investigate the delegated question. Return a concise evidence brief containing the conclusion, source URLs with the claim each supports, freshness, and material uncertainty. Read workspace context only when the task requires it. If evidence is insufficient, state what is missing.", harness: "codex", harnessOptions: { mode: "read-only", permissionPolicy: "reject", webSearch: "cached" }, childExtensionContributions: [] });
    const unexpected = settledAgentCatalog(); unexpected.agents.reviewer!.childExtensionContributions = ["/unexpected.ts"]; assert.throws(() => validateAgentCatalog(unexpected), /settled reviewer capability/u);
    const mutatingCritic = settledAgentCatalog(); mutatingCritic.agents.critic!.tools.push("write"); mutatingCritic.agents.critic!.skillOptIns.push("source-implementation"); assert.throws(() => validateAgentCatalog(mutatingCritic), /settled critic capability/u);
    const wrongCursorHarness = settledAgentCatalog(); wrongCursorHarness.agents["fast-worker"]!.harnessOptions = { mode: "agent", permissionPolicy: "allow-always", sandbox: "enabled", trustWorkspace: true, worktree: false }; assert.throws(() => validateAgentCatalog(wrongCursorHarness), /settled fast-worker capability/u);
    const wrongCodexHarness = settledAgentCatalog(); wrongCodexHarness.agents.codex!.harnessOptions = { mode: "agent", permissionPolicy: "reject", webSearch: "cached" }; assert.throws(() => validateAgentCatalog(wrongCodexHarness), /settled codex capability/u);
    const injectedManifest = buildLaunchEnvelope("reviewer", settledAgentCatalog(), { "agent:reviewer": ["critic"] }, ["/popup", "/orchestration", "/bridge"]); injectedManifest.childExtensions.reviewer!.splice(2, 0, "/unexpected.ts"); assert.throws(() => validateLaunchEnvelope(injectedManifest), /exactly match its settled contribution manifest/u);
});
void test("nested launch projection preserves the parent-frozen target definitions and manifests after global mutation", () => {
    const parent = buildLaunchEnvelope("reviewer", settledAgentCatalog(), { "agent:reviewer": ["critic"] }, ["/old-popup", "/old-orchestration", "/old-bridge"]); const mutableGlobal = { popup: "/new-popup", criticModel: "changed/model" }; const child = projectLaunchEnvelope("critic", parent);
    assert.deepEqual(child.childExtensions.critic, ["/old-popup", "/old-orchestration", "/old-bridge"]); assert.equal(child.self.model, "openai-codex/gpt-5.6-terra"); assert.notEqual(child.self.model, mutableGlobal.criticModel); assert.ok(!child.childExtensions.critic.includes(mutableGlobal.popup));
});
void test("delegation config authorizes the Codex leaf from both modes and accepts its external harness", () => { const base = { schemaVersion: 1, stateRoot: "/state", tmux: "/tmux", returnParentCommand: "/parent", parentNavigationHint: "parent", historyViewerExtension: "/history", popupExtension: "/popup", orchestrationExtension: "/orchestration", childBridgeExtension: "/bridge", harnesses: { codex: { adapter: "codex-acp", command: "/bin/codex-acp", workerCommand: "/bin/node", workerEntrypoint: "/worker.ts", bridgeReadyTimeoutMs: 15000 } }, maxDepth: 3, natureHandleWords: ["May"], delegation: { "mode:recon": ["explorer", "reviewer", "codex"], "mode:ops": ["explorer", "worker", "validator", "reviewer", "fast-worker", "codex"], "agent:reviewer": ["critic"] } }; const config = validateDelegationConfig(base); assert.equal(config.harnesses.codex?.adapter, "codex-acp"); assert.ok(config.delegation["mode:recon"]?.includes("codex")); assert.ok(config.delegation["mode:ops"]?.includes("codex")); assert.equal(config.delegation["agent:codex"], undefined); assert.throws(() => validateDelegationConfig({ ...base, allowedChildExtensionContributions: ["/unexpected.ts"] }), /unknown keys/u); assert.throws(() => validateDelegationConfig({ ...base, delegation: { ...base.delegation, "agent:codex": ["critic"] } }), /exactly match/u); });
void test("persisted schema-2 agent records accept the settled Codex harness without a schema change", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-codex-record-"));
    try {
        const definition = settledAgentCatalog().agents.codex!; const prepared = await prepareAgent(root, { agent: "codex", harness: "codex", cwd: root, agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:recon", targetAgent: "codex", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: false, interactiveInterventions: false, terminalHistory: false } });
        const envelope = buildLaunchEnvelope("codex", settledAgentCatalog(), {}, ["/popup", "/orchestration", "/bridge"]); const envelopePath = join(prepared.paths.directory, "launch-envelope.json"); await writeFile(envelopePath, JSON.stringify(envelope));
        await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "codex", harness: "codex", cwd: root, agentSnapshot: definition, launchEnvelope: envelopePath, callerIdentity: "mode:recon", targetAgent: "codex", depth: 1, originSessionId: "origin", tmux: { socket: "/tmp/tmux", serverPid: "1", sessionId: "$1", sessionName: "s", windowId: "@1", paneId: "%1", windowName: "codex" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: false, interactiveInterventions: false, terminalHistory: false } });
        const snapshot = await readAgentSnapshot(root, prepared.agentId); assert.equal(snapshot.agent.schemaVersion, 2); assert.equal(snapshot.agent.harness, "codex"); assert.equal(snapshot.agent.agentSnapshot.model, "codex/gpt-5.6-luna");
    } finally { await rm(root, { recursive: true, force: true }); }
});
void test("existing agent reuse remains authorized by the active caller", () => { const stored = { agent: { agent: "worker" } } as never; assert.doesNotThrow(() => validateAgentReuseAuthorization({ identity: "mode:ops", targets: { worker: definition("Work") }, catalog: { schemaVersion: 1, agents: {} } }, stored)); assert.throws(() => validateAgentReuseAuthorization({ identity: "mode:recon", targets: { explorer: definition("Explore") }, catalog: { schemaVersion: 1, agents: {} } }, stored), /not allowed to reuse agent worker/u); });
void test("dispatch schema exposes only authorized agents and rejects legacy arguments", () => { const targets = { explorer: definition("Explore"), reviewer: definition("Review") }; const tool = createSubagentRunTool({ configPath: "/config", env: {}, exec: async () => ({ stdout: "", stderr: "", code: 0 }) } as never, targets); assert.equal(Value.Check(tool.parameters, { agent: "explorer", prompt: "Inspect" }), true); assert.equal(Value.Check(tool.parameters, { agent: "worker", prompt: "Change" }), false); assert.equal(Value.Check(tool.parameters, { profile: "explorer", purpose: "Inspect", prompt: "Inspect" }), false); const schema = tool.parameters as { properties?: Record<string, { description?: string }> }; assert.match(schema.properties?.agent?.description ?? "", /explorer: Explore.*reviewer: Review/u); });
void test("agent-session rows stay width-safe and narrow terminals use one pane", () => { const row = composeAgentRow({ width: 24, marker: "> ", connector: "├─", expand: "  ", handle: "Coulson-12345678", agentType: "validator", state: "● RUNNING", summary: "Validate the complete generated contract" }); assert.ok(visibleWidth(row) <= 24); assert.deepEqual(splitPaletteColumns(80), { listWidth: 80 }); assert.ok(splitPaletteColumns(120).detailWidth); });
void test("narrow agent-session rendering keeps textual identity/state and width-safe single-pane behavior", () => { const id = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"; const component = new SubagentPaletteComponent({ tui: { terminal: { rows: 24, columns: 60 }, requestRender() {} }, theme: { fg: (_role: string, text: string) => text, bg: (_role: string, text: string) => text, bold: (text: string) => text }, ui: { confirm: async () => true }, keymap: { moveUp: [], moveDown: [], collapse: [], expand: [], confirm: [], cancel: [], refresh: [], stop: [], preview: [], unlink: [] }, deps: { stateRoot: "/state", originSessionId: "origin", authorizedAgents: ["worker"], callerIdentity: "mode:ops", exec: async () => ({ stdout: "", stderr: "", code: 1 }), tmux: "/tmux", historyViewerExtension: "/history", piCommand: "/pi", natureHandleWords: ["May"] }, done() {} } as never); assert.match(component.render(60).join("\n"), /Loading/u); component.replaceAgents([{ agent: { schemaVersion: 2, agentId: id, agent: "worker", harness: "pi", cwd: "/work", createdAt: "2026-01-01", agentSnapshot: definition("Work"), launchEnvelope: "/envelope", launchEnvelopeDigest: "digest", tmux: { socket: "/tmp/tmux", serverPid: "1", sessionId: "$1", sessionName: "s", windowId: "@1", paneId: "%1", windowName: "w" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, status: { schemaVersion: 2, agentId: id, state: "busy", bridgeReady: true, agentUsage: emptyUsage(), accountedTaskIds: [], updatedAt: "2026-01-01" }, task: { request: { schemaVersion: 2, agentId: id, taskId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", prompt: "Validate contract\nFULL DETAIL ONLY", createdAt: "2026-01-01" }, status: { schemaVersion: 2, agentId: id, taskId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb", state: "running", createdAt: "2026-01-01" }, result: null, interventions: [], claimed: false, directory: "/task" } }]); const lines = component.render(60); assert.match(lines.join("\n"), /worker/u); assert.match(lines.join("\n"), /BUSY/u); assert.doesNotMatch(lines.join("\n"), /FULL DETAIL ONLY/u); for (const line of lines) assert.ok(visibleWidth(line) <= 60); component.dispose(); });
void test("prompt summaries derive from the first nonblank line", () => { assert.equal(promptSummary("\n  Validate   this contract\nfull detail"), "Validate this contract"); });
