import assert from "node:assert/strict";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createSubagentGetTool, createSubagentRunTool, createSubagentStopTool, createSubagentSubmitTool, createSubagentWaitTool } from "../extensions_src/orchestration.ts";
import { AGENT_ARTIFACT_EXTENSION, buildLaunchEnvelope, settledAgentCatalog, settledAgentDefinition } from "../extensions_src/utilities/agent_types.ts";
import { OriginAgentDiscovery, stopSubagentAgent } from "../extensions_src/utilities/orchestration_management.ts";
import { piLaunchDescriptor } from "../extensions_src/utilities/orchestration_pi.ts";
import { emptyUsage } from "../extensions_src/utilities/orchestration_types.ts";
import { claimPendingTask, claimTaskUsage, createTask, findTaskAgent, finishTask, patchAgentStatus, prepareAgent, publishAgent, readAgentSnapshot, readTaskCancellation, recordIntervention, requestTaskCancellation, taskPaths } from "../extensions_src/utilities/orchestration_store.ts";
const definition = settledAgentDefinition("worker");
const capabilities = { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true };
const tmux = { socket: "/tmp/tmux", serverPid: "1", sessionId: "$1", sessionName: "main", windowId: "@1", paneId: "%1", windowName: "worker" };
async function persistEnvelope(directory: string): Promise<string> { const path = join(directory, "launch-envelope.json"); const envelope = buildLaunchEnvelope("worker", settledAgentCatalog(), {}, ["/popup", "/orchestration", "/bridge"]); await writeFile(path, JSON.stringify(envelope)); return path; }
void test("task store persists agent identity and full prompt without purpose metadata", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-store-"));
    const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory);
    await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities });
    const task = await createTask(root, prepared.agentId, "Implement the boundary\nwith complete details"); await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded", output: "done" });
    const snapshot = await readAgentSnapshot(root, prepared.agentId, task.request.taskId); assert.equal(snapshot.agent.agent, "worker"); assert.equal(snapshot.task?.request.prompt, "Implement the boundary\nwith complete details"); assert.equal(snapshot.task?.result?.output, "done"); const persisted = await readFile(join(task.directory, "request.json"), "utf8"); assert.doesNotMatch(persisted, /purpose|profile/u);
});
void test("persistent task lifecycle retains reuse, intervention, cancellation, and exactly-once usage", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-lifecycle-"));
    const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory);
    await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities }); await patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true });
    const first = await createTask(root, prepared.agentId, "first prompt"); await claimPendingTask(root, prepared.agentId); await recordIntervention(root, prepared.agentId, { taskId: first.request.taskId, text: "include tests", deliveryMode: "steer", images: [] });
    const usage = { input: 1, output: 2, cacheRead: 0, cacheWrite: 0, totalTokens: 3, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } };
    await finishTask(root, prepared.agentId, first.request.taskId, { outcome: "succeeded", output: "done", usage, turns: 1 }); await finishTask(root, prepared.agentId, first.request.taskId, { outcome: "succeeded", output: "duplicate", usage, turns: 1 });
    const afterFirst = await readAgentSnapshot(root, prepared.agentId, first.request.taskId); assert.equal(afterFirst.status.agentUsage.totalTokens, 3); assert.equal(afterFirst.task?.interventions[0]?.text, "include tests"); const firstClaim = await claimTaskUsage(root, prepared.agentId, first.request.taskId, "origin", undefined, "call-1", "subagent_run"); const duplicateClaim = await claimTaskUsage(root, prepared.agentId, first.request.taskId, "origin", undefined, "call-2", "subagent_get"); assert.equal(firstClaim.created, true); assert.equal(duplicateClaim.created, false); assert.equal(duplicateClaim.claim.toolCallId, "call-1");
    const second = await createTask(root, prepared.agentId, "second prompt"); assert.notEqual(second.request.taskId, first.request.taskId); await requestTaskCancellation(root, prepared.agentId, second.request.taskId, "cancelled by caller"); const stopped = await readAgentSnapshot(root, prepared.agentId, second.request.taskId); assert.equal(stopped.task?.status.state, "stopped"); assert.equal(stopped.status.state, "idle");
});
void test("task lookup isolates origin sessions", async () => { const root = await mkdtemp(join(tmpdir(), "orchestration-origin-")); const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "other-origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory); await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "other-origin", tmux, capabilities }); await patchAgentStatus(prepared.paths, { state: "idle" }); const task = await createTask(root, prepared.agentId, "foreign"); await assert.rejects(findTaskAgent(root, task.request.taskId, "current-origin"), /not found in this origin/u); assert.equal((await readAgentSnapshot(root, prepared.agentId, task.request.taskId)).task?.status.state, "created"); });
void test("schema-v2 persisted task records reject unknown keys", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-exact-record-")); const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory); await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities }); await patchAgentStatus(prepared.paths, { state: "idle" }); const task = await createTask(root, prepared.agentId, "prompt"); const requestPath = join(task.directory, "request.json"); const request = JSON.parse(await readFile(requestPath, "utf8")); await writeFile(requestPath, JSON.stringify({ ...request, purpose: "legacy" })); await assert.rejects(readAgentSnapshot(root, prepared.agentId, task.request.taskId), /unknown keys.*purpose/u);
});
void test("every schema-v2 record rejects missing, mistyped, invalid-enum, or path-mismatched state at the store boundary", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-malformed-records-")); const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory); await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities }); await patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true }); const task = await createTask(root, prepared.agentId, "validate records"); await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded", output: "done" }); await requestTaskCancellation(root, prepared.agentId, task.request.taskId, "already terminal"); await claimTaskUsage(root, prepared.agentId, task.request.taskId, "origin", undefined, "call", "subagent_get");
    const paths = taskPaths(root, prepared.agentId, task.request.taskId); const otherId = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
    const rejects = async (path: string, change: (value: Record<string, unknown>) => Record<string, unknown>, read: () => Promise<unknown>, pattern: RegExp) => { const original = await readFile(path, "utf8"); const value = JSON.parse(original) as Record<string, unknown>; await writeFile(path, JSON.stringify(change(value))); await assert.rejects(read(), pattern); await writeFile(path, original); };
    await rejects(prepared.paths.agent, value => { const { cwd: _cwd, ...rest } = value; return rest; }, () => readAgentSnapshot(root, prepared.agentId), /missing required keys.*cwd/u);
    await rejects(prepared.paths.status, value => ({ ...value, state: "unknown" }), () => readAgentSnapshot(root, prepared.agentId), /state is invalid/u);
    await rejects(paths.request, value => ({ ...value, agentId: otherId }), () => readAgentSnapshot(root, prepared.agentId, task.request.taskId), /does not match path identity/u);
    await rejects(paths.status, value => { const { createdAt: _createdAt, ...rest } = value; return rest; }, () => readAgentSnapshot(root, prepared.agentId, task.request.taskId), /missing required keys.*createdAt/u);
    await rejects(paths.result, value => ({ ...value, turns: "one" }), () => readAgentSnapshot(root, prepared.agentId, task.request.taskId), /turns must be/u);
    await writeFile(paths.cancel, JSON.stringify({ schemaVersion: 2, agentId: prepared.agentId, taskId: task.request.taskId, requestedAt: new Date().toISOString(), reason: "test" })); await rejects(paths.cancel, value => ({ ...value, taskId: otherId }), () => readTaskCancellation(root, prepared.agentId, task.request.taskId), /does not match path identity/u);
    await rejects(paths.usageClaim, value => ({ ...value, toolName: "legacy" }), () => readAgentSnapshot(root, prepared.agentId, task.request.taskId), /toolName is invalid/u);
});
void test("persisted agent identity must match its immutable launch envelope before reuse", async () => { const root = await mkdtemp(join(tmpdir(), "orchestration-agent-identity-")); const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory); await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities }); const record = JSON.parse(await readFile(prepared.paths.agent, "utf8")); await writeFile(prepared.paths.agent, JSON.stringify({ ...record, agent: "explorer" })); await assert.rejects(readAgentSnapshot(root, prepared.agentId), /identity does not match its immutable launch/u); });
void test("the five registered operations expose foreground, background, inspect, fan-in, stop, reuse, and usage-once outcomes", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-tools-")); const configPath = join(root, "orchestration.json"); await writeFile(configPath, JSON.stringify({ schemaVersion: 1, stateRoot: root, tmux: "/tmux", returnParentCommand: "/parent", parentNavigationHint: "parent", historyViewerExtension: "/history", popupExtension: "/popup", orchestrationExtension: "/orchestration", childBridgeExtension: "/bridge", harnesses: { pi: { adapter: "pi-native", command: "/pi" } }, maxDepth: 3, natureHandleWords: ["May"], delegation: { "mode:recon": ["explorer", "reviewer", "codex"], "mode:ops": ["explorer", "worker", "validator", "reviewer", "fast-worker", "codex"], "agent:reviewer": ["critic"] } }));
    const createIdleAgent = async () => { const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities }); const envelope = await persistEnvelope(prepared.paths.directory); await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities }); await patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true }); return prepared; };
    const exec = async (_command: string, args: string[]) => { const command = args.join(" "); if (command.includes("#{pid}")) return { stdout: "1\n", stderr: "", code: 0 }; if (command.includes("list-panes")) return { stdout: "%1\t0\n", stderr: "", code: 0 }; return { stdout: "", stderr: "", code: 0 }; }; const current = { identity: "mode:ops", targets: { worker: definition }, catalog: settledAgentCatalog() }; const ctx = { cwd: "/work", sessionManager: { getSessionId: () => "origin", getSessionFile: () => undefined } } as never;
    const foreground = await createIdleAgent(); let completedForeground = false; const run = createSubagentRunTool({ configPath, env: {}, exec, activeCaller: () => current, sleep: async () => { if (!completedForeground) { completedForeground = true; const active = await readAgentSnapshot(root, foreground.agentId); await finishTask(root, foreground.agentId, active.status.activeTaskId!, { outcome: "succeeded", output: "foreground", usage: { ...emptyUsage(), input: 2, totalTokens: 2 } }); } } }); const runResult = await run.execute("run-call", { agentId: foreground.agentId, prompt: "foreground prompt" }, undefined, undefined, ctx); assert.match((runResult.content[0] as { text: string }).text, /succeeded/u); assert.equal(runResult.usage?.totalTokens, 2);
    const inspect = await createSubagentGetTool({ configPath, env: {}, exec, activeCaller: () => current }).execute("get-call", { agentId: foreground.agentId }, undefined, undefined, ctx); assert.equal(inspect.usage, undefined);
    const background = await createIdleAgent(); const submit = await createSubagentSubmitTool({ configPath, env: {}, exec, activeCaller: () => current }).execute("submit-call", { agentId: background.agentId, prompt: "background prompt" }, undefined, undefined, ctx); const submittedTaskId = (submit.details as { task: { request: { taskId: string } } }).task.request.taskId; assert.match((submit.content[0] as { text: string }).text, new RegExp(submittedTaskId, "u"));
    const second = await createIdleAgent(); const secondTask = await createTask(root, second.agentId, "second background"); await finishTask(root, background.agentId, submittedTaskId, { outcome: "succeeded", output: "first done" }); const waitAny = await createSubagentWaitTool({ configPath, env: {}, exec, activeCaller: () => current, sleep: async () => {} }).execute("wait-any", { taskIds: [submittedTaskId, secondTask.request.taskId], condition: "any" }, undefined, undefined, ctx); assert.match((waitAny.content[0] as { text: string }).text, /completed/u); let finishedSecond = false; const waitAll = await createSubagentWaitTool({ configPath, env: {}, exec, activeCaller: () => current, sleep: async () => { if (!finishedSecond) { finishedSecond = true; await finishTask(root, second.agentId, secondTask.request.taskId, { outcome: "succeeded", output: "second done" }); } } }).execute("wait-all", { taskIds: [submittedTaskId, secondTask.request.taskId], condition: "all" }, undefined, undefined, ctx); assert.match((waitAll.content[0] as { text: string }).text, /completed/u);
    const stoppable = await createTask(root, background.agentId, "stop this task"); const stopped = await createSubagentStopTool({ configPath, env: {}, exec, activeCaller: () => current }).execute("stop-call", { taskId: stoppable.request.taskId }, undefined, undefined, ctx); assert.equal((stopped.details as { stopDisposition: string }).stopDisposition, "stopped-now"); assert.equal((await readAgentSnapshot(root, background.agentId, stoppable.request.taskId)).task?.status.state, "stopped");
});
void test("a restricted reviewer cannot inspect, wait on, stop, or discover a same-origin worker", async () => {
    const root = await mkdtemp(join(tmpdir(), "orchestration-reviewer-boundary-"));
    const configPath = join(root, "orchestration.json");
    await writeFile(configPath, JSON.stringify({ schemaVersion: 1, stateRoot: root, tmux: "/tmux", returnParentCommand: "/parent", parentNavigationHint: "parent", historyViewerExtension: "/history", popupExtension: "/popup", orchestrationExtension: "/orchestration", childBridgeExtension: "/bridge", harnesses: { pi: { adapter: "pi-native", command: "/pi" } }, maxDepth: 3, natureHandleWords: ["May"], delegation: { "mode:recon": ["explorer", "reviewer", "codex"], "mode:ops": ["explorer", "worker", "validator", "reviewer", "fast-worker", "codex"], "agent:reviewer": ["critic"] } }));
    const prepared = await prepareAgent(root, { agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: "pending", lineage: { callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin" }, capabilities });
    const envelope = await persistEnvelope(prepared.paths.directory);
    await publishAgent(prepared.paths, { agentId: prepared.agentId, agent: "worker", harness: "pi", cwd: "/work", agentSnapshot: definition, launchEnvelope: envelope, callerIdentity: "mode:ops", targetAgent: "worker", depth: 1, originSessionId: "origin", tmux, capabilities });
    await patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true });
    const task = await createTask(root, prepared.agentId, "worker task");
    const exec = async () => ({ stdout: "", stderr: "", code: 0 });
    const reviewer = { identity: "agent:reviewer", targets: { critic: settledAgentDefinition("critic") }, catalog: settledAgentCatalog() };
    const deps = { configPath, env: { PI_SUBAGENT_AGENT_ID: "reviewer-id", PI_SUBAGENT_ORIGIN_SESSION_ID: "origin" }, exec, activeCaller: () => reviewer };
    const ctx = { cwd: "/work", sessionManager: { getSessionId: () => "child", getSessionFile: () => undefined } } as never;
    await assert.rejects(createSubagentGetTool(deps).execute("get", { agentId: prepared.agentId }, undefined, undefined, ctx), /not allowed to access agent worker/u);
    await assert.rejects(createSubagentWaitTool(deps).execute("wait", { taskIds: [task.request.taskId], condition: "all" }, undefined, undefined, ctx), /not allowed to access agent worker/u);
    await assert.rejects(createSubagentStopTool(deps).execute("stop-agent", { agentId: prepared.agentId }, undefined, undefined, ctx), /not allowed to access agent worker/u);
    await assert.rejects(createSubagentStopTool(deps).execute("stop-task", { taskId: task.request.taskId }, undefined, undefined, ctx), /not allowed to access agent worker/u);
    assert.equal((await readAgentSnapshot(root, prepared.agentId, task.request.taskId)).task?.status.state, "created");
    const discovered = await new OriginAgentDiscovery({ stateRoot: root, originSessionId: "origin", authorizedAgents: ["critic"], exec, tmux: "/tmux" }).refresh();
    assert.deepEqual(discovered, { agents: [], malformedCount: 0 });
    await assert.rejects(stopSubagentAgent({ stateRoot: root, originSessionId: "origin", agentId: prepared.agentId, authorizedAgents: ["critic"], callerIdentity: "agent:reviewer", exec, tmux: "/tmux" }), /not allowed to manage agent worker/u);
});

void test("native child manifests are exact, ordered, reviewer-contribution-aware, and exclude parent mode", () => { const config = { schemaVersion: 1 as const, stateRoot: "/state", tmux: "/tmux", returnParentCommand: "/parent", parentNavigationHint: "parent", historyViewerExtension: "/history", popupExtension: "/changed-popup", orchestrationExtension: "/changed-orchestration", childBridgeExtension: "/changed-bridge", harnesses: { pi: { adapter: "pi-native" as const, command: "/pi" } }, maxDepth: 3, natureHandleWords: ["May"], delegation: { "mode:recon": ["explorer", "reviewer", "codex"], "mode:ops": ["explorer", "worker", "validator", "reviewer", "fast-worker", "codex"], "agent:reviewer": ["critic"] } }; const envelope = buildLaunchEnvelope("reviewer", settledAgentCatalog(), config.delegation, ["/popup", "/orchestration", "/bridge"]); assert.deepEqual(envelope.childExtensions, { reviewer: ["/popup", "/orchestration", AGENT_ARTIFACT_EXTENSION, "/bridge"], critic: ["/popup", "/orchestration", "/bridge"] }); const launch = piLaunchDescriptor(config, { agentId: "a", agentDirectory: "/state/agents/a", agent: "reviewer", launchEnvelope: "/state/agents/a/launch-envelope.json", launchEnvelopeSnapshot: envelope, depth: 1, originSessionId: "origin" }); assert.deepEqual(launch.args.filter((value, index) => launch.args[index - 1] === "-e"), envelope.childExtensions.reviewer); assert.ok(!launch.args.includes("--profile") && !launch.args.includes("--mode")); assert.equal(launch.env.PI_AGENT_RESOLVED_AGENT, "/state/agents/a/launch-envelope.json"); });
