import assert from "node:assert/strict";
import { chmod, mkdir, utimes, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";
import { createSubagentRunTool } from "../extensions_src/subagent.ts";
import { withRunLock } from "../extensions_src/utilities/subagent_lock.ts";
import { claimPendingTask, claimTaskUsage, createTask, failAgent, finishTask, markAgentStopping, markBridgeReady, patchAgentStatus, prepareAgent, publishAgent, readAgentSnapshot, readTaskCancellation, reconcileOriginUsageClaims, requestTaskCancellation, recordIdleUsage, recordIntervention, taskPaths } from "../extensions_src/utilities/subagent_store.ts";
import { stopSubagentAgentWithDisposition, stopSubagentTaskWithDisposition } from "../extensions_src/utilities/subagent_management.ts";
import { type CommandResult } from "../extensions_src/utilities/subagent_tmux.ts";
import { emptyUsage } from "../extensions_src/utilities/subagent_types.ts";
import { nativeConfig as config, nativeProfile as profile, nativeTmux as tmux, subagentTestRoot } from "./subagent_native_helpers.ts";

void test("run lock reclaims an aged ownerless directory without waiting for the retry ceiling", async () => {
    const root = await subagentTestRoot("native-ownerless-lock-");
    const lock = join(root, ".lock");
    await mkdir(lock, { mode: 0o700 });
    const old = new Date(Date.now() - 5000);
    await utimes(lock, old, old);
    const started = performance.now();
    assert.equal(await withRunLock(root, async () => "claimed"), "claimed");
    assert.ok(performance.now() - started < 1000);
});
void test("agent store separates persistent agent and sequential task identities", async () => { const root = await subagentTestRoot("native-agent-"); const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } }); await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }); await (await import("../extensions_src/utilities/subagent_store.ts")).patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true }); const first = await createTask(root, prepared.agentId, "first", "inspect"); assert.notEqual(first.request.taskId, prepared.agentId); await claimPendingTask(root, prepared.agentId); await recordIntervention(root, prepared.agentId, { taskId: first.request.taskId, text: "also check tests", deliveryMode: "steer", images: [] }); assert.equal((await readAgentSnapshot(root, prepared.agentId, first.request.taskId)).task?.interventions[0]?.text, "also check tests"); await finishTask(root, prepared.agentId, first.request.taskId, { outcome: "succeeded", output: "done", turns: 1 }); assert.equal((await readAgentSnapshot(root, prepared.agentId)).status.state, "idle"); const second = await createTask(root, prepared.agentId, "again", "retest"); assert.notEqual(second.request.taskId, first.request.taskId); const terminal = await readAgentSnapshot(root, prepared.agentId, first.request.taskId); assert.equal(terminal.task?.result?.interventions[0]?.text, "also check tests"); });
void test("diagnostic event failures do not orphan committed task transitions", async () => {
    const root = await subagentTestRoot("native-event-failure-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await patchAgentStatus(prepared.paths, { state: "idle" });
    await chmod(prepared.paths.events, 0o400);
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    assert.equal(task.status.state, "created");
    assert.equal((await claimPendingTask(root, prepared.agentId))?.status.state, "running");
    await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded" });
    assert.equal((await readAgentSnapshot(root, prepared.agentId, task.request.taskId)).status.state, "idle");
});
void test("busy agents reject sends without creating another task", async () => { const root = await subagentTestRoot("native-busy-"); const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } }); await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }); await (await import("../extensions_src/utilities/subagent_store.ts")).patchAgentStatus(prepared.paths, { state: "idle" }); const first = await createTask(root, prepared.agentId, "first", "inspect"); await assert.rejects(createTask(root, prepared.agentId, "second", "queue me"), new RegExp(`busy.*${first.request.taskId}`)); });
void test("usage claims recover when the parent tool result was not persisted", async () => {
    const root = await subagentTestRoot("native-claim-");
    const sessionFile = join(root, "parent.jsonl");
    await writeFile(sessionFile, "");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin", originSessionFile: sessionFile }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin", originSessionFile: sessionFile });
    await (await import("../extensions_src/utilities/subagent_store.ts")).patchAgentStatus(prepared.paths, { state: "idle" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    await claimPendingTask(root, prepared.agentId);
    await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded" });
    assert.equal((await claimTaskUsage(root, prepared.agentId, task.request.taskId, "origin", sessionFile, "call-a", "subagent_get")).created, true);
    assert.equal((await claimTaskUsage(root, prepared.agentId, task.request.taskId, "origin", sessionFile, "call-b", "subagent_get")).created, false);
    const childSessionFile = join(root, "child.jsonl");
    await writeFile(childSessionFile, "");
    assert.equal(await reconcileOriginUsageClaims(root, "origin", childSessionFile), 0);
    assert.equal((await claimTaskUsage(root, prepared.agentId, task.request.taskId, "origin", sessionFile, "call-still-owned", "subagent_get")).created, false);
    assert.equal(await reconcileOriginUsageClaims(root, "origin", sessionFile), 1);
    assert.equal((await claimTaskUsage(root, prepared.agentId, task.request.taskId, "origin", sessionFile, "call-c", "subagent_get")).created, true);
    await writeFile(sessionFile, `${JSON.stringify({ type: "message", message: { role: "toolResult", details: { accounting: { claimedTaskIds: [task.request.taskId] } } } })}\n`);
    assert.equal(await reconcileOriginUsageClaims(root, "origin", sessionFile), 0);
    assert.equal((await claimTaskUsage(root, prepared.agentId, task.request.taskId, "origin", sessionFile, "call-d", "subagent_get")).created, false);
});
void test("agent usage totals include parent tasks and idle human-originated turns", async () => {
    const root = await subagentTestRoot("native-agent-usage-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await (await import("../extensions_src/utilities/subagent_store.ts")).patchAgentStatus(prepared.paths, { state: "idle" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    await claimPendingTask(root, prepared.agentId);
    await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded", usage: { input: 1, output: 2, cacheRead: 3, cacheWrite: 4, totalTokens: 10, reasoning: 5, cacheWrite1h: 6, cost: { input: 1, output: 2, cacheRead: 3, cacheWrite: 4, total: 10 } } });
    await recordIdleUsage(root, prepared.agentId, { input: 10, output: 20, cacheRead: 30, cacheWrite: 40, totalTokens: 100, reasoning: 50, cacheWrite1h: 60, cost: { input: 10, output: 20, cacheRead: 30, cacheWrite: 40, total: 100 } });
    const total = (await readAgentSnapshot(root, prepared.agentId)).status.agentUsage;
    assert.deepEqual(total, { input: 11, output: 22, cacheRead: 33, cacheWrite: 44, totalTokens: 110, reasoning: 55, cacheWrite1h: 66, cost: { input: 11, output: 22, cacheRead: 33, cacheWrite: 44, total: 110 } });
});
void test("terminal task replay repairs agent usage exactly once after a partial completion commit", async () => {
    const root = await subagentTestRoot("native-partial-completion-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await (await import("../extensions_src/utilities/subagent_store.ts")).patchAgentStatus(prepared.paths, { state: "idle" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    const running = await claimPendingTask(root, prepared.agentId);
    assert.ok(running);
    const usage = { input: 7, output: 8, cacheRead: 9, cacheWrite: 10, totalTokens: 34, cost: { input: 1, output: 2, cacheRead: 3, cacheWrite: 4, total: 10 } };
    const files = taskPaths(root, prepared.agentId, task.request.taskId);
    const finishedAt = new Date().toISOString();
    await writeFile(files.result, `${JSON.stringify({ schemaVersion: 1, agentId: prepared.agentId, taskId: task.request.taskId, outcome: "succeeded", output: "done", usage, turns: 1, interventions: [], startedAt: running!.status.startedAt, finishedAt })}\n`);
    await writeFile(files.status, `${JSON.stringify({ ...running!.status, state: "succeeded", finishedAt })}\n`);
    assert.equal((await readAgentSnapshot(root, prepared.agentId)).status.agentUsage.input, 0);
    await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded" });
    await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded" });
    const repaired = (await readAgentSnapshot(root, prepared.agentId)).status;
    assert.equal(repaired.agentUsage.input, 7);
    assert.deepEqual(repaired.accountedTaskIds, [task.request.taskId]);
});
void test("replaying an old completion preserves a newer active task", async () => {
    const root = await subagentTestRoot("native-old-completion-replay-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await patchAgentStatus(prepared.paths, { state: "idle" });
    const first = await createTask(root, prepared.agentId, "first", "inspect");
    await claimPendingTask(root, prepared.agentId);
    await finishTask(root, prepared.agentId, first.request.taskId, { outcome: "succeeded" });
    const second = await createTask(root, prepared.agentId, "second", "retest");
    await finishTask(root, prepared.agentId, first.request.taskId, { outcome: "succeeded" });
    const replayed = await readAgentSnapshot(root, prepared.agentId, second.request.taskId);
    assert.equal(replayed.status.state, "busy");
    assert.equal(replayed.status.activeTaskId, second.request.taskId);
    assert.equal(replayed.task?.status.state, "created");
});
void test("Stop wins a concurrent successful settle without exposing idle or a successful active task", async () => {
    const root = await subagentTestRoot("native-stop-settle-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    const store = await import("../extensions_src/utilities/subagent_store.ts");
    await store.patchAgentStatus(prepared.paths, { state: "idle" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    await claimPendingTask(root, prepared.agentId);
    await store.patchAgentStatus(prepared.paths, { state: "stopping" });
    const settled = await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded", output: "too late" });
    const stopping = await readAgentSnapshot(root, prepared.agentId, task.request.taskId);
    assert.equal(settled.outcome, "stopped");
    assert.equal(stopping.status.state, "stopping");
    assert.equal(stopping.task?.status.state, "stopped");
    await assert.rejects(createTask(root, prepared.agentId, "late", "must not start"), /stopping/u);
    await failAgent(root, prepared.agentId, "Stopped by parent", true);
    assert.equal((await readAgentSnapshot(root, prepared.agentId, task.request.taskId)).status.state, "stopped");
});
void test("bridge readiness preserves an initial task that became busy before readiness was committed", async () => {
    const root = await subagentTestRoot("native-ready-race-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    await markBridgeReady(prepared.paths);
    const snapshot = await readAgentSnapshot(root, prepared.agentId, task.request.taskId);
    assert.equal(snapshot.status.bridgeReady, true);
    assert.equal(snapshot.status.state, "busy");
    assert.equal(snapshot.status.activeTaskId, task.request.taskId);
    assert.equal((await claimPendingTask(root, prepared.agentId))?.request.taskId, task.request.taskId);
});
void test("Stop overrides a result-only provisional success before the task terminal transition", async () => {
    const root = await subagentTestRoot("native-result-stop-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    const store = await import("../extensions_src/utilities/subagent_store.ts");
    await store.patchAgentStatus(prepared.paths, { state: "idle" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    const running = await claimPendingTask(root, prepared.agentId);
    const files = taskPaths(root, prepared.agentId, task.request.taskId);
    await writeFile(files.result, `${JSON.stringify({ schemaVersion: 1, agentId: prepared.agentId, taskId: task.request.taskId, outcome: "succeeded", output: "provisional", usage: { input: 3, output: 4, cacheRead: 0, cacheWrite: 0, totalTokens: 7, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } }, turns: 1, interventions: [], startedAt: running!.status.startedAt, finishedAt: new Date().toISOString() })}\n`);
    await store.patchAgentStatus(prepared.paths, { state: "stopping" });
    const result = await finishTask(root, prepared.agentId, task.request.taskId, { outcome: "succeeded" });
    const snapshot = await readAgentSnapshot(root, prepared.agentId, task.request.taskId);
    assert.equal(result.outcome, "stopped");
    assert.equal(snapshot.task?.status.state, "stopped");
    assert.equal(snapshot.status.state, "stopping");
    assert.equal(snapshot.status.agentUsage.input, 3);
});
void test("Stop intent cannot overwrite a concurrent terminal transition", async () => {
    const root = await subagentTestRoot("native-stop-terminal-race-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await patchAgentStatus(prepared.paths, { state: "idle" });
    const task = await createTask(root, prepared.agentId, "first", "inspect");
    await failAgent(root, prepared.agentId, "child failed");
    const stopping = await markAgentStopping(prepared.paths);
    assert.equal(stopping.state, "failed");
    assert.equal((await readAgentSnapshot(root, prepared.agentId, task.request.taskId)).task?.status.state, "failed");
});
void test("failed Stop restores a live agent instead of reporting a false terminal state", async () => {
    const root = await subagentTestRoot("native-stop-error-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await patchAgentStatus(prepared.paths, { state: "idle" });
    let kills = 0;
    const exec = async (_command: string, args: string[]): Promise<CommandResult> => { if (args.at(-1) === "#{pid}") return { stdout: "10\n", stderr: "", code: 0 }; if (args.includes("kill-window")) { kills += 1; return { stdout: "", stderr: "permission denied", code: 1 }; } if (args.includes("has-session")) return { stdout: "", stderr: "", code: 0 }; if (args.includes("#{pane_id}\t#{pane_dead}")) return { stdout: "%2\t0\n", stderr: "", code: 0 }; return { stdout: "", stderr: "", code: 0 }; };
    const options = { stateRoot: root, agentId: prepared.agentId, originSessionId: "origin", exec, tmux: "/tmux" };
    const results = await Promise.allSettled([stopSubagentAgentWithDisposition(options), stopSubagentAgentWithDisposition(options)]);
    assert.ok(results.every(result => result.status === "rejected" && /permission denied/u.test(String(result.reason))));
    assert.equal(kills, 1);
    assert.equal((await readAgentSnapshot(root, prepared.agentId)).status.state, "idle");
});
void test("an already-aborted existing-agent run creates no task", async () => {
    const root = await subagentTestRoot("native-existing-pre-abort-");
    const configPath = join(root, "subagent.json");
    await writeFile(configPath, JSON.stringify(config(root)));
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true });
    const controller = new AbortController();
    controller.abort(new Error("pre-aborted"));
    const ctx = { sessionManager: { getSessionId: () => "origin", getSessionFile: () => undefined } } as unknown as import("@earendil-works/pi-coding-agent").ExtensionContext;
    await assert.rejects(createSubagentRunTool({ configPath, env: {}, exec: async () => ({ stdout: "", stderr: "", code: 0 }) }).execute("run", { agentId: prepared.agentId, purpose: "no task", prompt: "do not create" }, controller.signal, undefined, ctx), /pre-aborted/);
    const unchanged = await readAgentSnapshot(root, prepared.agentId);
    assert.equal(unchanged.status.state, "idle");
    assert.equal(unchanged.status.latestTaskId, undefined);
});
void test("durable task cancellation stops created work and forces running completion while preserving agent reuse", async () => {
    const root = await subagentTestRoot("native-task-cancel-");
    const prepared = await prepareAgent(root, { profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, lineage: { callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" }, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: true, interactiveInterventions: true } });
    await publishAgent(prepared.paths, { agentId: prepared.agentId, profile: "tester", purpose: "first", harness: "pi", cwd: "/work", profileSnapshot: profile, tmux, capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: true, interactiveInterventions: true }, callerProfile: "taskmaster", targetProfile: "tester", depth: 1, originSessionId: "origin" });
    await patchAgentStatus(prepared.paths, { state: "idle", bridgeReady: true });
    const created = await createTask(root, prepared.agentId, "created", "do not run");
    const cancelledCreated = await requestTaskCancellation(root, prepared.agentId, created.request.taskId, "cancel created");
    assert.equal(cancelledCreated.snapshot.task?.status.state, "stopped");
    assert.equal(await claimPendingTask(root, prepared.agentId), null);
    const running = await createTask(root, prepared.agentId, "running", "begin work");
    await claimPendingTask(root, prepared.agentId);
    await requestTaskCancellation(root, prepared.agentId, running.request.taskId, "cancel running");
    const repeatedStop = stopSubagentTaskWithDisposition({ stateRoot: root, agentId: prepared.agentId, taskId: running.request.taskId, originSessionId: "origin" });
    const completion = new Promise<void>((resolve, reject) => { setTimeout(() => { finishTask(root, prepared.agentId, running.request.taskId, { outcome: "succeeded", output: "partial", usage: emptyUsage(), turns: 1 }).then(() => resolve(), reject); }, 50); });
    assert.equal((await repeatedStop).disposition, "stop-pending");
    await completion;
    const stopped = await readAgentSnapshot(root, prepared.agentId, running.request.taskId);
    assert.equal(stopped.task?.status.state, "stopped");
    assert.equal(stopped.task?.result?.output, "partial");
    assert.equal(stopped.status.state, "idle");
    assert.equal((await readTaskCancellation(root, prepared.agentId, running.request.taskId))?.reason, "cancel running");
    const next = await createTask(root, prepared.agentId, "next", "reused");
    assert.equal(next.status.state, "created");
});
