#!/bin/bash

export WHITE=0xffffffff

### Catppuccin
export RED=0xfffb4934
export YELLOW=0xfffabd2f
export ORANGE=0xfffab387
export GREEN=0xffb8bb26
export GREEN_BG=0x19b8bb26
export LAVENDER=0xffebdbb2
export LAVENDER_BG=0x19ebdbb2
export PASTEL_BLUE=0xff5e81ac
export FLAMINGO=0xfffabd2f
export FLAMINGO_BG=0x19fabd2f
export PINK=0xfffb4934
export PINK_BG=0x19fb4934
export LIGHT_PINK=0xffffc0cd
export VIVID_RED=0xffff3366

export OVERLAY1=0xff928374

# General bar colors
export BAR_COLOR=0x00000000
export LABEL_COLOR=$OVERLAY1

export POPUP_BACKGROUND_COLOR=0xFF272936

# Item colors
export GENERAL_BACKGROUND=0xff231b33
export GENERAL_COLOR=0xffeaeef4

export SPACE_SELECTED=$LAVENDER
export SPACE_SELECTED_BACKGROUND=$LAVENDER_BG
export SPACE=$OVERLAY1
export SPACE_BACKGROUND=0x00000000

export CALENDAR=$GENERAL_COLOR
export CALENDAR_BACKGROUND=$PASTEL_BLUE

export BATTERY=$GREEN
export BATTERY_WARNING=$YELLOW
export BATTERY_CRITICAL=$RED
export BATTERY_BACKGROUND=$GREEN_BG

export CPU=$VIVID_RED
export CPU_BACKGROUND=$LIGHT_PINK

export WIFI=$FLAMINGO
export WIFI_BACKGROUND=$FLAMINGO_BG

export VOLUME=$PINK
export VOLUME_BACKGROUND=$PINK_BG
