import { createHash } from "node:crypto";
import { basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import type { ThinkingLevel } from "./mode_types.ts";

export type AgentHarness = "pi" | "cursor-agent" | "codex";
export interface AgentDefinition { model: string; description: string; thinkingLevel?: ThinkingLevel; tools: string[]; skillOptIns: string[]; instructions: string; harness: AgentHarness; harnessOptions?: Record<string, unknown>; childExtensionContributions: string[] }
export interface AgentCatalog { schemaVersion: 1; agents: Record<string, AgentDefinition> }
export interface MeshBudgets { maxLiveAgents: number; maxConcurrentTasks: number; maxTasksPerMesh: number }
export interface OrchestrationConfig { schemaVersion: 1; stateRoot: string; tmux: string; returnParentCommand: string; parentNavigationHint: string; historyViewerExtension: string; popupExtension: string; orchestrationExtension: string; childBridgeExtension: string; harnesses: Record<string, HarnessRuntimeConfig>; natureHandleWords: string[]; roleSets: Record<string, string[]>; budgets: MeshBudgets }
export interface HarnessRuntimeConfig { adapter: "pi-native" | "cursor-acp" | "codex-acp"; command: string; workerCommand?: string; workerEntrypoint?: string; bridgeReadyTimeoutMs?: number }
export interface AgentLaunchEnvelope { schemaVersion: 1; marker: "pi-mesh-agent-launch-v1"; meshId: string; agentId: string; epochId: string; identity: string; self: AgentDefinition; roleSet: string[]; catalog: Record<string, AgentDefinition>; policyDigest: string; childExtensions: Record<string, string[]> }

export const AGENT_ARTIFACT_EXTENSION = fileURLToPath(new URL("../agent_artifact.ts", import.meta.url));
export const WEB_SEARCH_EXTENSION = fileURLToPath(new URL("../web_search.ts", import.meta.url));
export const WEB_FETCH_EXTENSION = fileURLToPath(new URL("../web_fetch.ts", import.meta.url));
const cursorHarnessOptions = { mode: "agent", permissionPolicy: "allow-always", sandbox: "disabled", trustWorkspace: true, worktree: false } as const;
const codexHarnessOptions = { mode: "read-only", permissionPolicy: "reject", webSearch: "cached" } as const;
const settledRoleSets: Record<string, string[]> = {
    "mode:recon": ["explorer", "reviewer", "critic", "researcher", "codex"],
    "mode:ops": ["explorer", "worker", "validator", "reviewer", "critic", "researcher", "fast-worker", "codex"],
};
const settledAgents: Record<string, AgentDefinition> = {
    explorer: { model: "openai-codex/gpt-5.6-luna", description: "Read-only bounded repository evidence gathering.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: ["codebase-exploration"], instructions: "Investigate one bounded repository question and return concise evidence with file references.", harness: "pi", childExtensionContributions: [] },
    worker: { model: "openai-codex/gpt-5.6-sol", description: "Bounded source implementation and repair.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash", "write", "edit"], skillOptIns: ["source-implementation"], instructions: "Complete the bounded source objective, inspect the diff, and return changed files, diagnostics, deviations, and risks.", harness: "pi", childExtensionContributions: [] },
    validator: { model: "openai-codex/gpt-5.6-luna", description: "Read-only automated implementation validation.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: ["implementation-validation"], instructions: "Run the caller's requested automated validation objective without changing repository source and return concrete evidence.", harness: "pi", childExtensionContributions: [] },
    reviewer: { model: "openai-codex/gpt-5.6-sol", description: "Read-only review consolidator that may request an independent critic task.", thinkingLevel: "high", tools: ["read", "grep", "find", "ls", "bash", "mesh_enable", "mesh_run", "mesh_submit", "mesh_get", "mesh_wait", "mesh_stop", "mesh_route", "save_agent_artifact"], skillOptIns: ["adaptive-review", "task-orchestration", "agent-artifact"], instructions: "Review the defined target, request an independent critic task for a concrete lens when useful, consolidate the review outcome, and save one review report when requested.", harness: "pi", childExtensionContributions: [AGENT_ARTIFACT_EXTENSION] },
    critic: { model: "openai-codex/gpt-5.6-terra", description: "Read-only independent focused review peer for a caller-supplied lens or dossier.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: [], instructions: "Independently review only the caller-supplied lens or dossier and return severity-ordered evidence, gaps, and residual risk.", harness: "pi", childExtensionContributions: [] },
    researcher: { model: "openai-codex/gpt-5.6-terra", description: "Read-only bounded Web research with claim-linked evidence.", thinkingLevel: "high", tools: ["read", "grep", "find", "ls", "bash", "web_search", "web_fetch"], skillOptIns: ["web-research"], instructions: "Investigate the bounded research question using read operations only, apply web-research, and return its claim-linked evidence brief. Report decision-critical missing context instead of guessing.", harness: "pi", childExtensionContributions: [WEB_SEARCH_EXTENSION, WEB_FETCH_EXTENSION] },
    "fast-worker": { model: "cursor/cursor-grok-4.5-high-fast", description: "Fast bounded source worker through Cursor ACP; usage and interactive parity are limited.", tools: [], skillOptIns: [], instructions: "Implement the bounded source objective in the current workspace, validate proportionately, and return changed files, evidence, deviations, and risks.", harness: "cursor-agent", harnessOptions: cursorHarnessOptions, childExtensionContributions: [] },
    codex: { model: "codex/gpt-5.6-luna", description: "Read-only bounded source-backed Web research peer through Codex ACP.", thinkingLevel: "high", tools: [], skillOptIns: [], instructions: "Use Codex's built-in Web search to investigate the bounded research question. Return a concise evidence brief containing the conclusion, source URLs with the claim each supports, freshness, and material uncertainty. Read workspace context only when the task requires it. If evidence is insufficient, state what is missing.", harness: "codex", harnessOptions: codexHarnessOptions, childExtensionContributions: [] },
};
const historicalAgentSnapshots: Partial<Record<string, AgentDefinition[]>> = {
    reviewer: [{ model: "openai-codex/gpt-5.6-sol", description: "Read-only adaptive review owner with optional critic delegation.", thinkingLevel: "high", tools: ["read", "grep", "find", "ls", "bash", "mesh_enable", "mesh_run", "mesh_submit", "mesh_get", "mesh_wait", "mesh_stop", "mesh_route", "save_agent_artifact"], skillOptIns: ["adaptive-review", "task-orchestration", "agent-artifact"], instructions: "Review the defined target, delegate only a concrete independent critic lens when useful, and save one review report when requested.", harness: "pi", childExtensionContributions: [AGENT_ARTIFACT_EXTENSION] }],
    critic: [{ model: "openai-codex/gpt-5.6-terra", description: "Read-only focused or dissenting review leaf.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: [], instructions: "Review only the caller-supplied lens or dossier and return severity-ordered evidence, gaps, and residual risk.", harness: "pi", childExtensionContributions: [] }],
    codex: [{ model: "codex/gpt-5.6-luna", description: "Read-only, source-backed Web research leaf through Codex ACP.", thinkingLevel: "high", tools: [], skillOptIns: [], instructions: "Use Codex's built-in Web search to investigate the delegated question. Return a concise evidence brief containing the conclusion, source URLs with the claim each supports, freshness, and material uncertainty. Read workspace context only when the task requires it. If evidence is insufficient, state what is missing.", harness: "codex", harnessOptions: codexHarnessOptions, childExtensionContributions: [] }],
};

export function settledAgentCatalog(): AgentCatalog { return { schemaVersion: 1, agents: structuredClone(settledAgents) }; }
export function settledAgentDefinition(name: string): AgentDefinition { const definition = settledAgents[name]; if (!definition) throw new Error(`Unsupported settled agent: ${name}`); return structuredClone(definition); }
export function settledMeshRoleSets(): Record<string, string[]> { return structuredClone(settledRoleSets); }

export function canonicalJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`).join(",")}}`; return JSON.stringify(value); }
function same(left: unknown, right: unknown): boolean { return canonicalJson(left) === canonicalJson(right); }
function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, keys: readonly string[], label: string): void { const unknown = Object.keys(value).filter(key => !keys.includes(key)); if (unknown.length) throw new Error(`${label} contains unknown keys: ${unknown.join(", ")}`); const missing = keys.filter(key => !(key in value)); if (missing.length) throw new Error(`${label} is missing required keys: ${missing.join(", ")}`); }
function text(value: unknown, label: string): string { if (typeof value !== "string" || !value.trim()) throw new Error(`${label} must be a non-empty string`); return value; }
function strings(value: unknown, label: string): string[] { if (!Array.isArray(value) || value.some(item => typeof item !== "string" || !item.trim())) throw new Error(`${label} must be an array of non-empty strings`); const out = [...value] as string[]; if (new Set(out).size !== out.length) throw new Error(`${label} must not contain duplicates`); return out; }
function positiveInteger(value: unknown, label: string): number { if (!Number.isInteger(value) || Number(value) <= 0) throw new Error(`${label} must be a positive integer`); return Number(value); }
function uuid(value: unknown, label: string): string { const id = text(value, label); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(id)) throw new Error(`${label} must be a UUID`); return id; }

function nixStoreContributionIdentity(path: string): string | undefined { const match = path.match(/^\/nix\/store\/[0-9a-z]{32}-([^/]+)\/(.+)$/u); return match ? `${match[1]}/${match[2]}` : undefined; }
function sourceContributionIdentity(path: string): string | undefined { return [AGENT_ARTIFACT_EXTENSION, WEB_SEARCH_EXTENSION, WEB_FETCH_EXTENSION].includes(path) ? `${basename(dirname(path))}/${basename(path)}` : undefined; }
function sameContributionSnapshot(path: string, expected: string): boolean {
    if (path === expected) return true;
    const actualIdentity = nixStoreContributionIdentity(path) ?? sourceContributionIdentity(path);
    const expectedIdentity = nixStoreContributionIdentity(expected) ?? sourceContributionIdentity(expected);
    return actualIdentity !== undefined && actualIdentity === expectedIdentity;
}
function definitionKeys(raw: Record<string, unknown>): string[] { return ["model", "description", "tools", "skillOptIns", "instructions", "harness", "childExtensionContributions", ...(raw.thinkingLevel === undefined ? [] : ["thinkingLevel"]), ...(raw.harnessOptions === undefined ? [] : ["harnessOptions"])]; }
function validateDefinitionShape(name: string, value: unknown, label: string): { raw: Record<string, unknown>; expected: AgentDefinition } {
    const expected = settledAgents[name]; if (!expected) throw new Error(`${label} uses unsupported agent name ${name}`);
    const raw = object(value, label); exact(raw, definitionKeys(raw), label); strings(raw.childExtensionContributions, `${label}.childExtensionContributions`);
    return { raw, expected };
}
export function validateAgentDefinition(name: string, value: unknown, label = `agent definition ${name}`): AgentDefinition {
    const { raw, expected } = validateDefinitionShape(name, value, label);
    if (!same(raw, expected)) throw new Error(`${label} must exactly match the settled ${name} capability contract`);
    return structuredClone(expected);
}
export function validateAgentDefinitionSnapshot(name: string, value: unknown, label = `agent definition snapshot ${name}`): AgentDefinition {
    const { raw, expected } = validateDefinitionShape(name, value, label);
    const candidates = [expected, ...(historicalAgentSnapshots[name] ?? [])];
    const matches = candidates.some(candidate => {
        const rawContributions = raw.childExtensionContributions as string[];
        const sameContributions = rawContributions.length === candidate.childExtensionContributions.length && rawContributions.every((path, index) => sameContributionSnapshot(path, candidate.childExtensionContributions[index]!));
        return sameContributions && same({ ...raw, childExtensionContributions: [] }, { ...candidate, childExtensionContributions: [] });
    });
    if (!matches) throw new Error(`${label} must match a settled ${name} capability contract`);
    return structuredClone(raw) as unknown as AgentDefinition;
}
export function validateOrchestrationConfig(value: unknown): OrchestrationConfig {
    const root = object(value, "orchestration config"); exact(root, ["schemaVersion", "stateRoot", "tmux", "returnParentCommand", "parentNavigationHint", "historyViewerExtension", "popupExtension", "orchestrationExtension", "childBridgeExtension", "harnesses", "natureHandleWords", "roleSets", "budgets"], "orchestration config");
    if (root.schemaVersion !== 1) throw new Error("Unsupported orchestration config schemaVersion");
    const harnesses: Record<string, HarnessRuntimeConfig> = {};
    for (const [name, value] of Object.entries(object(root.harnesses, "harnesses"))) { const item = object(value, `harnesses.${name}`); const keys = ["adapter", "command", ...(item.workerCommand === undefined ? [] : ["workerCommand"]), ...(item.workerEntrypoint === undefined ? [] : ["workerEntrypoint"]), ...(item.bridgeReadyTimeoutMs === undefined ? [] : ["bridgeReadyTimeoutMs"])]; exact(item, keys, `harnesses.${name}`); if (item.adapter !== "pi-native" && item.adapter !== "cursor-acp" && item.adapter !== "codex-acp") throw new Error(`harnesses.${name}.adapter is invalid`); harnesses[name] = { adapter: item.adapter, command: text(item.command, `harnesses.${name}.command`), ...(item.workerCommand === undefined ? {} : { workerCommand: text(item.workerCommand, `harnesses.${name}.workerCommand`) }), ...(item.workerEntrypoint === undefined ? {} : { workerEntrypoint: text(item.workerEntrypoint, `harnesses.${name}.workerEntrypoint`) }), ...(item.bridgeReadyTimeoutMs === undefined ? {} : { bridgeReadyTimeoutMs: positiveInteger(item.bridgeReadyTimeoutMs, `harnesses.${name}.bridgeReadyTimeoutMs`) }) }; }
    const roleSets = Object.fromEntries(Object.entries(object(root.roleSets, "roleSets")).map(([mode, roles]) => [mode, strings(roles, `roleSets.${mode}`)])); if (!same(roleSets, settledRoleSets)) throw new Error("roleSets must exactly match the settled mode role sets");
    const budgetRaw = object(root.budgets, "budgets"); exact(budgetRaw, ["maxLiveAgents", "maxConcurrentTasks", "maxTasksPerMesh"], "budgets"); const budgets = { maxLiveAgents: positiveInteger(budgetRaw.maxLiveAgents, "budgets.maxLiveAgents"), maxConcurrentTasks: positiveInteger(budgetRaw.maxConcurrentTasks, "budgets.maxConcurrentTasks"), maxTasksPerMesh: positiveInteger(budgetRaw.maxTasksPerMesh, "budgets.maxTasksPerMesh") }; if (budgets.maxConcurrentTasks > budgets.maxTasksPerMesh) throw new Error("maxConcurrentTasks must not exceed maxTasksPerMesh");
    return { schemaVersion: 1, stateRoot: text(root.stateRoot, "stateRoot"), tmux: text(root.tmux, "tmux"), returnParentCommand: text(root.returnParentCommand, "returnParentCommand"), parentNavigationHint: text(root.parentNavigationHint, "parentNavigationHint"), historyViewerExtension: text(root.historyViewerExtension, "historyViewerExtension"), popupExtension: text(root.popupExtension, "popupExtension"), orchestrationExtension: text(root.orchestrationExtension, "orchestrationExtension"), childBridgeExtension: text(root.childBridgeExtension, "childBridgeExtension"), harnesses, natureHandleWords: strings(root.natureHandleWords, "natureHandleWords"), roleSets, budgets };
}
/** Transitional function name for downstream W2; validation is mesh-v2 only. */
export const validateDelegationConfig = validateOrchestrationConfig;
export function validateAgentCatalog(value: unknown): AgentCatalog { const root = object(value, "agent catalog"); exact(root, ["schemaVersion", "agents"], "agent catalog"); if (root.schemaVersion !== 1) throw new Error("Unsupported agent catalog schemaVersion"); const raw = object(root.agents, "agents"); if (!same(Object.keys(raw).sort(), Object.keys(settledAgents).sort())) throw new Error("agent catalog must contain exactly the eight settled agents"); return { schemaVersion: 1, agents: Object.fromEntries(Object.entries(raw).map(([name, definition]) => [name, validateAgentDefinition(name, definition, `agents.${name}`)])) }; }
export function policyDigest(input: { mode: string; roleSet: readonly string[]; roles: Record<string, AgentDefinition> }): string { return createHash("sha256").update(canonicalJson({ mode: input.mode, roleSet: input.roleSet, roles: input.roles })).digest("hex"); }
export function launchEnvelopeDigest(envelope: AgentLaunchEnvelope): string { return createHash("sha256").update(canonicalJson(validateLaunchEnvelope(envelope))).digest("hex"); }
export function validateLaunchEnvelope(value: unknown): AgentLaunchEnvelope {
    const root = object(value, "agent launch envelope"); exact(root, ["schemaVersion", "marker", "meshId", "agentId", "epochId", "identity", "self", "roleSet", "catalog", "policyDigest", "childExtensions"], "agent launch envelope"); if (root.schemaVersion !== 1 || root.marker !== "pi-mesh-agent-launch-v1") throw new Error("Unsupported agent launch envelope schema or marker");
    const meshId = uuid(root.meshId, "meshId"); const agentId = uuid(root.agentId, "agentId"); const epochId = uuid(root.epochId, "epochId"); const identity = text(root.identity, "identity"); if (!identity.startsWith("agent:")) throw new Error("launch identity must use agent namespace"); const selfName = identity.slice(6); const self = validateAgentDefinitionSnapshot(selfName, root.self, "self"); const roleSet = strings(root.roleSet, "roleSet"); if (!roleSet.includes(selfName)) throw new Error("launch roleSet must include self");
    const catalogRaw = object(root.catalog, "catalog"); if (!same(Object.keys(catalogRaw).sort(), [...roleSet].sort())) throw new Error("launch catalog must exactly cover roleSet"); const catalog = Object.fromEntries(Object.entries(catalogRaw).map(([name, definition]) => [name, validateAgentDefinitionSnapshot(name, definition, `catalog.${name}`)])); if (!same(catalog[selfName], self)) throw new Error("launch self does not match catalog");
    const extensionRaw = object(root.childExtensions, "childExtensions"); if (!same(Object.keys(extensionRaw).sort(), [...roleSet].sort())) throw new Error("childExtensions must exactly cover roleSet"); const childExtensions = Object.fromEntries(Object.entries(extensionRaw).map(([name, paths]) => [name, strings(paths, `childExtensions.${name}`)])); const digest = text(root.policyDigest, "policyDigest"); if (!/^[0-9a-f]{64}$/u.test(digest)) throw new Error("policyDigest must be a SHA-256 digest");
    return { schemaVersion: 1, marker: "pi-mesh-agent-launch-v1", meshId, agentId, epochId, identity, self, roleSet, catalog, policyDigest: digest, childExtensions };
}
export function buildLaunchEnvelope(input: { meshId: string; agentId: string; epochId: string; agent: string; mode: string; roleSet: readonly string[]; catalog: AgentCatalog; childExtensions: Record<string, string[]> }): AgentLaunchEnvelope { const roles = Object.fromEntries(input.roleSet.map(name => { const definition = input.catalog.agents[name]; if (!definition) throw new Error(`Unknown epoch role: ${name}`); return [name, structuredClone(definition)]; })); const self = roles[input.agent]; if (!self) throw new Error(`Agent ${input.agent} is outside the policy epoch`); return validateLaunchEnvelope({ schemaVersion: 1, marker: "pi-mesh-agent-launch-v1", meshId: input.meshId, agentId: input.agentId, epochId: input.epochId, identity: `agent:${input.agent}`, self, roleSet: [...input.roleSet], catalog: roles, policyDigest: policyDigest({ mode: input.mode, roleSet: input.roleSet, roles }), childExtensions: input.childExtensions }); }
export function projectLaunchEnvelope(agent: string, agentId: string, parent: AgentLaunchEnvelope): AgentLaunchEnvelope { const source = validateLaunchEnvelope(parent); const self = source.catalog[agent]; if (!self) throw new Error(`Agent ${agent} is outside the immutable policy epoch`); return validateLaunchEnvelope({ ...source, agentId, identity: `agent:${agent}`, self }); }
