import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import type { ThinkingLevel } from "./mode_types.ts";

export type AgentHarness = "pi" | "cursor-agent" | "codex";
export interface AgentDefinition { model: string; description: string; thinkingLevel?: ThinkingLevel; tools: string[]; skillOptIns: string[]; instructions: string; harness: AgentHarness; harnessOptions?: Record<string, unknown>; childExtensionContributions: string[] }
export interface AgentCatalog { schemaVersion: 1; agents: Record<string, AgentDefinition> }
export interface DelegationConfig { schemaVersion: 1; stateRoot: string; tmux: string; returnParentCommand: string; parentNavigationHint: string; historyViewerExtension: string; popupExtension: string; orchestrationExtension: string; childBridgeExtension: string; harnesses: Record<string, HarnessRuntimeConfig>; maxDepth: number; natureHandleWords: string[]; delegation: Record<string, string[]> }
export interface HarnessRuntimeConfig { adapter: "pi-native" | "cursor-acp" | "codex-acp"; command: string; workerCommand?: string; workerEntrypoint?: string; bridgeReadyTimeoutMs?: number }
export interface AgentLaunchEnvelope { schemaVersion: 1; marker: "pi-agent-launch-v1"; identity: string; self: AgentDefinition; catalog: Record<string, AgentDefinition>; delegation: Record<string, string[]>; childExtensions: Record<string, string[]> }

export const AGENT_ARTIFACT_EXTENSION = fileURLToPath(new URL("../agent_artifact.ts", import.meta.url));
const cursorHarnessOptions = { mode: "agent", permissionPolicy: "allow-always", sandbox: "disabled", trustWorkspace: true, worktree: false } as const;
const codexHarnessOptions = { mode: "read-only", permissionPolicy: "reject", webSearch: "cached" } as const;
const settledDelegation: Record<string, string[]> = { "mode:recon": ["explorer", "reviewer", "codex"], "mode:ops": ["explorer", "worker", "validator", "reviewer", "fast-worker", "codex"], "agent:reviewer": ["critic"] };
const settledAgents: Record<string, AgentDefinition> = {
    explorer: { model: "openai-codex/gpt-5.6-luna", description: "Read-only bounded repository evidence gathering.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: ["codebase-exploration"], instructions: "Investigate one bounded repository question and return concise evidence with file references.", harness: "pi", childExtensionContributions: [] },
    worker: { model: "openai-codex/gpt-5.6-sol", description: "Bounded source implementation and repair.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash", "write", "edit"], skillOptIns: ["source-implementation"], instructions: "Complete the bounded source objective, inspect the diff, and return changed files, diagnostics, deviations, and risks.", harness: "pi", childExtensionContributions: [] },
    validator: { model: "openai-codex/gpt-5.6-luna", description: "Read-only automated implementation validation.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: ["implementation-validation"], instructions: "Run the caller's requested automated validation objective without changing repository source and return concrete evidence.", harness: "pi", childExtensionContributions: [] },
    reviewer: { model: "openai-codex/gpt-5.6-sol", description: "Read-only adaptive review owner with optional critic delegation.", thinkingLevel: "high", tools: ["read", "grep", "find", "ls", "bash", "subagent_run", "subagent_submit", "subagent_get", "subagent_wait", "subagent_stop", "save_agent_artifact"], skillOptIns: ["adaptive-review", "task-orchestration", "agent-artifact"], instructions: "Review the defined target, delegate only a concrete independent critic lens when useful, and save one review report when requested.", harness: "pi", childExtensionContributions: [AGENT_ARTIFACT_EXTENSION] },
    critic: { model: "openai-codex/gpt-5.6-terra", description: "Read-only focused or dissenting review leaf.", thinkingLevel: "medium", tools: ["read", "grep", "find", "ls", "bash"], skillOptIns: [], instructions: "Review only the caller-supplied lens or dossier and return severity-ordered evidence, gaps, and residual risk.", harness: "pi", childExtensionContributions: [] },
    "fast-worker": { model: "cursor/cursor-grok-4.5-high-fast", description: "Fast bounded source worker through Cursor ACP; usage and interactive parity are limited.", tools: [], skillOptIns: [], instructions: "Implement the bounded source objective in the current workspace, validate proportionately, and return changed files, evidence, deviations, and risks.", harness: "cursor-agent", harnessOptions: cursorHarnessOptions, childExtensionContributions: [] },
    codex: { model: "codex/gpt-5.6-luna", description: "Read-only, source-backed Web research leaf through Codex ACP.", thinkingLevel: "high", tools: [], skillOptIns: [], instructions: "Use Codex's built-in Web search to investigate the delegated question. Return a concise evidence brief containing the conclusion, source URLs with the claim each supports, freshness, and material uncertainty. Read workspace context only when the task requires it. If evidence is insufficient, state what is missing.", harness: "codex", harnessOptions: codexHarnessOptions, childExtensionContributions: [] },
};
export function settledAgentCatalog(): AgentCatalog { return { schemaVersion: 1, agents: structuredClone(settledAgents) }; }
export function settledAgentDefinition(name: string): AgentDefinition { const definition = settledAgents[name]; if (!definition) throw new Error(`Unsupported settled agent: ${name}`); return structuredClone(definition); }

function canonicalJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${canonicalJson(item)}`).join(",")}}`; return JSON.stringify(value); }
function same(left: unknown, right: unknown): boolean { return canonicalJson(left) === canonicalJson(right); }
export function launchEnvelopeDigest(envelope: AgentLaunchEnvelope): string { return createHash("sha256").update(canonicalJson(validateLaunchEnvelope(envelope))).digest("hex"); }
function object(value: unknown, label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, unknown>; }
function exact(value: Record<string, unknown>, keys: readonly string[], label: string) { const unknown = Object.keys(value).filter(key => !keys.includes(key)); if (unknown.length) throw new Error(`${label} contains unknown keys: ${unknown.join(", ")}`); }
function text(value: unknown, label: string) { if (typeof value !== "string" || !value.trim()) throw new Error(`${label} must be a non-empty string`); return value; }
function strings(value: unknown, label: string) { if (!Array.isArray(value) || value.some(item => typeof item !== "string" || !item.trim())) throw new Error(`${label} must be an array of non-empty strings`); const out = [...value] as string[]; if (new Set(out).size !== out.length) throw new Error(`${label} must not contain duplicates`); return out; }
export function validateAgentDefinition(name: string, value: unknown, label = `agent definition ${name}`): AgentDefinition {
    const expected = settledAgents[name]; if (!expected) throw new Error(`${label} uses unsupported agent name ${name}`);
    const raw = object(value, label); exact(raw, ["model", "description", "thinkingLevel", "tools", "skillOptIns", "instructions", "harness", "harnessOptions", "childExtensionContributions"], label);
    text(raw.model, `${label}.model`); text(raw.description, `${label}.description`); strings(raw.tools, `${label}.tools`); strings(raw.skillOptIns, `${label}.skillOptIns`); text(raw.instructions, `${label}.instructions`); strings(raw.childExtensionContributions, `${label}.childExtensionContributions`);
    if (!same(raw, expected)) throw new Error(`${label} must exactly match the settled ${name} capability contract`);
    return structuredClone(expected);
}
export function validateDelegationConfig(value: unknown): DelegationConfig {
    const root = object(value, "orchestration config"); exact(root, ["schemaVersion", "stateRoot", "tmux", "returnParentCommand", "parentNavigationHint", "historyViewerExtension", "popupExtension", "orchestrationExtension", "childBridgeExtension", "harnesses", "maxDepth", "natureHandleWords", "delegation"], "orchestration config");
    if (root.schemaVersion !== 1) throw new Error("Unsupported orchestration config schemaVersion");
    const harnessRaw = object(root.harnesses, "harnesses"); const harnesses: Record<string, HarnessRuntimeConfig> = {};
    for (const [name, value] of Object.entries(harnessRaw)) { const item = object(value, `harnesses.${name}`); exact(item, ["adapter", "command", "workerCommand", "workerEntrypoint", "bridgeReadyTimeoutMs"], `harnesses.${name}`); if (item.adapter !== "pi-native" && item.adapter !== "cursor-acp" && item.adapter !== "codex-acp") throw new Error(`harnesses.${name}.adapter is invalid`); if (item.bridgeReadyTimeoutMs !== undefined && (!Number.isInteger(item.bridgeReadyTimeoutMs) || Number(item.bridgeReadyTimeoutMs) <= 0)) throw new Error(`harnesses.${name}.bridgeReadyTimeoutMs must be a positive integer`); harnesses[name] = { adapter: item.adapter, command: text(item.command, `harnesses.${name}.command`), ...(item.workerCommand === undefined ? {} : { workerCommand: text(item.workerCommand, `harnesses.${name}.workerCommand`) }), ...(item.workerEntrypoint === undefined ? {} : { workerEntrypoint: text(item.workerEntrypoint, `harnesses.${name}.workerEntrypoint`) }), ...(item.bridgeReadyTimeoutMs === undefined ? {} : { bridgeReadyTimeoutMs: item.bridgeReadyTimeoutMs as number }) }; }
    const delegationRaw = object(root.delegation, "delegation"); const delegation = Object.fromEntries(Object.entries(delegationRaw).map(([caller, targets]) => [caller, strings(targets, `delegation.${caller}`)]));
    if (!same(delegation, settledDelegation)) throw new Error("delegation must exactly match the settled caller map");
    if (!Number.isInteger(root.maxDepth) || Number(root.maxDepth) < 0) throw new Error("maxDepth must be non-negative");
    return { schemaVersion: 1, stateRoot: text(root.stateRoot, "stateRoot"), tmux: text(root.tmux, "tmux"), returnParentCommand: text(root.returnParentCommand, "returnParentCommand"), parentNavigationHint: text(root.parentNavigationHint, "parentNavigationHint"), historyViewerExtension: text(root.historyViewerExtension, "historyViewerExtension"), popupExtension: text(root.popupExtension, "popupExtension"), orchestrationExtension: text(root.orchestrationExtension, "orchestrationExtension"), childBridgeExtension: text(root.childBridgeExtension, "childBridgeExtension"), harnesses, maxDepth: root.maxDepth as number, natureHandleWords: strings(root.natureHandleWords, "natureHandleWords"), delegation };
}
export function validateAgentCatalog(value: unknown): AgentCatalog { const root = object(value, "agent catalog"); exact(root, ["schemaVersion", "agents"], "agent catalog"); if (root.schemaVersion !== 1) throw new Error("Unsupported agent catalog schemaVersion"); const raw = object(root.agents, "agents"); if (!same(Object.keys(raw).sort(), Object.keys(settledAgents).sort())) throw new Error("agent catalog must contain exactly the seven settled agents"); const agents = Object.fromEntries(Object.entries(raw).map(([name, definition]) => [name, validateAgentDefinition(name, definition, `agents.${name}`)])); return { schemaVersion: 1, agents }; }
function validateEnvelopeCatalog(value: unknown): Record<string, AgentDefinition> { const raw = object(value, "catalog"); return Object.fromEntries(Object.entries(raw).map(([name, definition]) => [name, validateAgentDefinition(name, definition, `catalog.${name}`)])); }
export function validateLaunchEnvelope(value: unknown): AgentLaunchEnvelope {
    const root = object(value, "agent launch envelope"); exact(root, ["schemaVersion", "marker", "identity", "self", "catalog", "delegation", "childExtensions"], "agent launch envelope"); if (root.schemaVersion !== 1 || root.marker !== "pi-agent-launch-v1") throw new Error("Unsupported agent launch envelope schema or marker");
    const identity = text(root.identity, "identity"); if (!identity.startsWith("agent:")) throw new Error("launch identity must use agent namespace"); const selfName = identity.slice(6); const catalog = validateEnvelopeCatalog(root.catalog); const self = validateAgentDefinition(selfName, root.self, "self");
    const delegationRaw = object(root.delegation, "delegation"); const delegation = Object.fromEntries(Object.entries(delegationRaw).map(([caller, targets]) => [caller, strings(targets, `delegation.${caller}`)])); const extensionRaw = object(root.childExtensions, "childExtensions"); const childExtensions = Object.fromEntries(Object.entries(extensionRaw).map(([name, paths]) => [name, strings(paths, `childExtensions.${name}`)])); const names = Object.keys(catalog).sort();
    if (!catalog[selfName] || !same(catalog[selfName], self)) throw new Error("launch envelope self does not match its catalog definition"); if (!same(Object.keys(childExtensions).sort(), names)) throw new Error("launch envelope childExtensions must exactly cover catalog agents"); if (!same(Object.keys(delegation).sort(), names.map(name => `agent:${name}`).sort())) throw new Error("launch envelope delegation must exactly cover catalog agents");
    for (const name of names) {
        const expectedTargets = name === "reviewer" && catalog.critic ? ["critic"] : [];
        if (!same(delegation[`agent:${name}`], expectedTargets)) throw new Error(`agent:${name} delegation violates the settled leaf restrictions`);
        const manifest = childExtensions[name]!; const contribution = catalog[name]!.childExtensionContributions;
        if (manifest.length < 3) throw new Error(`childExtensions.${name} must contain the popup, orchestration, and bridge extensions`);
        const expectedManifest = [manifest[0]!, manifest[1]!, ...contribution, manifest.at(-1)!];
        if (!same(manifest, expectedManifest)) throw new Error(`childExtensions.${name} must exactly match its settled contribution manifest`);
    }
    const reachable = new Set<string>(); const visit = (name: string) => { if (reachable.has(name)) return; reachable.add(name); for (const target of delegation[`agent:${name}`] ?? []) visit(target); }; visit(selfName); if (!same([...reachable].sort(), names)) throw new Error("launch envelope catalog contains agents outside the immutable delegation closure");
    return { schemaVersion: 1, marker: "pi-agent-launch-v1", identity, self, catalog, delegation, childExtensions };
}
export function buildLaunchEnvelope(agent: string, catalog: AgentCatalog, delegation: Record<string, string[]>, baseExtensions: readonly [string, string, string]): AgentLaunchEnvelope {
    const self = catalog.agents[agent]; if (!self) throw new Error(`Unknown agent: ${agent}`); validateAgentDefinition(agent, self, `agents.${agent}`);
    const seen = new Set<string>(); const visit = (name: string) => { if (seen.has(name)) return; const definition = catalog.agents[name]; if (!definition) throw new Error(`Unknown delegated agent: ${name}`); validateAgentDefinition(name, definition, `agents.${name}`); seen.add(name); for (const child of delegation[`agent:${name}`] ?? []) visit(child); }; visit(agent);
    const subset = Object.fromEntries([...seen].map(name => [name, structuredClone(catalog.agents[name]!) ])); const policy = Object.fromEntries([...seen].map(name => [`agent:${name}`, [...(delegation[`agent:${name}`] ?? [])]])); const childExtensions = Object.fromEntries([...seen].map(name => [name, [baseExtensions[0], baseExtensions[1], ...catalog.agents[name]!.childExtensionContributions, baseExtensions[2]]]));
    return validateLaunchEnvelope({ schemaVersion: 1, marker: "pi-agent-launch-v1", identity: `agent:${agent}`, self: structuredClone(self), catalog: subset, delegation: policy, childExtensions });
}
export function projectLaunchEnvelope(agent: string, parent: AgentLaunchEnvelope): AgentLaunchEnvelope { const source = validateLaunchEnvelope(parent); const self = source.catalog[agent]; if (!self) throw new Error(`Agent ${agent} is outside the immutable parent launch envelope`); const seen = new Set<string>(); const visit = (name: string) => { if (seen.has(name)) return; if (!source.catalog[name]) throw new Error(`Unknown delegated agent in parent envelope: ${name}`); seen.add(name); for (const child of source.delegation[`agent:${name}`] ?? []) visit(child); }; visit(agent); return validateLaunchEnvelope({ schemaVersion: 1, marker: "pi-agent-launch-v1", identity: `agent:${agent}`, self: structuredClone(self), catalog: Object.fromEntries([...seen].map(name => [name, structuredClone(source.catalog[name]!) ])), delegation: Object.fromEntries([...seen].map(name => [`agent:${name}`, [...(source.delegation[`agent:${name}`] ?? [])]])), childExtensions: Object.fromEntries([...seen].map(name => [name, [...source.childExtensions[name]!] ])) }); }
