import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, rename, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { canonicalJson } from "./agent_types.ts";
import { withMeshLock } from "./orchestration_lock.ts";
import { meshPaths, readAgentSnapshot, readTask } from "./orchestration_store.ts";
import { isTerminalTask, type TaskState } from "./orchestration_types.ts";

export type MeshDelivery = "steer" | "followUp";
export type MeshEndpointKind = "root" | "agent";
export interface MeshEndpoint { schemaVersion: 1; meshId: string; endpointId: string; kind: MeshEndpointKind; agentId?: string; harness: "pi"; sessionId: string; sessionFile: string; online: boolean; updatedAt: string }
export interface FrozenTask { taskId: string; state: TaskState; createdAt: string; startedAt?: string; finishedAt?: string; elapsedMs: number }
export interface MeshEvent { schemaVersion: 1; meshId: string; eventId: string; endpointId: string; endpointSessionFile: string; senderEndpointId: string; delivery: MeshDelivery; state: "pending" | "injected" | "acknowledged"; kind: "completion" | "signal"; payload: Record<string, unknown>; createdAt: string; injectedAt?: string; acknowledgedAt?: string }
export interface MeshWatch { schemaVersion: 1; meshId: string; watchId: string; endpointId: string; endpointSessionFile: string; senderEndpointId: string; delivery: MeshDelivery; taskIds: string[]; condition: "any" | "all"; createdAt: string; eventId?: string; eligibleAt?: string }
export interface RouteIdempotency { schemaVersion: 1; meshId: string; endpointId: string; toolCallId: string; argumentsDigest: string; resultKind: "watch" | "event"; resultId: string; createdAt: string }

function endpointKey(endpointId: string): string { return createHash("sha256").update(endpointId).digest("hex"); }
function endpointPath(stateRoot: string, meshId: string, endpointId: string): string { return join(meshPaths(stateRoot, meshId).endpoints, `${endpointKey(endpointId)}.json`); }
function watchPath(stateRoot: string, meshId: string, watchId: string): string { return join(meshPaths(stateRoot, meshId).watches, `${watchId}.json`); }
function eventPath(stateRoot: string, meshId: string, eventId: string): string { return join(meshPaths(stateRoot, meshId).events, `${eventId}.json`); }
function retryPath(stateRoot: string, meshId: string, endpointId: string, toolCallId: string): string { return join(meshPaths(stateRoot, meshId).events, `retry-${createHash("sha256").update(`${endpointId}\0${toolCallId}`).digest("hex")}.json`); }
async function atomic(path: string, value: unknown): Promise<void> { await mkdir(dirname(path), { recursive: true, mode: 0o700 }); const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 }); await rename(temporary, path); }
async function json<T>(path: string): Promise<T> { return JSON.parse(await readFile(path, "utf8")) as T; }
async function optional<T>(path: string): Promise<T | undefined> { return json<T>(path).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); }
function assertUuid(value: string, label: string): void { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value)) throw new Error(`${label} must be a UUID`); }
function exact(value: unknown, required: readonly string[], optionalKeys: readonly string[], label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); const raw = value as Record<string, unknown>; const allowed = [...required, ...optionalKeys]; const unknown = Object.keys(raw).filter(key => !allowed.includes(key)); const missing = required.filter(key => !(key in raw)); if (unknown.length || missing.length) throw new Error(`${label} has invalid keys`); return raw; }
function validateEndpoint(value: unknown, meshId: string, endpointId?: string): MeshEndpoint { const raw = exact(value, ["schemaVersion", "meshId", "endpointId", "kind", "harness", "sessionId", "sessionFile", "online", "updatedAt"], ["agentId"], "mesh endpoint"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || endpointId !== undefined && raw.endpointId !== endpointId || raw.harness !== "pi" || raw.kind !== "root" && raw.kind !== "agent" || typeof raw.sessionId !== "string" || typeof raw.sessionFile !== "string" || !raw.sessionFile || typeof raw.online !== "boolean") throw new Error("mesh endpoint is invalid"); if (raw.kind === "agent") assertUuid(String(raw.agentId), "endpoint agentId"); return value as MeshEndpoint; }
function validateWatch(value: unknown, meshId: string): MeshWatch { const raw = exact(value, ["schemaVersion", "meshId", "watchId", "endpointId", "endpointSessionFile", "senderEndpointId", "delivery", "taskIds", "condition", "createdAt"], ["eventId", "eligibleAt"], "mesh watch"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || raw.delivery !== "steer" && raw.delivery !== "followUp" || raw.condition !== "any" && raw.condition !== "all" || !Array.isArray(raw.taskIds) || raw.taskIds.length < 1 || raw.taskIds.length > 128) throw new Error("mesh watch is invalid"); assertUuid(String(raw.watchId), "watchId"); for (const id of raw.taskIds) assertUuid(String(id), "watch taskId"); if (raw.eventId !== undefined) { if (typeof raw.eventId !== "string") throw new Error("watch eventId is invalid"); assertUuid(raw.eventId, "watch eventId"); } return value as MeshWatch; }
function validateEvent(value: unknown, meshId: string): MeshEvent { const raw = exact(value, ["schemaVersion", "meshId", "eventId", "endpointId", "endpointSessionFile", "senderEndpointId", "delivery", "state", "kind", "payload", "createdAt"], ["injectedAt", "acknowledgedAt"], "mesh event"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || raw.delivery !== "steer" && raw.delivery !== "followUp" || !["pending", "injected", "acknowledged"].includes(String(raw.state)) || raw.kind !== "completion" && raw.kind !== "signal" || !raw.payload || typeof raw.payload !== "object" || Array.isArray(raw.payload)) throw new Error("mesh event is invalid"); assertUuid(String(raw.eventId), "eventId"); return value as MeshEvent; }
function validateRetry(value: unknown, meshId: string): RouteIdempotency { const raw = exact(value, ["schemaVersion", "meshId", "endpointId", "toolCallId", "argumentsDigest", "resultKind", "resultId", "createdAt"], [], "route idempotency"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || raw.resultKind !== "watch" && raw.resultKind !== "event" || typeof raw.argumentsDigest !== "string" || !/^[0-9a-f]{64}$/u.test(raw.argumentsDigest)) throw new Error("route idempotency is invalid"); assertUuid(String(raw.resultId), "route resultId"); return value as RouteIdempotency; }

export async function bindMeshEndpoint(stateRoot: string, meshId: string, input: Omit<MeshEndpoint, "schemaVersion" | "meshId" | "online" | "updatedAt">): Promise<MeshEndpoint> {
    if (!input.sessionFile.trim()) throw new Error("Durable mesh endpoint requires a persisted session file");
    if (input.kind === "agent") { if (!input.agentId) throw new Error("Agent endpoint requires agentId"); assertUuid(input.agentId, "agentId"); }
    const endpoint: MeshEndpoint = { schemaVersion: 1, meshId, ...input, online: true, updatedAt: new Date().toISOString() };
    await withMeshLock(stateRoot, meshId, async () => atomic(endpointPath(stateRoot, meshId, endpoint.endpointId), endpoint)); return endpoint;
}
export async function setMeshEndpointOffline(stateRoot: string, meshId: string, endpointId: string, expected?: Pick<MeshEndpoint, "sessionId" | "sessionFile">): Promise<void> { await withMeshLock(stateRoot, meshId, async () => { const path = endpointPath(stateRoot, meshId, endpointId); const raw = await optional<unknown>(path); const endpoint = raw === undefined ? undefined : validateEndpoint(raw, meshId, endpointId); if (!endpoint || expected && (endpoint.sessionId !== expected.sessionId || endpoint.sessionFile !== expected.sessionFile)) return; await atomic(path, { ...endpoint, online: false, updatedAt: new Date().toISOString() }); }); }
export async function readMeshEndpoint(stateRoot: string, meshId: string, endpointId: string): Promise<MeshEndpoint> { return validateEndpoint(await json<unknown>(endpointPath(stateRoot, meshId, endpointId)), meshId, endpointId); }
export async function isLiveMeshEndpointBinding(stateRoot: string, meshId: string, binding: MeshEndpoint): Promise<boolean> {
    const current = await readMeshEndpoint(stateRoot, meshId, binding.endpointId).catch(() => undefined);
    return Boolean(current?.online && current.kind === binding.kind && current.agentId === binding.agentId && current.sessionId === binding.sessionId && current.sessionFile === binding.sessionFile);
}

export async function resolveRouteEndpoint(stateRoot: string, meshId: string, receiver: string, callerAgentId?: string): Promise<MeshEndpoint> {
    let endpointId: string;
    if (receiver === "self") endpointId = callerAgentId ? `agent:${callerAgentId}` : `root:${meshId}`;
    else if (receiver === "root") endpointId = `root:${meshId}`;
    else if (receiver === "parent") {
        if (!callerAgentId) throw new Error("Root endpoint has no parent");
        const caller = await readAgentSnapshot(stateRoot, meshId, callerAgentId);
        endpointId = caller.agent.parentAgentId ? `agent:${caller.agent.parentAgentId}` : `root:${meshId}`;
    } else { assertUuid(receiver, "receiver"); endpointId = `agent:${receiver}`; }
    try { return await readMeshEndpoint(stateRoot, meshId, endpointId); }
    catch { throw new Error(`Receiver ${receiver} is not a durable Pi endpoint in this mesh`); }
}

async function frozenTasks(stateRoot: string, meshId: string, taskIds: readonly string[]): Promise<FrozenTask[]> { return Promise.all(taskIds.map(async taskId => { const task = await readTask(stateRoot, meshId, taskId); const end = task.status.finishedAt ? Date.parse(task.status.finishedAt) : Date.now(); const start = Date.parse(task.status.startedAt ?? task.status.createdAt); return { taskId, state: task.status.state, createdAt: task.status.createdAt, ...(task.status.startedAt ? { startedAt: task.status.startedAt } : {}), ...(task.status.finishedAt ? { finishedAt: task.status.finishedAt } : {}), elapsedMs: Math.max(0, end - start) }; })); }
async function createEvent(stateRoot: string, meshId: string, input: Omit<MeshEvent, "schemaVersion" | "meshId" | "eventId" | "state" | "createdAt">): Promise<MeshEvent> { const eventId = randomUUID(); const event: MeshEvent = { schemaVersion: 1, meshId, eventId, state: "pending", createdAt: new Date().toISOString(), ...input, payload: { eventId, ...input.payload } }; await atomic(eventPath(stateRoot, meshId, event.eventId), event); return event; }
async function evaluateWatch(stateRoot: string, meshId: string, watch: MeshWatch): Promise<MeshEvent | undefined> { if (watch.eventId) return optional<MeshEvent>(eventPath(stateRoot, meshId, watch.eventId)); const tasks = await frozenTasks(stateRoot, meshId, watch.taskIds); const terminal = tasks.filter(task => isTerminalTask(task.state)); if (watch.condition === "any" ? terminal.length === 0 : terminal.length !== tasks.length) return undefined; const eligibleAt = new Date().toISOString(); const event = await createEvent(stateRoot, meshId, { endpointId: watch.endpointId, endpointSessionFile: watch.endpointSessionFile, senderEndpointId: watch.senderEndpointId, delivery: watch.delivery, kind: "completion", payload: { condition: watch.condition, registeredAt: watch.createdAt, eligibleAt, tasks } }); await atomic(watchPath(stateRoot, meshId, watch.watchId), { ...watch, eventId: event.eventId, eligibleAt }); return event; }

async function idempotent<T extends { watchId?: string; eventId?: string }>(stateRoot: string, meshId: string, endpointId: string, toolCallId: string, args: unknown, create: () => Promise<T>): Promise<T> {
    return withMeshLock(stateRoot, meshId, async () => {
        const path = retryPath(stateRoot, meshId, endpointId, toolCallId); const digest = createHash("sha256").update(canonicalJson(args)).digest("hex"); const rawExisting = await optional<unknown>(path); const existing = rawExisting === undefined ? undefined : validateRetry(rawExisting, meshId);
        if (existing) { if (existing.argumentsDigest !== digest) throw new Error("mesh_route retry reused toolCallId with different arguments"); if (existing.resultKind === "watch") { const watch = validateWatch(await json<unknown>(watchPath(stateRoot, meshId, existing.resultId)), meshId); return { watchId: watch.watchId, ...(watch.eventId ? { eventId: watch.eventId } : {}) } as T; } return { eventId: existing.resultId } as T; }
        const result = await create(); const resultKind = result.watchId ? "watch" : "event"; const resultId = result.watchId ?? result.eventId!; await atomic(path, { schemaVersion: 1, meshId, endpointId, toolCallId, argumentsDigest: digest, resultKind, resultId, createdAt: new Date().toISOString() } satisfies RouteIdempotency); return result;
    });
}
export async function registerMeshWatch(stateRoot: string, meshId: string, input: { callerEndpointId: string; toolCallId: string; endpoint: MeshEndpoint; delivery: MeshDelivery; taskIds: string[]; condition: "any" | "all"; canonicalArguments: unknown }): Promise<{ watchId: string; eventId?: string }> { return idempotent(stateRoot, meshId, input.callerEndpointId, input.toolCallId, input.canonicalArguments, async () => { await Promise.all(input.taskIds.map(id => readTask(stateRoot, meshId, id))); const watch: MeshWatch = { schemaVersion: 1, meshId, watchId: randomUUID(), endpointId: input.endpoint.endpointId, endpointSessionFile: input.endpoint.sessionFile, senderEndpointId: input.callerEndpointId, delivery: input.delivery, taskIds: [...input.taskIds], condition: input.condition, createdAt: new Date().toISOString() }; await atomic(watchPath(stateRoot, meshId, watch.watchId), watch); const event = await evaluateWatch(stateRoot, meshId, watch); return { watchId: watch.watchId, ...(event ? { eventId: event.eventId } : {}) }; }); }
export async function registerMeshSignal(stateRoot: string, meshId: string, input: { callerEndpointId: string; toolCallId: string; endpoint: MeshEndpoint; delivery: MeshDelivery; topic: string; text: string; taskIds?: string[]; canonicalArguments: unknown }): Promise<{ eventId: string }> { return idempotent(stateRoot, meshId, input.callerEndpointId, input.toolCallId, input.canonicalArguments, async () => { if (input.taskIds) await Promise.all(input.taskIds.map(id => readTask(stateRoot, meshId, id))); const event = await createEvent(stateRoot, meshId, { endpointId: input.endpoint.endpointId, endpointSessionFile: input.endpoint.sessionFile, senderEndpointId: input.callerEndpointId, delivery: input.delivery, kind: "signal", payload: { topic: input.topic, text: input.text, ...(input.taskIds ? { taskIds: input.taskIds } : {}) } }); return { eventId: event.eventId }; }); }

async function records(directory: string, prefix = ""): Promise<unknown[]> { const names = await readdir(directory).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? [] : Promise.reject(error)); return Promise.all(names.filter(name => name.endsWith(".json") && (prefix === "" || !name.startsWith(prefix))).map(name => json<unknown>(join(directory, name)))); }
export async function pollMeshEvents(stateRoot: string, meshId: string, endpoint: MeshEndpoint): Promise<MeshEvent[]> { validateEndpoint(endpoint, meshId, endpoint.endpointId); return withMeshLock(stateRoot, meshId, async () => { const durableRaw = await optional<unknown>(endpointPath(stateRoot, meshId, endpoint.endpointId)); const durable = durableRaw === undefined ? undefined : validateEndpoint(durableRaw, meshId, endpoint.endpointId); if (!durable || !durable.online || durable.sessionId !== endpoint.sessionId || durable.sessionFile !== endpoint.sessionFile) return []; const watches = (await records(meshPaths(stateRoot, meshId).watches)).map(value => validateWatch(value, meshId)); for (const watch of watches) if (!watch.eventId) await evaluateWatch(stateRoot, meshId, watch); const events = (await records(meshPaths(stateRoot, meshId).events, "retry-")).map(value => validateEvent(value, meshId)); return events.filter(event => event.endpointId === durable.endpointId && event.endpointSessionFile === durable.sessionFile && event.state !== "acknowledged"); }); }
export async function markMeshEventInjected(stateRoot: string, meshId: string, eventId: string): Promise<void> { await withMeshLock(stateRoot, meshId, async () => { const path = eventPath(stateRoot, meshId, eventId); const event = validateEvent(await json<unknown>(path), meshId); if (event.state !== "pending") return; await atomic(path, { ...event, state: "injected", injectedAt: new Date().toISOString() }); }); }
export async function acknowledgeMeshEvents(stateRoot: string, meshId: string, eventIds: readonly string[]): Promise<void> { await withMeshLock(stateRoot, meshId, async () => { for (const eventId of new Set(eventIds)) { const path = eventPath(stateRoot, meshId, eventId); const raw = await optional<unknown>(path); const event = raw === undefined ? undefined : validateEvent(raw, meshId); if (event && event.state !== "acknowledged") await atomic(path, { ...event, state: "acknowledged", acknowledgedAt: new Date().toISOString() }); } }); }
