import { createHash, randomUUID } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { canonicalJson } from "./agent_types.ts";
import { bindCompletionTargetUnlocked, settleCompletionDeliveriesUnlocked } from "./orchestration_completion.ts";
import { indexEventCreation, readEndpointEventReferences, readEndpointTaskReferences, removeOrchestrationIndexReference, type OrchestrationIndexReadObserver } from "./orchestration_index.ts";
import { readOptionalJson as optional, writeAtomicJson } from "./orchestration_json.ts";
import { withMeshAgentLock, withMeshLock } from "./orchestration_lock.ts";
import { assertDispatchMutationAuthority, assertRootLeaseOwner, createTaskUnlocked, meshPaths, readAgentSnapshot, readMesh, readTask, releasePendingMeshReservationUnlocked, reserveExistingAgentTaskCapacityUnlocked, type DispatchMutationAuthority } from "./orchestration_store.ts";
import { assertExpectedEndpointBindingUnlocked, endpointRecordPath as endpointPath } from "./orchestration_binding.ts";
import { isTerminalTask, type TaskState } from "./orchestration_types.ts";

export type MeshDelivery = "steer" | "followUp";
export type MeshEndpointKind = "root" | "agent";
export interface MeshEndpoint { schemaVersion: 2; meshId: string; endpointId: string; bindingId: string; kind: MeshEndpointKind; agentId?: string; harness: "pi"; sessionId: string; sessionFile: string; online: boolean; updatedAt: string }
export interface FrozenTask { taskId: string; agentId: string; state: TaskState }
export type MeshEventKind = "completion" | "signal" | "intervention" | "report" | "delivery-ack";
export interface MeshEvent { schemaVersion: 1; meshId: string; eventId: string; endpointId: string; endpointSessionFile: string; endpointBindingId: string; senderEndpointId: string; /** Absent only on legacy completion/signal events. */ senderEndpointSessionFile?: string; delivery: MeshDelivery; state: "pending" | "injected" | "acknowledged"; kind: MeshEventKind; payload: Record<string, unknown>; createdAt: string; injectedAt?: string; acknowledgedAt?: string; /** Links acknowledged interventions to their idempotent delivery-ack event. */ ackEventId?: string }
export type MeshSendResult = { disposition: "submitted"; agentId: string; taskId: string } | { disposition: "intervened"; agentId: string; taskId: string; messageId: string; sequence: number; deliveryState: "pending" };
export interface MeshSendIdempotency { schemaVersion: 1; meshId: string; callerEndpointId: string; callerEndpointSessionFile: string; toolCallId: string; argumentsDigest: string; result: MeshSendResult; createdAt: string }
export interface ContextAcknowledgment { eventId: string; agentId: string; taskId: string; acknowledgedThrough: number; messageIds: string[] }
export interface RouteIdempotency { schemaVersion: 1; meshId: string; endpointId: string; toolCallId: string; argumentsDigest: string; resultKind: "event"; resultId: string; createdAt: string }
export interface EndpointDeliverySnapshot { endpoint: MeshEndpoint; events: MeshEvent[]; observedAt: string; pendingTasks: FrozenTask[] }

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
function eventPath(stateRoot: string, meshId: string, eventId: string): string { return join(meshPaths(stateRoot, meshId).events, `${eventId}.json`); }
function retryPath(stateRoot: string, meshId: string, endpointId: string, toolCallId: string): string { return join(meshPaths(stateRoot, meshId).events, `retry-${createHash("sha256").update(`${endpointId}\0${toolCallId}`).digest("hex")}.json`); }
function sendRetryPath(stateRoot: string, meshId: string, endpointId: string, toolCallId: string): string { return join(meshPaths(stateRoot, meshId).events, `send-retry-${createHash("sha256").update(`${endpointId}\0${toolCallId}`).digest("hex")}.json`); }
async function json<T>(path: string): Promise<T> { return JSON.parse(await readFile(path, "utf8")) as T; }
function assertUuid(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || !UUID.test(value)) throw new Error(`${label} must be a UUID`); }
function timestamp(value: unknown, label: string): asserts value is string { if (typeof value !== "string" || !Number.isFinite(Date.parse(value))) throw new Error(`${label} must be an ISO timestamp`); }
function exact(value: unknown, required: readonly string[], optionalKeys: readonly string[], label: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); const raw = value as Record<string, unknown>; const allowed = [...required, ...optionalKeys]; if (Object.keys(raw).some(key => !allowed.includes(key)) || required.some(key => !(key in raw))) throw new Error(`${label} has invalid keys`); return raw; }
function validateEndpoint(value: unknown, meshId: string, endpointId?: string): MeshEndpoint { const raw = exact(value, ["schemaVersion", "meshId", "endpointId", "bindingId", "kind", "harness", "sessionId", "sessionFile", "online", "updatedAt"], ["agentId"], "mesh endpoint"); if (raw.schemaVersion !== 2 || raw.meshId !== meshId || endpointId !== undefined && raw.endpointId !== endpointId || raw.harness !== "pi" || raw.kind !== "root" && raw.kind !== "agent" || typeof raw.endpointId !== "string" || typeof raw.sessionId !== "string" || !raw.sessionId || typeof raw.sessionFile !== "string" || !raw.sessionFile || typeof raw.online !== "boolean") throw new Error("mesh endpoint is invalid"); assertUuid(raw.bindingId, "endpoint bindingId"); timestamp(raw.updatedAt, "endpoint updatedAt"); if (raw.kind === "agent") assertUuid(raw.agentId, "endpoint agentId"); else if (raw.agentId !== undefined) throw new Error("root endpoint must not contain agentId"); return value as MeshEndpoint; }
function validateCompletionPayload(value: unknown, eventId: string): void { const raw = exact(value, ["eventId", "batchId", "settledAt", "tasks"], [], "completion event payload"); if (raw.eventId !== eventId) throw new Error("completion event identity is invalid"); assertUuid(raw.batchId, "completion batchId"); timestamp(raw.settledAt, "completion settledAt"); if (!Array.isArray(raw.tasks) || !raw.tasks.length) throw new Error("completion event tasks are invalid"); const ids = new Set<string>(); for (const task of raw.tasks) { const item = exact(task, ["taskId", "agentId", "state"], [], "completion event task"); assertUuid(item.taskId, "completion taskId"); assertUuid(item.agentId, "completion agentId"); if (item.state !== "succeeded" && item.state !== "failed" && item.state !== "stopped" || ids.has(item.taskId)) throw new Error("completion event task is invalid"); ids.add(item.taskId); } }
function validateProtocolPayload(kind: MeshEventKind, value: unknown, eventId: string): void {
    if (kind === "completion") return validateCompletionPayload(value, eventId);
    if (kind === "signal") return;
    const raw = value as Record<string, unknown>;
    if (kind === "intervention") { const payload = exact(raw, ["eventId", "messageId", "agentId", "taskId", "sequence", "message"], [], "intervention event payload"); if (payload.eventId !== eventId || payload.messageId !== eventId) throw new Error("intervention event identity is invalid"); assertUuid(payload.agentId, "intervention agentId"); assertUuid(payload.taskId, "intervention taskId"); if (!Number.isInteger(payload.sequence) || Number(payload.sequence) < 1 || typeof payload.message !== "string" || !payload.message.trim()) throw new Error("intervention event payload is invalid"); return; }
    if (kind === "report") { const payload = exact(raw, ["eventId", "reportId", "agentId", "taskId", "summary"], [], "report event payload"); if (payload.eventId !== eventId || payload.reportId !== eventId) throw new Error("report event identity is invalid"); assertUuid(payload.agentId, "report agentId"); assertUuid(payload.taskId, "report taskId"); if (typeof payload.summary !== "string" || !payload.summary.trim()) throw new Error("report event payload is invalid"); return; }
    const payload = exact(raw, ["eventId", "ackId", "agentId", "taskId", "acknowledgedThrough", "messageIds"], [], "delivery acknowledgment payload"); if (payload.eventId !== eventId || payload.ackId !== eventId) throw new Error("delivery acknowledgment identity is invalid"); assertUuid(payload.agentId, "delivery acknowledgment agentId"); assertUuid(payload.taskId, "delivery acknowledgment taskId"); if (!Number.isInteger(payload.acknowledgedThrough) || Number(payload.acknowledgedThrough) < 1 || !Array.isArray(payload.messageIds) || !payload.messageIds.length) throw new Error("delivery acknowledgment payload is invalid"); for (const messageId of payload.messageIds) assertUuid(messageId, "delivery acknowledgment messageId");
}
function validateEvent(value: unknown, meshId: string): MeshEvent { const raw = exact(value, ["schemaVersion", "meshId", "eventId", "endpointId", "endpointSessionFile", "endpointBindingId", "senderEndpointId", "delivery", "state", "kind", "payload", "createdAt"], ["senderEndpointSessionFile", "injectedAt", "acknowledgedAt", "ackEventId"], "mesh event"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || raw.delivery !== "steer" && raw.delivery !== "followUp" || !["pending", "injected", "acknowledged"].includes(String(raw.state)) || !["completion", "signal", "intervention", "report", "delivery-ack"].includes(String(raw.kind)) || !raw.payload || typeof raw.payload !== "object" || Array.isArray(raw.payload) || typeof raw.endpointId !== "string" || typeof raw.endpointSessionFile !== "string" || typeof raw.senderEndpointId !== "string") throw new Error("mesh event is invalid"); assertUuid(raw.eventId, "eventId"); assertUuid(raw.endpointBindingId, "event endpointBindingId"); if (raw.senderEndpointSessionFile !== undefined && (typeof raw.senderEndpointSessionFile !== "string" || !raw.senderEndpointSessionFile.trim())) throw new Error("mesh event sender session is invalid"); if (raw.ackEventId !== undefined) assertUuid(raw.ackEventId, "mesh event ackEventId"); if ((raw.kind === "intervention" || raw.kind === "report" || raw.kind === "delivery-ack") && raw.senderEndpointSessionFile === undefined) throw new Error("new mesh event requires sender session identity"); timestamp(raw.createdAt, "event createdAt"); if (raw.injectedAt !== undefined) timestamp(raw.injectedAt, "event injectedAt"); if (raw.acknowledgedAt !== undefined) timestamp(raw.acknowledgedAt, "event acknowledgedAt"); validateProtocolPayload(raw.kind as MeshEventKind, raw.payload, raw.eventId as string); return value as MeshEvent; }
function validateRetry(value: unknown, meshId: string): RouteIdempotency { const raw = exact(value, ["schemaVersion", "meshId", "endpointId", "toolCallId", "argumentsDigest", "resultKind", "resultId", "createdAt"], [], "signal idempotency"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || raw.resultKind !== "event" || typeof raw.argumentsDigest !== "string" || !/^[0-9a-f]{64}$/u.test(raw.argumentsDigest)) throw new Error("signal idempotency is invalid"); assertUuid(raw.resultId, "signal resultId"); return value as RouteIdempotency; }
function validateSendIdempotency(value: unknown, meshId: string): MeshSendIdempotency { const raw = exact(value, ["schemaVersion", "meshId", "callerEndpointId", "callerEndpointSessionFile", "toolCallId", "argumentsDigest", "result", "createdAt"], [], "mesh send idempotency"); if (raw.schemaVersion !== 1 || raw.meshId !== meshId || typeof raw.callerEndpointId !== "string" || typeof raw.callerEndpointSessionFile !== "string" || !raw.callerEndpointSessionFile || typeof raw.toolCallId !== "string" || !raw.toolCallId || typeof raw.argumentsDigest !== "string" || !/^[0-9a-f]{64}$/u.test(raw.argumentsDigest) || !raw.result || typeof raw.result !== "object" || Array.isArray(raw.result)) throw new Error("mesh send idempotency is invalid"); const result = raw.result as Record<string, unknown>; if (result.disposition !== "submitted" && result.disposition !== "intervened" || typeof result.agentId !== "string" || typeof result.taskId !== "string") throw new Error("mesh send disposition is invalid"); assertUuid(result.agentId, "mesh send agentId"); assertUuid(result.taskId, "mesh send taskId"); if (result.disposition === "submitted") { if (Object.keys(result).some(key => !["disposition", "agentId", "taskId"].includes(key))) throw new Error("submitted mesh send result is invalid"); } else { if (Object.keys(result).some(key => !["disposition", "agentId", "taskId", "messageId", "sequence", "deliveryState"].includes(key)) || typeof result.messageId !== "string" || !Number.isInteger(result.sequence) || Number(result.sequence) < 1 || result.deliveryState !== "pending") throw new Error("intervened mesh send result is invalid"); assertUuid(result.messageId, "mesh send messageId"); } timestamp(raw.createdAt, "mesh send idempotency createdAt"); return value as MeshSendIdempotency; }

export async function bindMeshEndpoint(stateRoot: string, meshId: string, input: Omit<MeshEndpoint, "schemaVersion" | "meshId" | "bindingId" | "online" | "updatedAt">): Promise<MeshEndpoint> { if (!input.sessionFile.trim()) throw new Error("Durable mesh endpoint requires a persisted session file"); if (input.kind === "agent") { if (!input.agentId) throw new Error("Agent endpoint requires agentId"); assertUuid(input.agentId, "agentId"); } const endpoint: MeshEndpoint = { schemaVersion: 2, meshId, bindingId: randomUUID(), ...input, online: true, updatedAt: new Date().toISOString() }; await withMeshLock(stateRoot, meshId, async () => writeAtomicJson(endpointPath(stateRoot, meshId, endpoint.endpointId), endpoint)); return endpoint; }
export async function setMeshEndpointOffline(stateRoot: string, meshId: string, endpointId: string, expected?: Pick<MeshEndpoint, "bindingId" | "sessionId" | "sessionFile">): Promise<void> { await withMeshLock(stateRoot, meshId, async () => { const path = endpointPath(stateRoot, meshId, endpointId); const raw = await optional<unknown>(path); const endpoint = raw === undefined ? undefined : validateEndpoint(raw, meshId, endpointId); if (!endpoint || expected && (endpoint.bindingId !== expected.bindingId || endpoint.sessionId !== expected.sessionId || endpoint.sessionFile !== expected.sessionFile)) return; await writeAtomicJson(path, { ...endpoint, online: false, updatedAt: new Date().toISOString() }); }); }
export async function readMeshEndpoint(stateRoot: string, meshId: string, endpointId: string): Promise<MeshEndpoint> { return validateEndpoint(await json<unknown>(endpointPath(stateRoot, meshId, endpointId)), meshId, endpointId); }
function sameBinding(current: MeshEndpoint | undefined, binding: MeshEndpoint): boolean { return Boolean(current?.online && current.bindingId === binding.bindingId && current.kind === binding.kind && current.agentId === binding.agentId && current.sessionId === binding.sessionId && current.sessionFile === binding.sessionFile); }
export async function isLiveMeshEndpointBinding(stateRoot: string, meshId: string, binding: MeshEndpoint): Promise<boolean> { const current = await readMeshEndpoint(stateRoot, meshId, binding.endpointId).catch(() => undefined); return sameBinding(current, binding); }

export async function resolveRouteEndpoint(stateRoot: string, meshId: string, receiver: string, callerAgentId?: string): Promise<MeshEndpoint> { let endpointId: string; if (receiver === "self") endpointId = callerAgentId ? `agent:${callerAgentId}` : `root:${meshId}`; else if (receiver === "root") endpointId = `root:${meshId}`; else if (receiver === "parent") { if (!callerAgentId) throw new Error("Root endpoint has no parent"); const caller = await readAgentSnapshot(stateRoot, meshId, callerAgentId); endpointId = caller.agent.parentAgentId ? `agent:${caller.agent.parentAgentId}` : `root:${meshId}`; } else { assertUuid(receiver, "receiver"); endpointId = `agent:${receiver}`; } try { return await readMeshEndpoint(stateRoot, meshId, endpointId); } catch { throw new Error(`Receiver ${receiver} is not a durable Pi endpoint in this mesh`); } }

async function createEvent(stateRoot: string, meshId: string, input: Omit<MeshEvent, "schemaVersion" | "meshId" | "eventId" | "state" | "createdAt" | "endpointBindingId"> & { endpointBindingId?: string }, assignedEventId?: string, afterIndexPersisted?: () => void | Promise<void>): Promise<MeshEvent> { const eventId = assignedEventId ?? randomUUID(); const existing = await optional<unknown>(eventPath(stateRoot, meshId, eventId)); if (existing !== undefined) { const event = validateEvent(existing, meshId); if (event.state !== "acknowledged") await indexEventCreation(stateRoot, meshId, { endpointId: event.endpointId, endpointSessionFile: event.endpointSessionFile, bindingId: event.endpointBindingId, eventId, createdAt: event.createdAt }, true); return event; } const createdAt = new Date().toISOString(); const target = await bindCompletionTargetUnlocked(stateRoot, meshId, { endpointId: input.endpointId, endpointSessionFile: input.endpointSessionFile, ...(input.endpointBindingId ? { bindingId: input.endpointBindingId } : {}) }); const event: MeshEvent = { schemaVersion: 1, meshId, eventId, state: "pending", createdAt, ...input, endpointBindingId: target.bindingId!, payload: { eventId, ...input.payload } }; validateEvent(event, meshId); await indexEventCreation(stateRoot, meshId, { endpointId: event.endpointId, endpointSessionFile: event.endpointSessionFile, bindingId: event.endpointBindingId, eventId, createdAt }); await afterIndexPersisted?.(); await writeAtomicJson(eventPath(stateRoot, meshId, event.eventId), event); await indexEventCreation(stateRoot, meshId, { endpointId: event.endpointId, endpointSessionFile: event.endpointSessionFile, bindingId: event.endpointBindingId, eventId, createdAt }, true); return event; }
export interface CompletionMaterializationOptions { afterLedgerPersisted?: () => void | Promise<void>; indexReadObserver?: OrchestrationIndexReadObserver }
async function evaluateCompletionTargets(stateRoot: string, meshId: string, leaseId: string, options: CompletionMaterializationOptions): Promise<void> { await assertRootLeaseOwner(stateRoot, meshId, leaseId); const mesh = await readMesh(stateRoot, meshId); const settlement = await settleCompletionDeliveriesUnlocked(stateRoot, meshId, mesh.budgets.maxTasksPerMesh, options.indexReadObserver); if (settlement.ledgersPersisted) await options.afterLedgerPersisted?.(); for (const item of settlement.eventBatches) { const eventId = item.batch.eventId; if (await optional(eventPath(stateRoot, meshId, eventId)) === undefined) await createEvent(stateRoot, meshId, { endpointId: item.ledger.endpointId, endpointSessionFile: item.ledger.endpointSessionFile, endpointBindingId: item.ledger.bindingId, senderEndpointId: item.ledger.endpointId, delivery: "steer", kind: "completion", payload: { batchId: item.batch.batchId, settledAt: item.batch.settledAt, tasks: item.tasks.map(task => ({ taskId: task.taskId, agentId: task.agentId, state: task.state })) } }, eventId); for (const task of item.tasks) await removeOrchestrationIndexReference(stateRoot, meshId, "completion-queue", { taskId: task.taskId }); } }

async function idempotent<T extends { eventId: string }>(stateRoot: string, meshId: string, endpointId: string, toolCallId: string, operation: string, args: unknown, create: (eventId: string) => Promise<T>): Promise<T> { return withMeshLock(stateRoot, meshId, async () => { const path = retryPath(stateRoot, meshId, endpointId, toolCallId); const digest = createHash("sha256").update(canonicalJson(args)).digest("hex"); const rawExisting = await optional<unknown>(path); const existing = rawExisting === undefined ? undefined : validateRetry(rawExisting, meshId); if (existing) { if (existing.argumentsDigest !== digest) throw new Error(`${operation} retry reused toolCallId with different arguments`); return create(existing.resultId); } const eventId = randomUUID(); await writeAtomicJson(path, { schemaVersion: 1, meshId, endpointId, toolCallId, argumentsDigest: digest, resultKind: "event", resultId: eventId, createdAt: new Date().toISOString() } satisfies RouteIdempotency); return create(eventId); }); }
export async function registerMeshSignal(stateRoot: string, meshId: string, input: { callerEndpointId: string; toolCallId: string; endpoint: MeshEndpoint; delivery: MeshDelivery; topic: string; text: string; taskIds?: string[]; canonicalArguments: unknown; afterEventIndexPersisted?: () => void | Promise<void> }): Promise<{ eventId: string }> { return idempotent(stateRoot, meshId, input.callerEndpointId, input.toolCallId, "mesh_signal", input.canonicalArguments, async eventId => { if (input.taskIds) await Promise.all(input.taskIds.map(id => readTask(stateRoot, meshId, id))); const event = await createEvent(stateRoot, meshId, { endpointId: input.endpoint.endpointId, endpointSessionFile: input.endpoint.sessionFile, endpointBindingId: input.endpoint.bindingId, senderEndpointId: input.callerEndpointId, delivery: input.delivery, kind: "signal", payload: { topic: input.topic, text: input.text, ...(input.taskIds ? { taskIds: input.taskIds } : {}) } }, eventId, input.afterEventIndexPersisted); return { eventId: event.eventId }; }); }

async function ensureEvent(stateRoot: string, meshId: string, eventId: string, input: Omit<MeshEvent, "schemaVersion" | "meshId" | "eventId" | "state" | "createdAt" | "endpointBindingId"> & { endpointBindingId?: string }): Promise<MeshEvent> { return createEvent(stateRoot, meshId, input, eventId); }
function interventionSequence(events: readonly MeshEvent[], callerEndpointId: string, callerEndpointSessionFile: string, agentId: string, taskId: string): number { return events.filter(event => event.kind === "intervention" && event.senderEndpointId === callerEndpointId && event.senderEndpointSessionFile === callerEndpointSessionFile && event.payload.agentId === agentId && event.payload.taskId === taskId).reduce((maximum, event) => Math.max(maximum, Number(event.payload.sequence)), 0) + 1; }

/** State selection, idempotency persistence, and its resulting mutation share one mesh→agent lock transaction. */
export async function registerStateAwareMeshSend(stateRoot: string, meshId: string, input: { callerEndpointId: string; callerEndpointSessionFile: string; toolCallId: string; canonicalArguments: unknown; endpoint?: MeshEndpoint; agentId: string; message: string; completion: import("./orchestration_types.ts").CompletionTarget; authority?: DispatchMutationAuthority }): Promise<MeshSendResult> {
    if (!input.message.trim()) throw new Error("Mesh send message must not be empty");
    return withMeshAgentLock(stateRoot, meshId, input.agentId, async () => {
        await assertExpectedEndpointBindingUnlocked(stateRoot, meshId, { endpointId: input.callerEndpointId, endpointSessionFile: input.callerEndpointSessionFile });
        const targetSnapshot = await readAgentSnapshot(stateRoot, meshId, input.agentId);
        const requesterAgentId = input.authority?.requesterAgentId ?? (input.callerEndpointId.startsWith("agent:") ? input.callerEndpointId.slice("agent:".length) : undefined);
        if (requesterAgentId && targetSnapshot.agent.parentAgentId !== requesterAgentId) throw new Error(`Agent ${input.agentId} is not a direct child of requester ${requesterAgentId}`);
        if (input.authority) {
            if (input.authority.targetRole !== targetSnapshot.agent.role || input.authority.selectedProfile !== targetSnapshot.agent.selectedProfile) throw new Error("Dispatch authority does not match target agent");
            await assertDispatchMutationAuthority(stateRoot, meshId, input.authority);
        }
        const path = sendRetryPath(stateRoot, meshId, input.callerEndpointId, input.toolCallId); const digest = createHash("sha256").update(canonicalJson(input.canonicalArguments)).digest("hex");
        const existingRaw = await optional<unknown>(path); const existing = existingRaw === undefined ? undefined : validateSendIdempotency(existingRaw, meshId);
        if (existing && (existing.callerEndpointSessionFile !== input.callerEndpointSessionFile || existing.argumentsDigest !== digest || existing.result.agentId !== input.agentId)) throw new Error("mesh_send retry reused toolCallId with different arguments");
        let result: MeshSendResult;
        if (existing) result = existing.result;
        else {
            const status = targetSnapshot.status;
            if (status.state === "busy") { if (!status.activeTaskId) throw new Error(`Agent ${input.agentId} is busy without an active task`); const task = await readTask(stateRoot, meshId, status.activeTaskId); if (isTerminalTask(task.status.state)) throw new Error(`Agent ${input.agentId} is busy with a terminal active task`); if (!targetSnapshot.agent.capabilities.interactiveInterventions) throw new Error(`Agent ${input.agentId} does not support active-task intervention`); if (!input.endpoint || input.endpoint.kind !== "agent" || input.endpoint.agentId !== input.agentId || !input.endpoint.online) throw new Error("Mesh send target is not an online agent endpoint"); const targetRaw = await optional<unknown>(endpointPath(stateRoot, meshId, input.endpoint.endpointId)); const target = targetRaw === undefined ? undefined : validateEndpoint(targetRaw, meshId, input.endpoint.endpointId); if (!sameBinding(target, input.endpoint)) throw new Error("Mesh send target endpoint binding is stale or offline"); result = { disposition: "intervened", agentId: input.agentId, taskId: task.request.taskId, messageId: randomUUID(), sequence: interventionSequence((await records(meshPaths(stateRoot, meshId).events)).map(value => validateEvent(value, meshId)), input.callerEndpointId, input.callerEndpointSessionFile, input.agentId, task.request.taskId), deliveryState: "pending" }; }
            else if (status.state === "idle") { if (!targetSnapshot.activity.acceptingTask) throw new Error(`Agent ${input.agentId} is not accepting tasks`); result = { disposition: "submitted", agentId: input.agentId, taskId: randomUUID() }; }
            else throw new Error(`Agent ${input.agentId} cannot accept mesh_send while ${status.state}`);
            await writeAtomicJson(path, { schemaVersion: 1, meshId, callerEndpointId: input.callerEndpointId, callerEndpointSessionFile: input.callerEndpointSessionFile, toolCallId: input.toolCallId, argumentsDigest: digest, result, createdAt: new Date().toISOString() } satisfies MeshSendIdempotency);
        }
        if (result.disposition === "intervened") { if (!input.endpoint) throw new Error("Mesh send intervention retry requires the target endpoint"); await ensureEvent(stateRoot, meshId, result.messageId, { endpointId: input.endpoint.endpointId, endpointSessionFile: input.endpoint.sessionFile, senderEndpointId: input.callerEndpointId, senderEndpointSessionFile: input.callerEndpointSessionFile, delivery: "steer", kind: "intervention", payload: { messageId: result.messageId, agentId: input.agentId, taskId: result.taskId, sequence: result.sequence, message: input.message } }); }
        else if (!(await readTask(stateRoot, meshId, result.taskId).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)))) { const reservation = await reserveExistingAgentTaskCapacityUnlocked(stateRoot, meshId, input.agentId); try { await createTaskUnlocked(stateRoot, meshId, input.agentId, input.message, { requesterEndpointId: input.callerEndpointId, ...(input.callerEndpointId.startsWith("agent:") ? { requesterAgentId: input.callerEndpointId.slice("agent:".length) } : {}), completion: input.completion }, reservation.reservationId, result.taskId, input.authority); } catch (error) { await releasePendingMeshReservationUnlocked(stateRoot, meshId, reservation.reservationId, "mesh_send task creation failed").catch(() => {}); throw error; } }
        return result;
    });
}

/** Reserves the stable IDs for the new-agent mesh_send path before W2 performs external launch I/O. */
export async function reserveNewAgentMeshSendSubmission(stateRoot: string, meshId: string, input: { callerEndpointId: string; callerEndpointSessionFile: string; toolCallId: string; canonicalArguments: unknown; agentId?: string; taskId?: string }): Promise<{ result: Extract<MeshSendResult, { disposition: "submitted" }>; created: boolean }> {
    return withMeshLock(stateRoot, meshId, async () => {
        await assertExpectedEndpointBindingUnlocked(stateRoot, meshId, { endpointId: input.callerEndpointId, endpointSessionFile: input.callerEndpointSessionFile });
        const path = sendRetryPath(stateRoot, meshId, input.callerEndpointId, input.toolCallId); const digest = createHash("sha256").update(canonicalJson(input.canonicalArguments)).digest("hex");
        const raw = await optional<unknown>(path); const existing = raw === undefined ? undefined : validateSendIdempotency(raw, meshId);
        if (existing) { if (existing.callerEndpointSessionFile !== input.callerEndpointSessionFile || existing.argumentsDigest !== digest || existing.result.disposition !== "submitted") throw new Error("mesh_send retry reused toolCallId with different arguments"); return { result: existing.result, created: false }; }
        const result = { disposition: "submitted" as const, agentId: input.agentId ?? randomUUID(), taskId: input.taskId ?? randomUUID() };
        assertUuid(result.agentId, "mesh send agentId"); assertUuid(result.taskId, "mesh send taskId");
        await writeAtomicJson(path, { schemaVersion: 1, meshId, callerEndpointId: input.callerEndpointId, callerEndpointSessionFile: input.callerEndpointSessionFile, toolCallId: input.toolCallId, argumentsDigest: digest, result, createdAt: new Date().toISOString() } satisfies MeshSendIdempotency);
        return { result, created: true };
    });
}

export async function registerMeshReport(stateRoot: string, meshId: string, input: { callerEndpointId: string; callerEndpointSessionFile: string; toolCallId: string; endpoint: MeshEndpoint; agentId: string; taskId: string; summary: string; canonicalArguments: unknown }): Promise<{ reportId: string }> { if (!input.summary.trim()) throw new Error("Mesh report summary must not be empty"); return idempotent(stateRoot, meshId, input.callerEndpointId, input.toolCallId, "mesh_report", input.canonicalArguments, async reportId => { await assertExpectedEndpointBindingUnlocked(stateRoot, meshId, { endpointId: input.callerEndpointId, endpointSessionFile: input.callerEndpointSessionFile }); const targetRaw = await optional<unknown>(endpointPath(stateRoot, meshId, input.endpoint.endpointId)); const target = targetRaw === undefined ? undefined : validateEndpoint(targetRaw, meshId, input.endpoint.endpointId); if (!sameBinding(target, input.endpoint)) throw new Error("Mesh report parent endpoint binding is stale or offline"); const event = await createEvent(stateRoot, meshId, { endpointId: input.endpoint.endpointId, endpointSessionFile: input.endpoint.sessionFile, senderEndpointId: input.callerEndpointId, senderEndpointSessionFile: input.callerEndpointSessionFile, delivery: "steer", kind: "report", payload: { reportId, agentId: input.agentId, taskId: input.taskId, summary: input.summary } }, reportId); return { eventId: event.eventId }; }).then(result => ({ reportId: result.eventId })); }

async function records(directory: string): Promise<unknown[]> { const names = await readdir(directory).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? [] : Promise.reject(error)); return Promise.all(names.filter(name => UUID.test(name.replace(/\.json$/u, ""))).map(name => json<unknown>(join(directory, name)))); }
async function pendingTasksUnlocked(stateRoot: string, meshId: string, endpoint: MeshEndpoint, observer?: OrchestrationIndexReadObserver): Promise<FrozenTask[]> { const target = { endpointId: endpoint.endpointId, endpointSessionFile: endpoint.sessionFile, bindingId: endpoint.bindingId }; const tasks = []; for (const reference of await readEndpointTaskReferences(stateRoot, meshId, target, observer)) { const task = await readTask(stateRoot, meshId, reference.taskId).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); if (!task) continue; if (task.request.agentId !== reference.agentId || task.request.completion?.endpointId !== endpoint.endpointId || task.request.completion.endpointSessionFile !== endpoint.sessionFile || task.request.completion.bindingId !== endpoint.bindingId) throw new Error("Endpoint task reference does not match authoritative task"); if (isTerminalTask(task.status.state)) { await removeOrchestrationIndexReference(stateRoot, meshId, "endpoint-tasks", reference); continue; } tasks.push(task); } return tasks.sort((a, b) => a.request.createdAt.localeCompare(b.request.createdAt) || a.request.taskId.localeCompare(b.request.taskId)).map(task => ({ taskId: task.request.taskId, agentId: task.request.agentId, state: task.status.state })); }
export async function materializeMeshCompletionEvents(stateRoot: string, meshId: string, leaseId: string, options: CompletionMaterializationOptions = {}): Promise<void> { await withMeshLock(stateRoot, meshId, () => evaluateCompletionTargets(stateRoot, meshId, leaseId, options)); }
export async function readEndpointDeliverySnapshot(stateRoot: string, meshId: string, endpoint: MeshEndpoint, observer?: OrchestrationIndexReadObserver): Promise<EndpointDeliverySnapshot> { validateEndpoint(endpoint, meshId, endpoint.endpointId); return withMeshLock(stateRoot, meshId, async () => { const raw = await optional<unknown>(endpointPath(stateRoot, meshId, endpoint.endpointId)); const durable = raw === undefined ? undefined : validateEndpoint(raw, meshId, endpoint.endpointId); if (!sameBinding(durable, endpoint)) throw new Error("Mesh endpoint binding rotated or went offline"); const target = { endpointId: endpoint.endpointId, endpointSessionFile: endpoint.sessionFile, bindingId: endpoint.bindingId }; const events: MeshEvent[] = []; for (const reference of await readEndpointEventReferences(stateRoot, meshId, target, observer)) { const value = await optional<unknown>(eventPath(stateRoot, meshId, reference.eventId)); if (value === undefined) continue; const event = validateEvent(value, meshId); if (event.endpointId !== endpoint.endpointId || event.endpointSessionFile !== endpoint.sessionFile || event.endpointBindingId !== endpoint.bindingId) throw new Error("Endpoint event reference does not match authoritative event"); if (event.state === "acknowledged") { await removeOrchestrationIndexReference(stateRoot, meshId, "endpoint-events", reference); continue; } events.push(event); } events.sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.eventId.localeCompare(b.eventId)); return { endpoint, events, observedAt: new Date().toISOString(), pendingTasks: await pendingTasksUnlocked(stateRoot, meshId, endpoint, observer) }; }); }
async function mutateEvents(stateRoot: string, meshId: string, endpoint: MeshEndpoint, eventIds: readonly string[], nextState: "injected" | "acknowledged"): Promise<void> { await withMeshLock(stateRoot, meshId, async () => { const raw = await optional<unknown>(endpointPath(stateRoot, meshId, endpoint.endpointId)); const durable = raw === undefined ? undefined : validateEndpoint(raw, meshId, endpoint.endpointId); if (!sameBinding(durable, endpoint)) throw new Error("Mesh endpoint binding rotated or went offline"); const now = new Date().toISOString(); for (const eventId of new Set(eventIds)) { const path = eventPath(stateRoot, meshId, eventId); const eventRaw = await optional<unknown>(path); const event = eventRaw === undefined ? undefined : validateEvent(eventRaw, meshId); if (!event) continue; if (event.endpointId !== endpoint.endpointId || event.endpointSessionFile !== endpoint.sessionFile || event.endpointBindingId !== endpoint.bindingId) throw new Error("Mesh event target does not match endpoint binding"); if (nextState === "injected") { if (event.state === "pending") await writeAtomicJson(path, { ...event, state: "injected", injectedAt: now }); } else if (event.state !== "acknowledged") { await writeAtomicJson(path, { ...event, state: "acknowledged", acknowledgedAt: now }); await removeOrchestrationIndexReference(stateRoot, meshId, "endpoint-events", { endpointId: event.endpointId, endpointSessionFile: event.endpointSessionFile, bindingId: event.endpointBindingId, eventId }); } } }); }
export async function markMeshEventsInjected(stateRoot: string, meshId: string, endpoint: MeshEndpoint, eventIds: readonly string[]): Promise<void> { await mutateEvents(stateRoot, meshId, endpoint, eventIds, "injected"); }
export async function acknowledgeMeshEvents(stateRoot: string, meshId: string, endpoint: MeshEndpoint, eventIds: readonly string[]): Promise<void> { await mutateEvents(stateRoot, meshId, endpoint, eventIds, "acknowledged"); }

/** Records model-context inclusion for interventions and creates one delivery-ack per sender/task scope. */
export async function acknowledgeMeshContextInterventions(stateRoot: string, meshId: string, endpoint: MeshEndpoint, eventIds: readonly string[]): Promise<ContextAcknowledgment[]> {
    return withMeshLock(stateRoot, meshId, async () => {
        const raw = await optional<unknown>(endpointPath(stateRoot, meshId, endpoint.endpointId)); const durable = raw === undefined ? undefined : validateEndpoint(raw, meshId, endpoint.endpointId);
        if (!sameBinding(durable, endpoint)) throw new Error("Mesh endpoint binding rotated or went offline");
        if (endpoint.kind !== "agent" || !endpoint.agentId) throw new Error("Only an agent endpoint can acknowledge interventions");
        const selected = (await Promise.all([...new Set(eventIds)].map(async eventId => { const rawEvent = await optional<unknown>(eventPath(stateRoot, meshId, eventId)); return rawEvent === undefined ? undefined : validateEvent(rawEvent, meshId); }))).filter((event): event is MeshEvent => event !== undefined && event.kind === "intervention");
        const scopeKey = (event: MeshEvent): string => `${event.senderEndpointId}\0${event.senderEndpointSessionFile!}\0${String(event.payload.agentId)}\0${String(event.payload.taskId)}`;
        const groups = new Map<string, MeshEvent[]>(); const replayAckIds = new Set<string>(); const replayAckIdsByScope = new Map<string, Set<string>>();
        for (const event of selected) {
            if (event.endpointId !== endpoint.endpointId || event.endpointSessionFile !== endpoint.sessionFile || event.endpointBindingId !== endpoint.bindingId) throw new Error("Mesh event target does not match endpoint binding");
            if (event.payload.agentId !== endpoint.agentId || event.state === "pending") throw new Error("Intervention was not injected into the acknowledging agent context");
            const task = await readTask(stateRoot, meshId, String(event.payload.taskId)); if (task.request.agentId !== endpoint.agentId) throw new Error("Intervention task does not belong to acknowledging agent");
            if (!event.senderEndpointSessionFile) throw new Error("Legacy intervention cannot create a delivery acknowledgment");
            const key = scopeKey(event);
            if (event.state === "acknowledged") { if (!event.ackEventId) throw new Error("Acknowledged intervention has no delivery acknowledgment"); replayAckIds.add(event.ackEventId); const values = replayAckIdsByScope.get(key) ?? new Set<string>(); values.add(event.ackEventId); replayAckIdsByScope.set(key, values); continue; }
            if (event.ackEventId) throw new Error("Unacknowledged intervention already links a delivery acknowledgment");
            const values = groups.get(key) ?? []; values.push(event); groups.set(key, values);
        }
        const orphanAckIdByScope = new Map<string, string>();
        for (const [key, ackIds] of replayAckIdsByScope) {
            const orphanIds: string[] = [];
            for (const ackId of ackIds) if (await optional<unknown>(eventPath(stateRoot, meshId, ackId)) === undefined) orphanIds.push(ackId);
            if (orphanIds.length > 1) throw new Error("Intervention context has multiple incomplete delivery acknowledgments");
            if (orphanIds[0]) orphanAckIdByScope.set(key, orphanIds[0]);
        }
        const acknowledgments: ContextAcknowledgment[] = [];
        for (const [key, events] of groups) {
            const [first] = events; const ackId = orphanAckIdByScope.get(key) ?? randomUUID(); const now = new Date().toISOString();
            for (const event of events) { await writeAtomicJson(eventPath(stateRoot, meshId, event.eventId), { ...event, state: "acknowledged", acknowledgedAt: now, ackEventId: ackId }); await removeOrchestrationIndexReference(stateRoot, meshId, "endpoint-events", { endpointId: event.endpointId, endpointSessionFile: event.endpointSessionFile, bindingId: event.endpointBindingId, eventId: event.eventId }); }
            const all = (await records(meshPaths(stateRoot, meshId).events)).map(value => validateEvent(value, meshId)).filter(event => event.kind === "intervention" && scopeKey(event) === key);
            const acknowledged = all.filter(event => event.state === "acknowledged").sort((a, b) => Number(a.payload.sequence) - Number(b.payload.sequence)); let acknowledgedThrough = 0;
            for (const event of acknowledged) { const sequence = Number(event.payload.sequence); if (sequence === acknowledgedThrough + 1) acknowledgedThrough = sequence; else if (sequence > acknowledgedThrough + 1) break; }
            const messageIds = all.filter(event => event.ackEventId === ackId).map(event => event.eventId).sort((a, b) => a.localeCompare(b));
            if (!messageIds.length || acknowledgedThrough < 1) throw new Error("Delivery acknowledgment has no acknowledged intervention frontier");
            await ensureEvent(stateRoot, meshId, ackId, { endpointId: first!.senderEndpointId, endpointSessionFile: first!.senderEndpointSessionFile!, senderEndpointId: endpoint.endpointId, senderEndpointSessionFile: endpoint.sessionFile, delivery: "steer", kind: "delivery-ack", payload: { ackId, agentId: String(first!.payload.agentId), taskId: String(first!.payload.taskId), acknowledgedThrough, messageIds } });
            acknowledgments.push({ eventId: ackId, agentId: String(first!.payload.agentId), taskId: String(first!.payload.taskId), acknowledgedThrough, messageIds });
        }
        const inventory = (await records(meshPaths(stateRoot, meshId).events)).map(value => validateEvent(value, meshId)); const createdAckIds = new Set(acknowledgments.map(acknowledgment => acknowledgment.eventId)); const replayCompleted = acknowledgments.length === 0;
        for (const ackId of replayAckIds) {
            if (createdAckIds.has(ackId)) continue;
            let event = await optional<unknown>(eventPath(stateRoot, meshId, ackId)).then(value => value === undefined ? undefined : validateEvent(value, meshId));
            if (event && !replayCompleted) continue;
            if (!event) {
                const linked = inventory.filter(candidate => candidate.kind === "intervention" && candidate.state === "acknowledged" && candidate.ackEventId === ackId); const [first] = linked;
                if (!first?.senderEndpointSessionFile) throw new Error("Incomplete delivery acknowledgment has no linked intervention");
                const all = inventory.filter(candidate => candidate.kind === "intervention" && scopeKey(candidate) === scopeKey(first)).sort((a, b) => Number(a.payload.sequence) - Number(b.payload.sequence)); let acknowledgedThrough = 0;
                for (const candidate of all) { const sequence = Number(candidate.payload.sequence); if (candidate.state === "acknowledged" && sequence === acknowledgedThrough + 1) acknowledgedThrough = sequence; else if (sequence > acknowledgedThrough + 1) break; }
                const messageIds = linked.map(candidate => candidate.eventId).sort((a, b) => a.localeCompare(b));
                event = await ensureEvent(stateRoot, meshId, ackId, { endpointId: first.senderEndpointId, endpointSessionFile: first.senderEndpointSessionFile, senderEndpointId: endpoint.endpointId, senderEndpointSessionFile: endpoint.sessionFile, delivery: "steer", kind: "delivery-ack", payload: { ackId, agentId: String(first.payload.agentId), taskId: String(first.payload.taskId), acknowledgedThrough, messageIds } });
            }
            const payload = event.payload;
            if (event.kind !== "delivery-ack" || event.senderEndpointId !== endpoint.endpointId || event.senderEndpointSessionFile !== endpoint.sessionFile) throw new Error("Intervention delivery acknowledgment is invalid");
            acknowledgments.push({ eventId: ackId, agentId: String(payload.agentId), taskId: String(payload.taskId), acknowledgedThrough: Number(payload.acknowledgedThrough), messageIds: [...(payload.messageIds as string[])] });
        }
        return acknowledgments;
    });
}
