import { randomUUID } from "node:crypto";
import { appendFile, chmod, link, mkdir, open, readFile, readdir, rename, rm, unlink, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { launchEnvelopeDigest, validateAgentDefinition, validateLaunchEnvelope, type AgentDefinition, type AgentHarness } from "./agent_types.ts";
import { mapConcurrent } from "./orchestration_concurrency.ts";
import { withRunLock } from "./orchestration_lock.ts";
import { AGENT_STATES, TASK_STATES, addUsage, emptyUsage, isTerminalAgent, isTerminalTask, type AgentLineage, type AgentRecord, type AgentSnapshot, type AgentStatus, type Intervention, type NativeCapabilities, type TaskCancelRequest, type TaskRequest, type TaskResult, type TaskSnapshot, type TaskStatus, type UsageClaim } from "./orchestration_types.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
export interface AgentPaths { directory: string; agent: string; status: string; events: string; session: string; tasks: string }
export interface TaskPaths { directory: string; request: string; status: string; result: string; cancel: string; usageClaim: string }
export function assertId(id: string, label = "ID"): void { if (!UUID.test(id)) throw new Error(`Invalid ${label}: ${id}`); }
export function agentPaths(stateRoot: string, agentId: string): AgentPaths { assertId(agentId, "agent ID"); const directory = join(stateRoot, "agents", agentId); return { directory, agent: join(directory, "agent.json"), status: join(directory, "status.json"), events: join(directory, "events.jsonl"), session: join(directory, "session"), tasks: join(directory, "tasks") }; }
export function taskPaths(stateRoot: string, agentId: string, taskId: string): TaskPaths { assertId(taskId, "task ID"); const directory = join(agentPaths(stateRoot, agentId).tasks, taskId); return { directory, request: join(directory, "request.json"), status: join(directory, "status.json"), result: join(directory, "result.json"), cancel: join(directory, "cancel.json"), usageClaim: join(directory, "usage-claim.json") }; }
async function atomicJson(path: string, value: unknown): Promise<void> { const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 }); await rename(temporary, path); await chmod(path, 0o600); }
export async function readJson<T>(path: string): Promise<T> { return JSON.parse(await readFile(path, "utf8")) as T; }
function schema2(value: unknown, required: readonly string[], optional: readonly string[], label: string): Record<string, unknown> {
    if (!value || typeof value !== "object" || Array.isArray(value) || (value as { schemaVersion?: unknown }).schemaVersion !== 2) throw new Error(`Unsupported ${label} schemaVersion`);
    const raw = value as Record<string, unknown>; const allowed = ["schemaVersion", ...required, ...optional];
    const unknown = Object.keys(raw).filter(key => !allowed.includes(key)); if (unknown.length) throw new Error(`${label} contains unknown keys: ${unknown.join(", ")}`);
    const missing = required.filter(key => !(key in raw)); if (missing.length) throw new Error(`${label} is missing required keys: ${missing.join(", ")}`);
    return raw;
}
function nonempty(value: unknown, label: string): string { if (typeof value !== "string" || !value.trim()) throw new Error(`${label} must be a non-empty string`); return value; }
function optionalText(value: unknown, label: string): string | undefined { return value === undefined ? undefined : nonempty(value, label); }
function bool(value: unknown, label: string): boolean { if (typeof value !== "boolean") throw new Error(`${label} must be a boolean`); return value; }
function integer(value: unknown, label: string): number { if (!Number.isInteger(value) || Number(value) < 0) throw new Error(`${label} must be a non-negative integer`); return Number(value); }
function sameId(value: unknown, expected: string, label: string): string { const id = nonempty(value, label); assertId(id, label); if (id !== expected) throw new Error(`${label} does not match path identity`); return id; }
function optionalId(value: unknown, label: string): string | undefined { if (value === undefined) return undefined; const id = nonempty(value, label); assertId(id, label); return id; }
function stringList(value: unknown, label: string, ids = false): string[] { if (!Array.isArray(value) || value.some(item => typeof item !== "string")) throw new Error(`${label} must be a string array`); const result = [...value] as string[]; if (new Set(result).size !== result.length) throw new Error(`${label} must not contain duplicates`); if (ids) for (const id of result) assertId(id, label); return result; }
function usage(value: unknown, label: string): TaskResult["usage"] { const raw = value as Record<string, unknown>; if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`${label} must be an object`); const keys = ["input", "output", "cacheRead", "cacheWrite", "cacheWrite1h", "totalTokens", "reasoning", "cost"]; const unknown = Object.keys(raw).filter(key => !keys.includes(key)); if (unknown.length) throw new Error(`${label} contains unknown keys: ${unknown.join(", ")}`); for (const key of ["input", "output", "cacheRead", "cacheWrite", "totalTokens"] as const) if (typeof raw[key] !== "number" || !Number.isFinite(raw[key])) throw new Error(`${label}.${key} must be a finite number`); for (const key of ["reasoning", "cacheWrite1h"] as const) if (raw[key] !== undefined && (typeof raw[key] !== "number" || !Number.isFinite(raw[key]))) throw new Error(`${label}.${key} must be a finite number`); const cost = raw.cost as Record<string, unknown>; if (!cost || typeof cost !== "object" || Array.isArray(cost) || JSON.stringify(Object.keys(cost).sort()) !== JSON.stringify(["cacheRead", "cacheWrite", "input", "output", "total"])) throw new Error(`${label}.cost has invalid keys`); for (const key of Object.keys(cost)) if (typeof cost[key] !== "number" || !Number.isFinite(cost[key])) throw new Error(`${label}.cost.${key} must be a finite number`); return value as TaskResult["usage"]; }
function tmuxReference(value: unknown): AgentRecord["tmux"] { const raw = value as Record<string, unknown>; const keys = ["socket", "serverPid", "sessionId", "sessionName", "windowId", "paneId", "windowName"]; if (!raw || typeof raw !== "object" || Array.isArray(raw) || JSON.stringify(Object.keys(raw).sort()) !== JSON.stringify([...keys].sort())) throw new Error("agent record tmux has invalid keys"); for (const key of keys) nonempty(raw[key], `agent record tmux.${key}`); return value as AgentRecord["tmux"]; }
function capabilities(value: unknown): NativeCapabilities { const raw = value as Record<string, unknown>; const required = ["nativeScreen", "taskDelivery", "taskCompletion", "usage", "interactiveInterventions"]; const optional = ["taskCancellation", "terminalHistory"]; if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error("agent record capabilities must be an object"); const unknown = Object.keys(raw).filter(key => !required.includes(key) && !optional.includes(key)); if (unknown.length || required.some(key => !(key in raw))) throw new Error("agent record capabilities has invalid keys"); for (const key of [...required, ...optional]) if (raw[key] !== undefined) bool(raw[key], `agent record capabilities.${key}`); return value as NativeCapabilities; }
function intervention(value: unknown, agentId: string, taskId: string): Intervention { const raw = value as Record<string, unknown>; const keys = ["sequence", "timestamp", "taskId", "text", "deliveryMode", "images"]; if (!raw || typeof raw !== "object" || Array.isArray(raw) || Object.keys(raw).some(key => !keys.includes(key)) || ["sequence", "timestamp", "text", "deliveryMode", "images"].some(key => !(key in raw))) throw new Error("task result intervention has invalid keys"); integer(raw.sequence, "intervention.sequence"); nonempty(raw.timestamp, "intervention.timestamp"); if (raw.taskId !== undefined && sameId(raw.taskId, taskId, "intervention.taskId") !== taskId) throw new Error("intervention task identity mismatch"); if (raw.deliveryMode !== "steer" && raw.deliveryMode !== "followUp" && raw.deliveryMode !== "idle") throw new Error("intervention.deliveryMode is invalid"); if (!Array.isArray(raw.images) || raw.images.some(item => typeof item !== "string")) throw new Error("intervention.images must be a string array"); if (typeof raw.text !== "string") throw new Error("intervention.text must be a string"); void agentId; return value as Intervention; }
const AGENT_REQUIRED = ["agentId", "agent", "harness", "cwd", "createdAt", "agentSnapshot", "launchEnvelope", "launchEnvelopeDigest", "tmux", "capabilities", "callerIdentity", "targetAgent", "depth", "originSessionId"];
const AGENT_OPTIONAL = ["tmuxOwnership", "parentAgentId", "originSessionFile"];
async function readAgentRecord(path: string): Promise<AgentRecord> {
    const value = await readJson<AgentRecord>(path); const raw = schema2(value, AGENT_REQUIRED, AGENT_OPTIONAL, "agent record"); const expectedAgentId = basename(dirname(path)); sameId(raw.agentId, expectedAgentId, "agent record agentId");
    const expectedEnvelopePath = join(dirname(path), "launch-envelope.json"); const agent = nonempty(raw.agent, "agent record agent"); const target = nonempty(raw.targetAgent, "agent record targetAgent");
    if (raw.launchEnvelope !== expectedEnvelopePath || agent !== target) throw new Error("agent record identity does not match its immutable launch reference");
    const harness = raw.harness; if (harness !== "pi" && harness !== "cursor-agent") throw new Error("agent record harness is invalid"); nonempty(raw.cwd, "agent record cwd"); nonempty(raw.createdAt, "agent record createdAt"); nonempty(raw.callerIdentity, "agent record callerIdentity"); nonempty(raw.originSessionId, "agent record originSessionId"); optionalText(raw.originSessionFile, "agent record originSessionFile"); optionalId(raw.parentAgentId, "agent record parentAgentId"); integer(raw.depth, "agent record depth"); if (raw.tmuxOwnership !== undefined && raw.tmuxOwnership !== "origin-hub" && raw.tmuxOwnership !== "dedicated") throw new Error("agent record tmuxOwnership is invalid"); tmuxReference(raw.tmux); capabilities(raw.capabilities);
    const definition = validateAgentDefinition(agent, raw.agentSnapshot, "agent record agentSnapshot"); const envelope = validateLaunchEnvelope(await readJson<unknown>(expectedEnvelopePath)); const digest = launchEnvelopeDigest(envelope);
    if (envelope.identity !== `agent:${agent}` || JSON.stringify(envelope.self) !== JSON.stringify(definition) || definition.harness !== harness) throw new Error("agent record identity does not match its immutable launch envelope");
    if (raw.launchEnvelopeDigest !== digest) throw new Error("agent record launch-envelope digest does not match the complete immutable closure");
    return { ...value, agent: agent as string, harness: harness as AgentHarness, targetAgent: target, agentSnapshot: definition, launchEnvelopeDigest: digest };
}
export async function prepareAgent(stateRoot: string, input: { agent: string; harness: AgentHarness; cwd: string; agentSnapshot: AgentDefinition; launchEnvelope: string; lineage: AgentLineage; capabilities: NativeCapabilities }): Promise<{ agentId: string; paths: AgentPaths }> { void input; const agentId = randomUUID(); const paths = agentPaths(stateRoot, agentId); await mkdir(paths.session, { recursive: true, mode: 0o700 }); await mkdir(paths.tasks, { recursive: true, mode: 0o700 }); await writeFile(paths.events, "", { mode: 0o600 }); const placeholder: AgentStatus = { schemaVersion: 2, agentId, state: "creating", bridgeReady: false, agentUsage: emptyUsage(), accountedTaskIds: [], updatedAt: new Date().toISOString() }; await atomicJson(paths.status, placeholder); return { agentId, paths }; }
export async function publishAgent(paths: AgentPaths, input: Omit<AgentRecord, "schemaVersion" | "createdAt" | "launchEnvelopeDigest">): Promise<AgentRecord> { const envelope = validateLaunchEnvelope(await readJson<unknown>(input.launchEnvelope)); const agent: AgentRecord = { schemaVersion: 2, createdAt: new Date().toISOString(), ...input, launchEnvelopeDigest: launchEnvelopeDigest(envelope) }; await atomicJson(paths.agent, agent); return agent; }
export async function removePreparedAgent(paths: AgentPaths): Promise<void> { await rm(paths.directory, { recursive: true, force: true }); }
function validateAgentStatus(value: unknown, expectedAgentId: string): AgentStatus { const raw = schema2(value, ["agentId", "state", "bridgeReady", "agentUsage", "accountedTaskIds", "updatedAt"], ["activeTaskId", "latestTaskId", "childSessionId", "childSessionFile", "exitReason"], "agent status"); sameId(raw.agentId, expectedAgentId, "agent status agentId"); if (!AGENT_STATES.includes(raw.state as never)) throw new Error("agent status state is invalid"); optionalId(raw.activeTaskId, "agent status activeTaskId"); optionalId(raw.latestTaskId, "agent status latestTaskId"); bool(raw.bridgeReady, "agent status bridgeReady"); optionalText(raw.childSessionId, "agent status childSessionId"); optionalText(raw.childSessionFile, "agent status childSessionFile"); usage(raw.agentUsage, "agent status agentUsage"); stringList(raw.accountedTaskIds, "agent status accountedTaskIds", true); nonempty(raw.updatedAt, "agent status updatedAt"); optionalText(raw.exitReason, "agent status exitReason"); return value as AgentStatus; }
function validateTaskRequest(value: unknown, agentId: string, taskId: string): TaskRequest { const raw = schema2(value, ["agentId", "taskId", "prompt", "createdAt"], [], "task request"); sameId(raw.agentId, agentId, "task request agentId"); sameId(raw.taskId, taskId, "task request taskId"); if (typeof raw.prompt !== "string" || !raw.prompt.trim()) throw new Error("task request prompt must be non-empty"); nonempty(raw.createdAt, "task request createdAt"); return value as TaskRequest; }
function validateTaskStatus(value: unknown, agentId: string, taskId: string): TaskStatus { const raw = schema2(value, ["agentId", "taskId", "state", "createdAt"], ["startedAt", "finishedAt", "error"], "task status"); sameId(raw.agentId, agentId, "task status agentId"); sameId(raw.taskId, taskId, "task status taskId"); if (!TASK_STATES.includes(raw.state as never)) throw new Error("task status state is invalid"); nonempty(raw.createdAt, "task status createdAt"); optionalText(raw.startedAt, "task status startedAt"); optionalText(raw.finishedAt, "task status finishedAt"); optionalText(raw.error, "task status error"); return value as TaskStatus; }
function validateTaskResult(value: unknown, agentId: string, taskId: string): TaskResult { const raw = schema2(value, ["agentId", "taskId", "outcome", "output", "usage", "turns", "interventions", "startedAt", "finishedAt"], ["error"], "task result"); sameId(raw.agentId, agentId, "task result agentId"); sameId(raw.taskId, taskId, "task result taskId"); if (raw.outcome !== "succeeded" && raw.outcome !== "failed" && raw.outcome !== "stopped") throw new Error("task result outcome is invalid"); if (typeof raw.output !== "string") throw new Error("task result output must be a string"); usage(raw.usage, "task result usage"); integer(raw.turns, "task result turns"); if (!Array.isArray(raw.interventions)) throw new Error("task result interventions must be an array"); raw.interventions.forEach(item => intervention(item, agentId, taskId)); nonempty(raw.startedAt, "task result startedAt"); nonempty(raw.finishedAt, "task result finishedAt"); optionalText(raw.error, "task result error"); return value as TaskResult; }
function validateTaskCancellation(value: unknown, agentId: string, taskId: string): TaskCancelRequest { const raw = schema2(value, ["agentId", "taskId", "requestedAt", "reason"], [], "task cancellation"); sameId(raw.agentId, agentId, "task cancellation agentId"); sameId(raw.taskId, taskId, "task cancellation taskId"); nonempty(raw.requestedAt, "task cancellation requestedAt"); nonempty(raw.reason, "task cancellation reason"); return value as TaskCancelRequest; }
function validateUsageClaim(value: unknown, expected?: { agentId?: string; taskId?: string }): UsageClaim { const raw = schema2(value, ["originSessionId", "toolCallId", "toolName", "agentId", "taskId", "claimedAt"], ["parentSessionFile"], "usage claim"); nonempty(raw.originSessionId, "usage claim originSessionId"); optionalText(raw.parentSessionFile, "usage claim parentSessionFile"); nonempty(raw.toolCallId, "usage claim toolCallId"); if (!["subagent_run", "subagent_submit", "subagent_get", "subagent_wait", "subagent_stop"].includes(raw.toolName as string)) throw new Error("usage claim toolName is invalid"); const agentId = nonempty(raw.agentId, "usage claim agentId"); const taskId = nonempty(raw.taskId, "usage claim taskId"); assertId(agentId, "usage claim agentId"); assertId(taskId, "usage claim taskId"); if (expected?.agentId && agentId !== expected.agentId) throw new Error("usage claim agentId does not match path identity"); if (expected?.taskId && taskId !== expected.taskId) throw new Error("usage claim taskId does not match path identity"); nonempty(raw.claimedAt, "usage claim claimedAt"); return value as UsageClaim; }
export async function readAgentStatus(paths: AgentPaths): Promise<AgentStatus> { return validateAgentStatus(await readJson<unknown>(paths.status), basename(paths.directory)); }
export async function patchAgentStatus(paths: AgentPaths, patch: Partial<AgentStatus>): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next: AgentStatus = { ...current, ...patch, schemaVersion: 2, agentId: current.agentId, updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function markBridgeReady(paths: AgentPaths, resolvedEnvelopeDigest: string): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const record = await readAgentRecord(paths.agent); if (record.launchEnvelopeDigest !== resolvedEnvelopeDigest) throw new Error("Resolved launch envelope digest does not match the persisted agent record"); const current = await readAgentStatus(paths); const next = { ...current, bridgeReady: true, state: current.state === "creating" ? "idle" as const : current.state, updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function recordChildSessionIdentity(paths: AgentPaths, childSessionId: string, childSessionFile: string | undefined): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next: AgentStatus = { ...current, childSessionId, ...(childSessionFile ? { childSessionFile } : {}), updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function markAgentStoppingWithDisposition(paths: AgentPaths): Promise<{ status: AgentStatus; initiated: boolean }> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); if (current.state === "stopped" || current.state === "failed" || current.state === "stopping") return { status: current, initiated: false }; const next: AgentStatus = { ...current, state: "stopping", updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return { status: next, initiated: true }; }); }
export async function markAgentStopping(paths: AgentPaths): Promise<AgentStatus> { return (await markAgentStoppingWithDisposition(paths)).status; }
export async function markAgentCleanupPending(paths: AgentPaths): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next: AgentStatus = { ...current, state: "stopping", updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function restoreAgentAfterStopFailure(stateRoot: string, agentId: string): Promise<AgentStatus> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); if (current.state !== "stopping") return current; let activeTaskId = current.activeTaskId; if (activeTaskId) { const task = await readTask(stateRoot, agentId, activeTaskId); if (isTerminalTask(task.status.state)) activeTaskId = undefined; } const next: AgentStatus = { ...current, state: activeTaskId ? "busy" : "idle", activeTaskId, updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function createTask(stateRoot: string, agentId: string, prompt: string): Promise<TaskSnapshot> { if (!prompt.trim()) throw new Error("Subagent prompt must not be empty"); const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const agent = await readAgentRecord(paths.agent); const status = await readAgentStatus(paths); if (agent.agentId !== agentId) throw new Error("Agent metadata mismatch"); if (status.state !== "idle" && status.state !== "creating") throw new Error(`Agent ${agentId} is ${status.state}${status.activeTaskId ? `; active task ${status.activeTaskId}` : ""}`); const taskId = randomUUID(); const task = taskPaths(stateRoot, agentId, taskId); await mkdir(task.directory, { recursive: true, mode: 0o700 }); const createdAt = new Date().toISOString(); const request: TaskRequest = { schemaVersion: 2, agentId, taskId, prompt, createdAt }; const taskStatus: TaskStatus = { schemaVersion: 2, agentId, taskId, state: "created", createdAt }; await atomicJson(task.request, request); await atomicJson(task.status, taskStatus); await atomicJson(paths.status, { ...status, state: "busy", activeTaskId: taskId, latestTaskId: taskId, updatedAt: createdAt }); await appendEventUnlocked(paths, "task_created", { taskId }).catch(() => {}); return { request, status: taskStatus, result: null, interventions: [], claimed: false, directory: task.directory }; }); }
export async function readTask(stateRoot: string, agentId: string, taskId: string): Promise<TaskSnapshot> { const paths = taskPaths(stateRoot, agentId, taskId); const agent = agentPaths(stateRoot, agentId); const [rawRequest, rawStatus, interventions] = await Promise.all([readJson<unknown>(paths.request), readJson<unknown>(paths.status), readInterventions(agent, taskId)]); const request = validateTaskRequest(rawRequest, agentId, taskId); const status = validateTaskStatus(rawStatus, agentId, taskId); const rawResult = await readJson<unknown>(paths.result).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? null : Promise.reject(error)); const result = rawResult ? validateTaskResult(rawResult, agentId, taskId) : null; const rawClaim = await readJson<unknown>(paths.usageClaim).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); const claimed = rawClaim === undefined ? false : Boolean(validateUsageClaim(rawClaim, { agentId, taskId })); return { request, status, result, interventions, claimed, directory: paths.directory }; }
export async function readAgentSnapshot(stateRoot: string, agentId: string, taskId?: string): Promise<AgentSnapshot> { const paths = agentPaths(stateRoot, agentId); const [agent, status] = await Promise.all([readAgentRecord(paths.agent), readAgentStatus(paths)]); const selected = taskId ?? status.activeTaskId ?? status.latestTaskId; return { agent, status, ...(selected ? { task: await readTask(stateRoot, agentId, selected) } : {}) }; }
export async function claimPendingTask(stateRoot: string, agentId: string): Promise<TaskSnapshot | null> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const status = await readAgentStatus(paths); if (!status.activeTaskId || status.state !== "busy") return null; const task = await readTask(stateRoot, agentId, status.activeTaskId); if (task.status.state !== "created") return null; const cancellation = await readTaskCancellation(stateRoot, agentId, task.request.taskId); if (cancellation) { await finishTaskUnlocked(stateRoot, paths, agentId, task.request.taskId, { outcome: "stopped", error: cancellation.reason }); return null; } const startedAt = new Date().toISOString(); await atomicJson(taskPaths(stateRoot, agentId, task.request.taskId).status, { ...task.status, state: "running", startedAt }); await appendEventUnlocked(paths, "task_started", { taskId: task.request.taskId }).catch(() => {}); return { ...task, status: { ...task.status, state: "running", startedAt } }; }); }
export async function readTaskCancellation(stateRoot: string, agentId: string, taskId: string): Promise<TaskCancelRequest | undefined> { const value = await readJson<unknown>(taskPaths(stateRoot, agentId, taskId).cancel).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); return value === undefined ? undefined : validateTaskCancellation(value, agentId, taskId); }
export async function requestTaskCancellation(stateRoot: string, agentId: string, taskId: string, reason: string): Promise<{ request?: TaskCancelRequest; created: boolean; snapshot: AgentSnapshot }> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const task = await readTask(stateRoot, agentId, taskId); if (isTerminalTask(task.status.state)) return { created: false, snapshot: await readAgentSnapshot(stateRoot, agentId, taskId) }; let request = await readTaskCancellation(stateRoot, agentId, taskId); const created = request === undefined; if (!request) { request = { schemaVersion: 2, agentId, taskId, requestedAt: new Date().toISOString(), reason }; await atomicJson(taskPaths(stateRoot, agentId, taskId).cancel, request); await appendEventUnlocked(paths, "task_cancel_requested", { taskId, reason }).catch(() => {}); } if (task.status.state === "created") await finishTaskUnlocked(stateRoot, paths, agentId, taskId, { outcome: "stopped", error: request.reason }); return { request, created, snapshot: await readAgentSnapshot(stateRoot, agentId, taskId) }; }); }
export async function recordIntervention(stateRoot: string, agentId: string, input: Omit<Intervention, "sequence" | "timestamp">): Promise<Intervention> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const events = await readEvents(paths); const intervention: Intervention = { sequence: events.reduce((n, event) => Math.max(n, Number(event.sequence) || 0), 0) + 1, timestamp: new Date().toISOString(), ...input }; await appendFile(paths.events, `${JSON.stringify({ schemaVersion: 1, type: "intervention", ...intervention })}\n`, { mode: 0o600 }); return intervention; }); }
export async function readInterventions(paths: AgentPaths, taskId?: string): Promise<Intervention[]> { return (await readEvents(paths)).filter(event => { if (event.type !== "intervention") return false; const keys = ["schemaVersion", "type", "sequence", "timestamp", "taskId", "text", "deliveryMode", "images"]; const unknown = Object.keys(event).filter(key => !keys.includes(key)); if (event.schemaVersion !== 1 || unknown.length) return false; return taskId === undefined ? event.taskId === undefined : event.taskId === taskId; }).map(({ schemaVersion: _schemaVersion, type: _type, ...event }) => event as unknown as Intervention); }
async function readEvents(paths: AgentPaths): Promise<Array<Record<string, unknown>>> { const text = await readFile(paths.events, "utf8"); return text.split("\n").filter(Boolean).flatMap(line => { try { return [JSON.parse(line) as Record<string, unknown>]; } catch { return []; } }); }
async function appendEventUnlocked(paths: AgentPaths, type: string, data: Record<string, unknown>): Promise<void> { const events = await readEvents(paths); await appendFile(paths.events, `${JSON.stringify({ schemaVersion: 1, sequence: events.length + 1, timestamp: new Date().toISOString(), type, ...data })}\n`, { mode: 0o600 }); }
export async function appendAgentEvent(stateRoot: string, agentId: string, type: string, data: Record<string, unknown>): Promise<void> { const paths = agentPaths(stateRoot, agentId); await withRunLock(paths.directory, () => appendEventUnlocked(paths, type, data)); }
export async function recordIdleUsage(stateRoot: string, agentId: string, usage: TaskResult["usage"]): Promise<void> { const paths = agentPaths(stateRoot, agentId); await withRunLock(paths.directory, async () => { const status = await readAgentStatus(paths); const agentUsage = structuredClone(status.agentUsage ?? emptyUsage()); addUsage(agentUsage, usage); await atomicJson(paths.status, { ...status, agentUsage, updatedAt: new Date().toISOString() }); await appendEventUnlocked(paths, "idle_usage", { usage }); }); }
async function finishTaskUnlocked(stateRoot: string, paths: AgentPaths, agentId: string, taskId: string, input: { outcome: TaskResult["outcome"]; output?: string; usage?: TaskResult["usage"]; turns?: number; error?: string }): Promise<TaskResult> { const task = await readTask(stateRoot, agentId, taskId); const status = await readAgentStatus(paths); const taskTerminal = isTerminalTask(task.status.state); const cancellation = taskTerminal ? undefined : await readTaskCancellation(stateRoot, agentId, taskId); const forcedOutcome = (status.state === "stopping" || cancellation) && !taskTerminal ? "stopped" : input.outcome; const replaceProvisional = !taskTerminal && task.result !== null && task.result.outcome !== forcedOutcome; const now = new Date().toISOString(); const error = forcedOutcome === "stopped" && !taskTerminal ? input.error ?? cancellation?.reason ?? "Stopped while task completion was settling" : input.error; const base = task.result ?? { schemaVersion: 2, agentId, taskId, outcome: forcedOutcome, output: input.output ?? "", usage: input.usage ?? emptyUsage(), turns: input.turns ?? 0, interventions: await readInterventions(paths, taskId), startedAt: task.status.startedAt ?? task.status.createdAt, finishedAt: now }; const result: TaskResult = replaceProvisional ? { ...base, outcome: forcedOutcome, finishedAt: now, ...(error ? { error } : {}) } : { ...base, ...(base.error || !error ? {} : { error }) }; if (!task.result || replaceProvisional) await atomicJson(taskPaths(stateRoot, agentId, taskId).result, result);
    const accountedTaskIds = [...(status.accountedTaskIds ?? [])]; const agentUsage = structuredClone(status.agentUsage ?? emptyUsage()); if (!accountedTaskIds.includes(taskId)) { addUsage(agentUsage, result.usage); accountedTaskIds.push(taskId); } await atomicJson(paths.status, { ...status, agentUsage, accountedTaskIds, updatedAt: now });
    if (!taskTerminal || task.status.state !== result.outcome) await atomicJson(taskPaths(stateRoot, agentId, taskId).status, { ...task.status, state: result.outcome, finishedAt: result.finishedAt, ...(result.error ? { error: result.error } : {}) }); const completesActiveTask = status.activeTaskId === taskId; const state = status.state === "stopping" ? "stopping" : status.state === "stopped" || status.state === "failed" ? status.state : completesActiveTask ? "idle" : status.state; await atomicJson(paths.status, { ...status, state, activeTaskId: completesActiveTask ? undefined : status.activeTaskId, agentUsage, accountedTaskIds, updatedAt: now }); if (!taskTerminal || replaceProvisional || !task.result) await appendEventUnlocked(paths, "task_finished", { taskId, outcome: result.outcome }).catch(() => {}); return result; }
export async function finishTask(stateRoot: string, agentId: string, taskId: string, input: { outcome: TaskResult["outcome"]; output?: string; usage?: TaskResult["usage"]; turns?: number; error?: string }): Promise<TaskResult> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, () => finishTaskUnlocked(stateRoot, paths, agentId, taskId, input)); }
export async function failAgent(stateRoot: string, agentId: string, reason: string, stopped = false, options: { overrideTerminalReason?: boolean } = {}): Promise<void> { const paths = agentPaths(stateRoot, agentId); await withRunLock(paths.directory, async () => { const status = await readAgentStatus(paths); if (isTerminalAgent(status.state) && !options.overrideTerminalReason) return; if (status.activeTaskId) await finishTaskUnlocked(stateRoot, paths, agentId, status.activeTaskId, { outcome: stopped ? "stopped" : "failed", error: reason }); const current = await readAgentStatus(paths); if (isTerminalAgent(current.state) && !options.overrideTerminalReason) return; await atomicJson(paths.status, { ...current, state: stopped ? "stopped" : "failed", activeTaskId: undefined, exitReason: reason, updatedAt: new Date().toISOString() }); }); }
export async function findTaskAgent(stateRoot: string, taskId: string, originSessionId: string): Promise<string> { assertId(taskId, "task ID"); for (const snapshot of await listOriginAgents(stateRoot, originSessionId)) { try { await readTask(stateRoot, snapshot.agent.agentId, taskId); return snapshot.agent.agentId; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } } throw new Error(`Task ${taskId} was not found in this origin session`); }
export async function listOriginAgents(stateRoot: string, originSessionId: string): Promise<AgentSnapshot[]> {
    const root = join(stateRoot, "agents");
    const entries = await readdir(root).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? [] : Promise.reject(error));
    const matchingIds = (await mapConcurrent(entries.filter(id => UUID.test(id)), 8, async id => {
        try {
            const record = await readAgentRecord(agentPaths(stateRoot, id).agent);
            return record.originSessionId === originSessionId ? id : undefined;
        } catch { return undefined; }
    })).filter((id): id is string => id !== undefined);
    const values = (await mapConcurrent(matchingIds, 8, async id => {
        try { return await readAgentSnapshot(stateRoot, id); }
        catch { return undefined; }
    })).filter((snapshot): snapshot is AgentSnapshot => snapshot !== undefined);
    return values.sort((a, b) => b.agent.createdAt.localeCompare(a.agent.createdAt));
}
function persistedClaimTaskIds(text: string): Set<string> { const ids = new Set<string>(); for (const line of text.split("\n")) { if (!line.trim()) continue; try { const entry = JSON.parse(line) as Record<string, unknown>; const message = entry.type === "message" && entry.message && typeof entry.message === "object" ? entry.message as Record<string, unknown> : undefined; const details = message?.role === "toolResult" && message.details && typeof message.details === "object" ? message.details as Record<string, unknown> : undefined; const accounting = details?.accounting && typeof details.accounting === "object" ? details.accounting as Record<string, unknown> : undefined; if (Array.isArray(accounting?.claimedTaskIds)) for (const id of accounting.claimedTaskIds) if (typeof id === "string") ids.add(id); } catch { /* tolerate a partially written final line */ } } return ids; }
export async function reconcileOriginUsageClaims(stateRoot: string, originSessionId: string, originSessionFile?: string): Promise<number> { if (!originSessionFile) return 0; const persisted = persistedClaimTaskIds(await readFile(originSessionFile, "utf8").catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? "" : Promise.reject(error))); let recovered = 0; for (const snapshot of await listOriginAgents(stateRoot, originSessionId)) { const paths = agentPaths(stateRoot, snapshot.agent.agentId); await withRunLock(paths.directory, async () => { const entries = await readdir(paths.tasks).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? [] : Promise.reject(error)); for (const taskId of entries) { if (!UUID.test(taskId) || persisted.has(taskId)) continue; const claimPath = taskPaths(stateRoot, snapshot.agent.agentId, taskId).usageClaim; const rawClaim = await readJson<unknown>(claimPath).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); const claim = rawClaim === undefined ? undefined : validateUsageClaim(rawClaim, { agentId: snapshot.agent.agentId, taskId }); if (claim?.parentSessionFile === originSessionFile) { await unlink(claimPath); recovered += 1; } } }); } return recovered; }
export async function claimTaskUsage(stateRoot: string, agentId: string, taskId: string, originSessionId: string, originSessionFile: string | undefined, toolCallId: string, toolName: UsageClaim["toolName"]): Promise<{ created: boolean; claim: UsageClaim; result: TaskResult }> { const task = await readTask(stateRoot, agentId, taskId); const agent = await readAgentRecord(agentPaths(stateRoot, agentId).agent); if (agent.originSessionId !== originSessionId) throw new Error(`Agent ${agentId} belongs to a different origin session`); if (!task.result || !isTerminalTask(task.status.state)) throw new Error(`Task ${taskId} is not terminal`); const claim: UsageClaim = { schemaVersion: 2, originSessionId, ...(originSessionFile ? { parentSessionFile: originSessionFile } : {}), toolCallId, toolName, agentId, taskId, claimedAt: new Date().toISOString() }; const path = taskPaths(stateRoot, agentId, taskId).usageClaim; const temporary = `${path}.${randomUUID()}.tmp`; const handle = await open(temporary, "wx", 0o600); await handle.writeFile(`${JSON.stringify(claim)}\n`); await handle.close(); try { await link(temporary, path); return { created: true, claim, result: task.result }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; const existing = validateUsageClaim(await readJson<unknown>(path), { agentId, taskId }); return { created: false, claim: existing, result: task.result }; } finally { await unlink(temporary).catch(() => {}); } }
