import type { AgentDefinition } from "./agent_types.ts";
import { piLaunchDescriptor } from "./orchestration_pi.ts";
import type { HarnessRuntimeConfig, NativeCapabilities, SubagentRuntimeConfig } from "./orchestration_types.ts";
export interface NativeLaunchDescriptor { command: string; args: string[]; env: Record<string, string> }
export interface HarnessLaunchInput { agentId: string; agentDirectory: string; agent: string; launchEnvelope: string; launchEnvelopeSnapshot: import("./agent_types.ts").AgentLaunchEnvelope; depth: number; originSessionId: string; originSessionFile?: string; cwd: string }
export interface HarnessAdapter { kind: HarnessRuntimeConfig["adapter"]; capabilities: NativeCapabilities; validate(agent: AgentDefinition, harnessId: string): void; launch(config: SubagentRuntimeConfig, harness: HarnessRuntimeConfig, input: HarnessLaunchInput): NativeLaunchDescriptor }
const expectedCursor = { mode: "agent", permissionPolicy: "allow-always", sandbox: "disabled", trustWorkspace: true, worktree: false } as const;
function cursorOptions(agent: AgentDefinition): void { if (!agent.model.startsWith("cursor/") || agent.thinkingLevel !== undefined || agent.tools.length) throw new Error("Cursor agents require cursor/<model>, no thinkingLevel, and no Pi tools"); const value = agent.harnessOptions; if (!value) throw new Error("Cursor agent requires harnessOptions"); for (const [key, expected] of Object.entries(expectedCursor)) if (value[key] !== expected) throw new Error(`Cursor harnessOptions.${key} must be ${String(expected)}`); }
const pi: HarnessAdapter = { kind: "pi-native", capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: true, interactiveInterventions: true, terminalHistory: true }, validate(agent, id) { if (id !== "pi" || agent.harnessOptions !== undefined) throw new Error("Pi agents must use pi without harnessOptions"); }, launch: (config, _harness, input) => piLaunchDescriptor(config, input) };
const cursor: HarnessAdapter = { kind: "cursor-acp", capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: false, interactiveInterventions: false, terminalHistory: false }, validate: cursorOptions, launch(config, harness, input) { const definition = input.launchEnvelopeSnapshot.self; cursorOptions(definition); if (!harness.workerCommand || !harness.workerEntrypoint) throw new Error("cursor-acp harness worker is incomplete"); return { command: harness.workerCommand, args: ["--experimental-strip-types", harness.workerEntrypoint], env: { PI_SUBAGENT_AGENT_ID: input.agentId, PI_SUBAGENT_AGENT_DIR: input.agentDirectory, PI_SUBAGENT_STATE_ROOT: config.stateRoot, PI_AGENT_RESOLVED_AGENT: input.launchEnvelope, PI_SUBAGENT_EXTERNAL_CONFIG: JSON.stringify({ adapter: "cursor-acp", command: harness.command, cwd: input.cwd, permissionPolicy: expectedCursor.permissionPolicy }) } }; } };
export const harnessAdapters = Object.freeze({ "pi-native": pi, "cursor-acp": cursor });
export function resolveHarnessAdapter(config: SubagentRuntimeConfig, id: string, agent?: AgentDefinition): { adapter: HarnessAdapter; harness: HarnessRuntimeConfig } { const harness = config.harnesses[id]; if (!harness) throw new Error(`Unknown orchestration harness: ${id}`); const adapter = harnessAdapters[harness.adapter]; if (agent) adapter.validate(agent, id); return { adapter, harness }; }
