import type { AgentDefinition } from "./agent_types.ts";
import { piLaunchDescriptor } from "./orchestration_pi.ts";
import type { HarnessRuntimeConfig, NativeCapabilities, SubagentRuntimeConfig } from "./orchestration_types.ts";
export interface NativeLaunchDescriptor { command: string; args: string[]; env: Record<string, string> }
export interface HarnessLaunchInput { meshId: string; agentId: string; agentDirectory: string; agent: string; taskPath: string; launchEnvelope: string; epochSnapshot: import("./agent_types.ts").AgentLaunchEnvelope; cwd: string }
export interface HarnessAdapter { kind: HarnessRuntimeConfig["adapter"]; capabilities: NativeCapabilities; validate(agent: AgentDefinition, harnessId: string): void; launch(config: SubagentRuntimeConfig, harness: HarnessRuntimeConfig, input: HarnessLaunchInput): NativeLaunchDescriptor }
const expectedCursor = { mode: "agent", permissionPolicy: "allow-always", sandbox: "disabled", trustWorkspace: true, worktree: false } as const;
const expectedCodex = { mode: "read-only", permissionPolicy: "reject", webSearch: "cached" } as const;
const externalCapabilities = { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: false, interactiveInterventions: false, terminalHistory: false } as const;
function exactOptions(value: Record<string, unknown> | undefined, expected: Record<string, unknown>, label: string): void { if (!value || Object.keys(value).length !== Object.keys(expected).length) throw new Error(`${label} requires exact harnessOptions`); for (const [key, item] of Object.entries(expected)) if (value[key] !== item) throw new Error(`${label} harnessOptions.${key} must be ${String(item)}`); }
function cursorOptions(agent: AgentDefinition, harnessId: string): void { if (harnessId !== "cursor-agent" || !agent.model.startsWith("cursor/") || agent.thinkingLevel !== undefined || agent.tools.length) throw new Error("Cursor agents require cursor-agent, cursor/<model>, no thinkingLevel, and no Pi tools"); exactOptions(agent.harnessOptions, expectedCursor, "Cursor agent"); }
function codexOptions(agent: AgentDefinition, harnessId: string): void { if (harnessId !== "codex" || !agent.model.startsWith("codex/") || !agent.thinkingLevel || agent.tools.length) throw new Error("Codex agents require codex, codex/<model>, thinkingLevel, and no Pi tools"); exactOptions(agent.harnessOptions, expectedCodex, "Codex agent"); }
function launchMetadata(input: HarnessLaunchInput): Record<string, string> { const epoch = input.epochSnapshot; if (epoch.meshId !== input.meshId || epoch.agentId !== input.agentId) throw new Error("Launch metadata does not match the immutable epoch snapshot"); return { PI_MESH_ID: input.meshId, PI_MESH_AGENT_ID: input.agentId, PI_MESH_AGENT_DIR: input.agentDirectory, PI_MESH_EPOCH_ID: epoch.epochId, PI_MESH_TASK_PATH: input.taskPath, PI_AGENT_RESOLVED_AGENT: input.launchEnvelope }; }
function externalLaunch(_config: SubagentRuntimeConfig, harness: HarnessRuntimeConfig, input: HarnessLaunchInput, externalConfig: Record<string, string>): NativeLaunchDescriptor { if (!harness.workerCommand || !harness.workerEntrypoint) throw new Error(`${harness.adapter} harness worker is incomplete`); return { command: harness.workerCommand, args: ["--experimental-strip-types", harness.workerEntrypoint], env: { ...launchMetadata(input), PI_MESH_EXTERNAL_CONFIG: JSON.stringify(externalConfig) } }; }
const pi: HarnessAdapter = { kind: "pi-native", capabilities: { nativeScreen: true, taskDelivery: true, taskCompletion: true, taskCancellation: true, usage: true, interactiveInterventions: true, terminalHistory: true }, validate(agent, id) { if (id !== "pi" || agent.harnessOptions !== undefined) throw new Error("Pi agents must use pi without harnessOptions"); }, launch: (config, _harness, input) => piLaunchDescriptor(config, input) };
const cursor: HarnessAdapter = { kind: "cursor-acp", capabilities: externalCapabilities, validate: cursorOptions, launch(config, harness, input) { const definition = input.epochSnapshot.self; cursorOptions(definition, definition.harness); return externalLaunch(config, harness, input, { adapter: "cursor-acp", command: harness.command, cwd: input.cwd, permissionPolicy: expectedCursor.permissionPolicy }); } };
const codex: HarnessAdapter = { kind: "codex-acp", capabilities: externalCapabilities, validate: codexOptions, launch(config, harness, input) { const definition = input.epochSnapshot.self; codexOptions(definition, definition.harness); return externalLaunch(config, harness, input, { adapter: "codex-acp", command: harness.command, cwd: input.cwd, mode: expectedCodex.mode, permissionPolicy: expectedCodex.permissionPolicy, webSearch: expectedCodex.webSearch }); } };
export const harnessAdapters = Object.freeze({ "pi-native": pi, "cursor-acp": cursor, "codex-acp": codex });
export function resolveHarnessAdapter(config: SubagentRuntimeConfig, id: string, agent?: AgentDefinition): { adapter: HarnessAdapter; harness: HarnessRuntimeConfig } { const harness = config.harnesses[id]; if (!harness) throw new Error(`Unknown orchestration harness: ${id}`); const adapter = harnessAdapters[harness.adapter]; if (agent) adapter.validate(agent, id); return { adapter, harness }; }
