import { randomUUID } from "node:crypto";
import { appendFile, chmod, link, mkdir, open, readFile, readdir, rename, rm, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { AgentProfile } from "./profile_types.ts";
import { mapConcurrent } from "./subagent_concurrency.ts";
import { withRunLock } from "./subagent_lock.ts";
import { addUsage, emptyUsage, isTerminalAgent, isTerminalTask, validateRunPurpose, type AgentLineage, type AgentRecord, type AgentSnapshot, type AgentStatus, type Intervention, type NativeCapabilities, type TaskCancelRequest, type TaskRequest, type TaskResult, type TaskSnapshot, type TaskStatus, type UsageClaim } from "./subagent_types.ts";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;
export interface AgentPaths { directory: string; agent: string; status: string; events: string; session: string; tasks: string }
export interface TaskPaths { directory: string; request: string; status: string; result: string; cancel: string; usageClaim: string }
export function assertId(id: string, label = "ID"): void { if (!UUID.test(id)) throw new Error(`Invalid ${label}: ${id}`); }
export function agentPaths(stateRoot: string, agentId: string): AgentPaths { assertId(agentId, "agent ID"); const directory = join(stateRoot, "agents", agentId); return { directory, agent: join(directory, "agent.json"), status: join(directory, "status.json"), events: join(directory, "events.jsonl"), session: join(directory, "session"), tasks: join(directory, "tasks") }; }
export function taskPaths(stateRoot: string, agentId: string, taskId: string): TaskPaths { assertId(taskId, "task ID"); const directory = join(agentPaths(stateRoot, agentId).tasks, taskId); return { directory, request: join(directory, "request.json"), status: join(directory, "status.json"), result: join(directory, "result.json"), cancel: join(directory, "cancel.json"), usageClaim: join(directory, "usage-claim.json") }; }
async function atomicJson(path: string, value: unknown): Promise<void> { const temporary = `${path}.${process.pid}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 }); await rename(temporary, path); await chmod(path, 0o600); }
export async function readJson<T>(path: string): Promise<T> { return JSON.parse(await readFile(path, "utf8")) as T; }
export async function prepareAgent(stateRoot: string, input: { profile: string; purpose: string; harness: string; cwd: string; profileSnapshot: AgentProfile; lineage: AgentLineage; capabilities: NativeCapabilities }): Promise<{ agentId: string; paths: AgentPaths }> { void input; const agentId = randomUUID(); const paths = agentPaths(stateRoot, agentId); await mkdir(paths.session, { recursive: true, mode: 0o700 }); await mkdir(paths.tasks, { recursive: true, mode: 0o700 }); await writeFile(paths.events, "", { mode: 0o600 }); const placeholder: AgentStatus = { schemaVersion: 1, agentId, state: "creating", bridgeReady: false, agentUsage: emptyUsage(), accountedTaskIds: [], updatedAt: new Date().toISOString() }; await atomicJson(paths.status, placeholder); return { agentId, paths }; }
export async function publishAgent(paths: AgentPaths, input: Omit<AgentRecord, "schemaVersion" | "createdAt">): Promise<AgentRecord> { const agent: AgentRecord = { schemaVersion: 1, createdAt: new Date().toISOString(), ...input }; await atomicJson(paths.agent, agent); return agent; }
export async function removePreparedAgent(paths: AgentPaths): Promise<void> { await rm(paths.directory, { recursive: true, force: true }); }
export async function readAgentStatus(paths: AgentPaths): Promise<AgentStatus> { return readJson<AgentStatus>(paths.status); }
export async function patchAgentStatus(paths: AgentPaths, patch: Partial<AgentStatus>): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next: AgentStatus = { ...current, ...patch, schemaVersion: 1, agentId: current.agentId, updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function markBridgeReady(paths: AgentPaths): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next = { ...current, bridgeReady: true, state: current.state === "creating" ? "idle" as const : current.state, updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function recordChildSessionIdentity(paths: AgentPaths, childSessionId: string, childSessionFile: string | undefined): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next: AgentStatus = { ...current, childSessionId, ...(childSessionFile ? { childSessionFile } : {}), updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function markAgentStoppingWithDisposition(paths: AgentPaths): Promise<{ status: AgentStatus; initiated: boolean }> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); if (current.state === "stopped" || current.state === "failed" || current.state === "stopping") return { status: current, initiated: false }; const next: AgentStatus = { ...current, state: "stopping", updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return { status: next, initiated: true }; }); }
export async function markAgentStopping(paths: AgentPaths): Promise<AgentStatus> { return (await markAgentStoppingWithDisposition(paths)).status; }
export async function markAgentCleanupPending(paths: AgentPaths): Promise<AgentStatus> { return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); const next: AgentStatus = { ...current, state: "stopping", updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function restoreAgentAfterStopFailure(stateRoot: string, agentId: string): Promise<AgentStatus> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const current = await readAgentStatus(paths); if (current.state !== "stopping") return current; let activeTaskId = current.activeTaskId; if (activeTaskId) { const task = await readTask(stateRoot, agentId, activeTaskId); if (isTerminalTask(task.status.state)) activeTaskId = undefined; } const next: AgentStatus = { ...current, state: activeTaskId ? "busy" : "idle", activeTaskId, updatedAt: new Date().toISOString() }; await atomicJson(paths.status, next); return next; }); }
export async function createTask(stateRoot: string, agentId: string, purpose: string, prompt: string): Promise<TaskSnapshot> { if (!prompt.trim()) throw new Error("Subagent prompt must not be empty"); const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const agent = await readJson<AgentRecord>(paths.agent); const status = await readAgentStatus(paths); if (agent.agentId !== agentId) throw new Error("Agent metadata mismatch"); if (status.state !== "idle" && status.state !== "creating") throw new Error(`Agent ${agentId} is ${status.state}${status.activeTaskId ? `; active task ${status.activeTaskId}` : ""}`); const taskId = randomUUID(); const task = taskPaths(stateRoot, agentId, taskId); await mkdir(task.directory, { recursive: true, mode: 0o700 }); const createdAt = new Date().toISOString(); const request: TaskRequest = { schemaVersion: 1, agentId, taskId, purpose: validateRunPurpose(purpose), prompt, createdAt }; const taskStatus: TaskStatus = { schemaVersion: 1, agentId, taskId, state: "created", createdAt }; await atomicJson(task.request, request); await atomicJson(task.status, taskStatus); await atomicJson(paths.status, { ...status, state: "busy", activeTaskId: taskId, latestTaskId: taskId, updatedAt: createdAt }); await appendEventUnlocked(paths, "task_created", { taskId, purpose: request.purpose }).catch(() => {}); return { request, status: taskStatus, result: null, interventions: [], claimed: false, directory: task.directory }; }); }
export async function readTask(stateRoot: string, agentId: string, taskId: string): Promise<TaskSnapshot> { const paths = taskPaths(stateRoot, agentId, taskId); const agent = agentPaths(stateRoot, agentId); const [request, status, interventions] = await Promise.all([readJson<TaskRequest>(paths.request), readJson<TaskStatus>(paths.status), readInterventions(agent, taskId)]); const result = await readJson<TaskResult>(paths.result).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? null : Promise.reject(error)); const claimed = await readFile(paths.usageClaim).then(() => true).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? false : Promise.reject(error)); return { request, status, result, interventions, claimed, directory: paths.directory }; }
export async function readAgentSnapshot(stateRoot: string, agentId: string, taskId?: string): Promise<AgentSnapshot> { const paths = agentPaths(stateRoot, agentId); const [agent, status] = await Promise.all([readJson<AgentRecord>(paths.agent), readAgentStatus(paths)]); const selected = taskId ?? status.activeTaskId ?? status.latestTaskId; return { agent, status, ...(selected ? { task: await readTask(stateRoot, agentId, selected) } : {}) }; }
export async function claimPendingTask(stateRoot: string, agentId: string): Promise<TaskSnapshot | null> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const status = await readAgentStatus(paths); if (!status.activeTaskId || status.state !== "busy") return null; const task = await readTask(stateRoot, agentId, status.activeTaskId); if (task.status.state !== "created") return null; const cancellation = await readTaskCancellation(stateRoot, agentId, task.request.taskId); if (cancellation) { await finishTaskUnlocked(stateRoot, paths, agentId, task.request.taskId, { outcome: "stopped", error: cancellation.reason }); return null; } const startedAt = new Date().toISOString(); await atomicJson(taskPaths(stateRoot, agentId, task.request.taskId).status, { ...task.status, state: "running", startedAt }); await appendEventUnlocked(paths, "task_started", { taskId: task.request.taskId }).catch(() => {}); return { ...task, status: { ...task.status, state: "running", startedAt } }; }); }
export async function readTaskCancellation(stateRoot: string, agentId: string, taskId: string): Promise<TaskCancelRequest | undefined> { return readJson<TaskCancelRequest>(taskPaths(stateRoot, agentId, taskId).cancel).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); }
export async function requestTaskCancellation(stateRoot: string, agentId: string, taskId: string, reason: string): Promise<{ request?: TaskCancelRequest; created: boolean; snapshot: AgentSnapshot }> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const task = await readTask(stateRoot, agentId, taskId); if (isTerminalTask(task.status.state)) return { created: false, snapshot: await readAgentSnapshot(stateRoot, agentId, taskId) }; let request = await readTaskCancellation(stateRoot, agentId, taskId); const created = request === undefined; if (!request) { request = { schemaVersion: 1, agentId, taskId, requestedAt: new Date().toISOString(), reason }; await atomicJson(taskPaths(stateRoot, agentId, taskId).cancel, request); await appendEventUnlocked(paths, "task_cancel_requested", { taskId, reason }).catch(() => {}); } if (task.status.state === "created") await finishTaskUnlocked(stateRoot, paths, agentId, taskId, { outcome: "stopped", error: request.reason }); return { request, created, snapshot: await readAgentSnapshot(stateRoot, agentId, taskId) }; }); }
export async function recordIntervention(stateRoot: string, agentId: string, input: Omit<Intervention, "sequence" | "timestamp">): Promise<Intervention> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, async () => { const events = await readEvents(paths); const intervention: Intervention = { sequence: events.reduce((n, event) => Math.max(n, Number(event.sequence) || 0), 0) + 1, timestamp: new Date().toISOString(), ...input }; await appendFile(paths.events, `${JSON.stringify({ type: "intervention", ...intervention })}\n`, { mode: 0o600 }); return intervention; }); }
export async function readInterventions(paths: AgentPaths, taskId?: string): Promise<Intervention[]> { return (await readEvents(paths)).filter(event => event.type === "intervention" && (taskId === undefined ? event.taskId === undefined : event.taskId === taskId)) as unknown as Intervention[]; }
async function readEvents(paths: AgentPaths): Promise<Array<Record<string, unknown>>> { const text = await readFile(paths.events, "utf8"); return text.split("\n").filter(Boolean).flatMap(line => { try { return [JSON.parse(line) as Record<string, unknown>]; } catch { return []; } }); }
async function appendEventUnlocked(paths: AgentPaths, type: string, data: Record<string, unknown>): Promise<void> { const events = await readEvents(paths); await appendFile(paths.events, `${JSON.stringify({ schemaVersion: 1, sequence: events.length + 1, timestamp: new Date().toISOString(), type, ...data })}\n`, { mode: 0o600 }); }
export async function appendAgentEvent(stateRoot: string, agentId: string, type: string, data: Record<string, unknown>): Promise<void> { const paths = agentPaths(stateRoot, agentId); await withRunLock(paths.directory, () => appendEventUnlocked(paths, type, data)); }
export async function recordIdleUsage(stateRoot: string, agentId: string, usage: TaskResult["usage"]): Promise<void> { const paths = agentPaths(stateRoot, agentId); await withRunLock(paths.directory, async () => { const status = await readAgentStatus(paths); const agentUsage = structuredClone(status.agentUsage ?? emptyUsage()); addUsage(agentUsage, usage); await atomicJson(paths.status, { ...status, agentUsage, updatedAt: new Date().toISOString() }); await appendEventUnlocked(paths, "idle_usage", { usage }); }); }
async function finishTaskUnlocked(stateRoot: string, paths: AgentPaths, agentId: string, taskId: string, input: { outcome: TaskResult["outcome"]; output?: string; usage?: TaskResult["usage"]; turns?: number; error?: string }): Promise<TaskResult> { const task = await readTask(stateRoot, agentId, taskId); const status = await readAgentStatus(paths); const taskTerminal = isTerminalTask(task.status.state); const cancellation = taskTerminal ? undefined : await readTaskCancellation(stateRoot, agentId, taskId); const forcedOutcome = (status.state === "stopping" || cancellation) && !taskTerminal ? "stopped" : input.outcome; const replaceProvisional = !taskTerminal && task.result !== null && task.result.outcome !== forcedOutcome; const now = new Date().toISOString(); const error = forcedOutcome === "stopped" && !taskTerminal ? input.error ?? cancellation?.reason ?? "Stopped while task completion was settling" : input.error; const base = task.result ?? { schemaVersion: 1, agentId, taskId, outcome: forcedOutcome, output: input.output ?? "", usage: input.usage ?? emptyUsage(), turns: input.turns ?? 0, interventions: await readInterventions(paths, taskId), startedAt: task.status.startedAt ?? task.status.createdAt, finishedAt: now }; const result: TaskResult = replaceProvisional ? { ...base, outcome: forcedOutcome, finishedAt: now, ...(error ? { error } : {}) } : { ...base, ...(base.error || !error ? {} : { error }) }; if (!task.result || replaceProvisional) await atomicJson(taskPaths(stateRoot, agentId, taskId).result, result);
    const accountedTaskIds = [...(status.accountedTaskIds ?? [])]; const agentUsage = structuredClone(status.agentUsage ?? emptyUsage()); if (!accountedTaskIds.includes(taskId)) { addUsage(agentUsage, result.usage); accountedTaskIds.push(taskId); } await atomicJson(paths.status, { ...status, agentUsage, accountedTaskIds, updatedAt: now });
    if (!taskTerminal || task.status.state !== result.outcome) await atomicJson(taskPaths(stateRoot, agentId, taskId).status, { ...task.status, state: result.outcome, finishedAt: result.finishedAt, ...(result.error ? { error: result.error } : {}) }); const completesActiveTask = status.activeTaskId === taskId; const state = status.state === "stopping" ? "stopping" : status.state === "stopped" || status.state === "failed" ? status.state : completesActiveTask ? "idle" : status.state; await atomicJson(paths.status, { ...status, state, activeTaskId: completesActiveTask ? undefined : status.activeTaskId, agentUsage, accountedTaskIds, updatedAt: now }); if (!taskTerminal || replaceProvisional || !task.result) await appendEventUnlocked(paths, "task_finished", { taskId, outcome: result.outcome }).catch(() => {}); return result; }
export async function finishTask(stateRoot: string, agentId: string, taskId: string, input: { outcome: TaskResult["outcome"]; output?: string; usage?: TaskResult["usage"]; turns?: number; error?: string }): Promise<TaskResult> { const paths = agentPaths(stateRoot, agentId); return withRunLock(paths.directory, () => finishTaskUnlocked(stateRoot, paths, agentId, taskId, input)); }
export async function failAgent(stateRoot: string, agentId: string, reason: string, stopped = false, options: { overrideTerminalReason?: boolean } = {}): Promise<void> { const paths = agentPaths(stateRoot, agentId); await withRunLock(paths.directory, async () => { const status = await readAgentStatus(paths); if (isTerminalAgent(status.state) && !options.overrideTerminalReason) return; if (status.activeTaskId) await finishTaskUnlocked(stateRoot, paths, agentId, status.activeTaskId, { outcome: stopped ? "stopped" : "failed", error: reason }); const current = await readAgentStatus(paths); if (isTerminalAgent(current.state) && !options.overrideTerminalReason) return; await atomicJson(paths.status, { ...current, state: stopped ? "stopped" : "failed", activeTaskId: undefined, exitReason: reason, updatedAt: new Date().toISOString() }); }); }
export async function findTaskAgent(stateRoot: string, taskId: string, originSessionId: string): Promise<string> { assertId(taskId, "task ID"); for (const snapshot of await listOriginAgents(stateRoot, originSessionId)) { try { await readTask(stateRoot, snapshot.agent.agentId, taskId); return snapshot.agent.agentId; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; } } throw new Error(`Task ${taskId} was not found in this origin session`); }
export async function listOriginAgents(stateRoot: string, originSessionId: string): Promise<AgentSnapshot[]> {
    const root = join(stateRoot, "agents");
    const entries = await readdir(root).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? [] : Promise.reject(error));
    const matchingIds = (await mapConcurrent(entries.filter(id => UUID.test(id)), 8, async id => {
        try {
            const record = await readJson<AgentRecord>(agentPaths(stateRoot, id).agent);
            return record.originSessionId === originSessionId ? id : undefined;
        } catch { return undefined; }
    })).filter((id): id is string => id !== undefined);
    const values = (await mapConcurrent(matchingIds, 8, async id => {
        try { return await readAgentSnapshot(stateRoot, id); }
        catch { return undefined; }
    })).filter((snapshot): snapshot is AgentSnapshot => snapshot !== undefined);
    return values.sort((a, b) => b.agent.createdAt.localeCompare(a.agent.createdAt));
}
function persistedClaimTaskIds(text: string): Set<string> { const ids = new Set<string>(); for (const line of text.split("\n")) { if (!line.trim()) continue; try { const entry = JSON.parse(line) as Record<string, unknown>; const message = entry.type === "message" && entry.message && typeof entry.message === "object" ? entry.message as Record<string, unknown> : undefined; const details = message?.role === "toolResult" && message.details && typeof message.details === "object" ? message.details as Record<string, unknown> : undefined; const accounting = details?.accounting && typeof details.accounting === "object" ? details.accounting as Record<string, unknown> : undefined; if (Array.isArray(accounting?.claimedTaskIds)) for (const id of accounting.claimedTaskIds) if (typeof id === "string") ids.add(id); } catch { /* tolerate a partially written final line */ } } return ids; }
export async function reconcileOriginUsageClaims(stateRoot: string, originSessionId: string, originSessionFile?: string): Promise<number> { if (!originSessionFile) return 0; const persisted = persistedClaimTaskIds(await readFile(originSessionFile, "utf8").catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? "" : Promise.reject(error))); let recovered = 0; for (const snapshot of await listOriginAgents(stateRoot, originSessionId)) { const paths = agentPaths(stateRoot, snapshot.agent.agentId); await withRunLock(paths.directory, async () => { const entries = await readdir(paths.tasks).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? [] : Promise.reject(error)); for (const taskId of entries) { if (!UUID.test(taskId) || persisted.has(taskId)) continue; const claimPath = taskPaths(stateRoot, snapshot.agent.agentId, taskId).usageClaim; const claim = await readJson<UsageClaim>(claimPath).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); if (claim?.parentSessionFile === originSessionFile) { await unlink(claimPath); recovered += 1; } } }); } return recovered; }
export async function claimTaskUsage(stateRoot: string, agentId: string, taskId: string, originSessionId: string, originSessionFile: string | undefined, toolCallId: string, toolName: UsageClaim["toolName"]): Promise<{ created: boolean; claim: UsageClaim; result: TaskResult }> { const task = await readTask(stateRoot, agentId, taskId); const agent = await readJson<AgentRecord>(agentPaths(stateRoot, agentId).agent); if (agent.originSessionId !== originSessionId) throw new Error(`Agent ${agentId} belongs to a different origin session`); if (!task.result || !isTerminalTask(task.status.state)) throw new Error(`Task ${taskId} is not terminal`); const claim: UsageClaim = { schemaVersion: 1, originSessionId, ...(originSessionFile ? { parentSessionFile: originSessionFile } : {}), toolCallId, toolName, agentId, taskId, claimedAt: new Date().toISOString() }; const path = taskPaths(stateRoot, agentId, taskId).usageClaim; const temporary = `${path}.${randomUUID()}.tmp`; const handle = await open(temporary, "wx", 0o600); await handle.writeFile(`${JSON.stringify(claim)}\n`); await handle.close(); try { await link(temporary, path); return { created: true, claim, result: task.result }; } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; return { created: false, claim: await readJson<UsageClaim>(path), result: task.result }; } finally { await unlink(temporary).catch(() => {}); } }
