vim.loader.enable()
vim.g.mapleader = " "
vim.keymap.set("i", "jj", [[<ESC>]], { silent = true })
-- vim.keymap.set("t", "jj", [[<C-\><C-n>]], { silent = true })
vim.keymap.set({ "n", "x", "o" }, "<Space>j", "<S-g>")
vim.keymap.set({ "n", "x", "o" }, "<Space>k", "gg")
vim.keymap.set("n", "<S-h>", vim.cmd["bprev"], { silent = true })
vim.keymap.set("n", "<S-l>", vim.cmd["bnext"], { silent = true })
vim.keymap.set("n", "q", [[<Nop>]])
vim.keymap.set("n", "r", "<C-r>")
vim.keymap.set("n", "<C-r>", "r")
vim.keymap.set("n", "<S-Y>", [[y$]], { silent = true })
vim.keymap.set("n", "x", [["_d]], { silent = true })
vim.keymap.set("n", "X", [["_D]], { silent = true })
vim.keymap.set("n", "<Space>r", 'yiw:%s/<C-r><C-r>"//g<Left><Left>', { silent = true })
vim.keymap.set("x", "<Space>r", 'y:%s/<C-r><C-r>"//g<Left><Left>', { silent = true })
vim.keymap.set("n", "<S-r>", vim.lsp.buf.rename)
-- emacs keybind for insert mode
vim.keymap.set("i", "<C-a>", "<C-o>^", { silent = true })
vim.keymap.set("i", "<C-e>", "<C-o>$", { silent = true })
vim.keymap.set("i", "<C-b>", "<Left>", { silent = true })
vim.keymap.set("i", "<C-f>", "<Right>", { silent = true })
vim.keymap.set({ "n", "x", "o" }, "<Space>h", [[^]], { silent = true })
vim.keymap.set({ "n", "x", "o" }, "<Space>l", [[$]], { silent = true })
vim.keymap.set({ "n", "x" }, "j", function()
  return "gj"
end, { expr = true, silent = true })
vim.keymap.set({ "n", "x" }, "k", function()
  return "gk"
end, { expr = true, silent = true })
vim.keymap.set({ "n", "x", "o" }, "M", [[%]], { silent = true })
vim.keymap.set({ "n" }, "<Space>w", vim.cmd["w"], { silent = true })
vim.keymap.set("x", "x", [["_x]], { silent = true })
vim.keymap.set("o", "x", [[d]], { silent = true })
vim.keymap.set("x", "y", [[mzy`z]], { silent = true })
-- vim.keymap.set("x", "d", [[mzd`z]], { silent = true })
vim.keymap.set("x", "gc", "mz:normal gcc<CR>`z", { silent = true })
for _, quote in ipairs({ [["]], [[']], [[`]] }) do
  vim.keymap.set({ "x", "o" }, "a" .. quote, "2i" .. quote)
end

vim.keymap.set("i", "<Left>", "<-", { silent = true })
vim.keymap.set("i", "<Right>", "->", { silent = true })
vim.keymap.set("i", "<S-Left>", "<=", { silent = true })
vim.keymap.set("i", "<S-Right>", "=>", { silent = true })
