import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import type { StopReason, Usage } from "@earendil-works/pi-ai";
import { getAgentDir, SettingsManager, type ExtensionAPI, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import { onResolvedAgent } from "./utilities/agent_events.ts";
import { launchEnvelopeDigest, validateLaunchEnvelope } from "./utilities/agent_types.ts";
import { availableContext, publishAgentActivity, type AgentActivityPhase, type AgentCompactionReason } from "./utilities/orchestration_activity.ts";
import { addUsage, emptyUsage, type TerminalTaskState } from "./utilities/orchestration_types.ts";
import { bindAgentRuntime, readCurrentPiRuntimeGeneration, unbindAgentRuntime } from "./utilities/orchestration_runtime.ts";
import { claimPendingTask, failAgent, finishTask, markBridgeReady, readAgentStatus, readTaskCancellation, recordChildSessionIdentity, recordIdleUsage, recordIntervention } from "./utilities/orchestration_store.ts";

function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function usage(value: unknown): Partial<Usage> | undefined { const item = record(value); return ["input", "output", "cacheRead", "cacheWrite", "totalTokens", "reasoning", "cacheWrite1h"].some(key => typeof item[key] === "number") || item.cost && typeof item.cost === "object" ? item as unknown as Partial<Usage> : undefined; }
function text(value: unknown): string { const message = record(value); if (!Array.isArray(message.content)) return ""; return message.content.map(part => { const item = record(part); return item.type === "text" && typeof item.text === "string" ? item.text : ""; }).join(""); }
function imageTypes(images: unknown): string[] { if (!Array.isArray(images)) return []; return images.map(image => record(image).mimeType).filter((type): type is string => typeof type === "string"); }
function terminal(stopReason: StopReason | undefined, errorMessage: string | undefined): { outcome: TerminalTaskState; error?: string } { if (stopReason === "aborted") return { outcome: "stopped", error: errorMessage ?? "Assistant turn was aborted" }; if (stopReason === "error") return { outcome: "failed", error: errorMessage ?? "Assistant turn failed" }; if (stopReason === "length") return { outcome: "failed", error: errorMessage ?? "Assistant turn reached the token limit" }; if (stopReason === "toolUse") return { outcome: "failed", error: errorMessage ?? "Assistant settled while awaiting tool execution" }; return { outcome: "succeeded" }; }

export interface MeshChildBridgeDependencies { finishTask?: typeof finishTask; failAgent?: typeof failAgent; markBridgeReady?: typeof markBridgeReady; recordChildSessionIdentity?: typeof recordChildSessionIdentity; publishAgentActivity?: typeof publishAgentActivity; resolveCompactionReserveTokens?: (ctx: ExtensionContext) => number | undefined; standaloneRuntimeBinding?: boolean; retryIntervalMs?: number; activityHeartbeatMs?: number; contextHeadroomTokens?: number; deliveryAckTimeoutMs?: number; completionPersistenceTimeoutMs?: number; publicationTimeoutMs?: number; publicationRetryMs?: number; sleep?: (milliseconds: number) => Promise<void>; now?: () => number; setInterval?: (callback: () => void | Promise<void>, intervalMs: number) => unknown; clearInterval?: (timer: unknown) => void; setTimeout?: (callback: () => void, timeoutMs: number) => unknown; clearTimeout?: (timer: unknown) => void }
function expectedResolvedAgent(env: NodeJS.ProcessEnv) { const path = env.PI_AGENT_RESOLVED_AGENT; return path ? validateLaunchEnvelope(JSON.parse(readFileSync(path, "utf8"))) : undefined; }
function missing(error: unknown): boolean { return (error as NodeJS.ErrnoException)?.code === "ENOENT"; }
async function markReadyAfterPublication(stateRoot: string, meshId: string, agentId: string, digest: string, runtimeId: string, dependencies: MeshChildBridgeDependencies): Promise<void> { const now = dependencies.now ?? Date.now; const deadline = now() + (dependencies.publicationTimeoutMs ?? 5000); const wait = dependencies.sleep ?? (milliseconds => new Promise(resolve => setTimeout(resolve, milliseconds))); while (true) try { await (dependencies.markBridgeReady ?? markBridgeReady)(stateRoot, meshId, agentId, digest, runtimeId); return; } catch (error) { if (!missing(error)) throw error; if (now() >= deadline) throw new Error("Timed out waiting for mesh agent publication"); await wait(dependencies.publicationRetryMs ?? 25); } }

export function registerMeshChildBridge(pi: ExtensionAPI, env: NodeJS.ProcessEnv = process.env, dependencies: MeshChildBridgeDependencies = {}): boolean {
    const meshId = env.PI_MESH_ID; const agentId = env.PI_MESH_AGENT_ID; const directory = env.PI_MESH_AGENT_DIR; if (!meshId || !agentId || !directory) return false; const stateRoot = directory.replace(/\/meshes\/[^/]+\/agents\/[^/]+$/u, "");
    const hasResolvedAgent = Boolean(env.PI_AGENT_RESOLVED_AGENT); let expectedEnvelope: ReturnType<typeof expectedResolvedAgent>; let invalid = false; let activatedExpected = false; if (hasResolvedAgent) try { expectedEnvelope = expectedResolvedAgent(env); } catch { invalid = true; }
    const promptOnly = () => expectedEnvelope?.selfRole.contextPolicy === "prompt-only";
    const enforcePromptOnlyTools = () => { if (promptOnly() && pi.getActiveTools().length) pi.setActiveTools([]); };
    enforcePromptOnlyTools();
    onResolvedAgent(pi, event => { if (expectedEnvelope && launchEnvelopeDigest(event.envelope) === launchEnvelopeDigest(expectedEnvelope)) activatedExpected = true; });
    let activeTaskId: string | undefined; let taskUsage = emptyUsage(); let turns = 0; let output = ""; let stopReason: StopReason | undefined; let errorMessage: string | undefined; let pumping = false; let completing = false; let settled = true; let pendingCompletion: { taskId: string; input: Parameters<typeof finishTask>[3]; deadline: number } | undefined; let awaitingDelivery: { taskId: string; prompt: string; deadline: number } | undefined; let timer: unknown; let bridgeContext: ExtensionContext | undefined; let cancellationAbortedTaskId: string | undefined; let shutdownAfterStoreFailure = false;
    let runtimeId: string = randomUUID(); let activityPhase: AgentActivityPhase = "starting"; let phaseSince = new Date((dependencies.now ?? Date.now)()).toISOString(); let compactionReason: AgentCompactionReason | undefined; let awaitingPostCompactionSettlement = false; let reserveTokens: number | undefined; let lastHeartbeat = Number.NEGATIVE_INFINITY; let compactionObservation = 0;
    const publishActivity = async (phase = activityPhase, heartbeat = false) => { const ctx = bridgeContext; if (!ctx) return; const now = (dependencies.now ?? Date.now)(); if (heartbeat && now - lastHeartbeat < (dependencies.activityHeartbeatMs ?? 2000)) return; if (phase !== activityPhase) { activityPhase = phase; phaseSince = new Date(now).toISOString(); } lastHeartbeat = now; const observedAt = new Date(now).toISOString(); const usage = ctx.getContextUsage?.(); const context = availableContext(usage?.tokens, usage?.contextWindow, reserveTokens, dependencies.contextHeadroomTokens); await (dependencies.publishAgentActivity ?? publishAgentActivity)(stateRoot, meshId, agentId, { runtimeId, phase: activityPhase, acceptingTask: activityPhase === "idle", pendingMessages: ctx.hasPendingMessages?.() ?? false, phaseSince, observedAt, heartbeatAt: observedAt, ...(activityPhase === "compacting" && compactionReason ? { compactionReason } : {}), context }); };
    const queueCompletion = (taskId: string, input: Parameters<typeof finishTask>[3]) => { pendingCompletion = { taskId, input, deadline: (dependencies.now ?? Date.now)() + (dependencies.completionPersistenceTimeoutMs ?? 30_000) }; };
    const persistCompletion = async () => { if (!pendingCompletion || completing) return; completing = true; const pending = pendingCompletion; const now = dependencies.now ?? Date.now; const scheduleTimeout = dependencies.setTimeout ?? ((callback: () => void, timeoutMs: number) => globalThis.setTimeout(callback, timeoutMs)); let deadlineTimer: unknown; let timedOut = false; try { await Promise.race([(dependencies.finishTask ?? finishTask)(stateRoot, meshId, pending.taskId, pending.input, runtimeId), new Promise<never>((_resolve, reject) => { deadlineTimer = scheduleTimeout(() => { timedOut = true; reject(new Error("Timed out persisting mesh task completion")); }, Math.max(0, pending.deadline - now())); })]); if (pendingCompletion === pending) pendingCompletion = undefined; if (activeTaskId === pending.taskId) activeTaskId = undefined; } catch (error) { if (!timedOut && now() < pending.deadline) throw error; if (!shutdownAfterStoreFailure) { shutdownAfterStoreFailure = true; bridgeContext?.shutdown(); } } finally { if (deadlineTimer !== undefined) (dependencies.clearTimeout ?? (value => globalThis.clearTimeout(value as NodeJS.Timeout)))(deadlineTimer); completing = false; } };
    const pump = async () => { if (pumping || pendingCompletion || activeTaskId || !settled) return; pumping = true; try { const task = await claimPendingTask(stateRoot, meshId, agentId, runtimeId); if (!task) return; activeTaskId = task.request.taskId; cancellationAbortedTaskId = undefined; taskUsage = emptyUsage(); turns = 0; output = ""; stopReason = undefined; errorMessage = undefined; settled = false; awaitingDelivery = { taskId: task.request.taskId, prompt: task.request.prompt, deadline: (dependencies.now ?? Date.now)() + (dependencies.deliveryAckTimeoutMs ?? 5000) }; try { pi.sendUserMessage(task.request.prompt); } catch (error) { awaitingDelivery = undefined; settled = true; queueCompletion(task.request.taskId, { outcome: "failed", error: `Could not deliver task: ${error instanceof Error ? error.message : String(error)}` }); await persistCompletion(); } } finally { pumping = false; } };
    const tick = async () => { if (activeTaskId && cancellationAbortedTaskId !== activeTaskId) { const cancellation = await readTaskCancellation(stateRoot, meshId, activeTaskId); if (cancellation) { cancellationAbortedTaskId = activeTaskId; if (awaitingDelivery?.taskId === activeTaskId) { awaitingDelivery = undefined; settled = true; queueCompletion(activeTaskId, { outcome: "stopped", output, usage: taskUsage, turns, error: cancellation.reason }); } else bridgeContext?.abort(); } } if (awaitingDelivery && (dependencies.now ?? Date.now)() >= awaitingDelivery.deadline) { const taskId = awaitingDelivery.taskId; awaitingDelivery = undefined; settled = true; queueCompletion(taskId, { outcome: "failed", error: "Could not deliver task: child Pi did not accept the extension message" }); } if (pendingCompletion) await persistCompletion(); const ctx = bridgeContext; if (awaitingPostCompactionSettlement && settled && !activeTaskId && ctx?.isIdle() && !(ctx.hasPendingMessages?.() ?? false)) { awaitingPostCompactionSettlement = false; compactionReason = undefined; await publishActivity("idle"); } if (!pendingCompletion) await pump(); await publishActivity(activityPhase, true); };
    pi.on("session_start", async (_event, ctx) => { bridgeContext = ctx; enforcePromptOnlyTools(); try { const childSessionId = ctx?.sessionManager.getSessionId() ?? env.PI_SESSION_ID; const childSessionFile = ctx?.sessionManager.getSessionFile() ?? env.PI_SESSION_FILE; if (childSessionId && childSessionFile) { let binding; try { binding = await readCurrentPiRuntimeGeneration(stateRoot, meshId, agentId, childSessionId, childSessionFile); } catch (error) { if (!dependencies.standaloneRuntimeBinding) throw error; binding = await bindAgentRuntime(stateRoot, meshId, agentId, { runtimeId, kind: "pi", sessionId: childSessionId, sessionFile: childSessionFile }); } runtimeId = binding.runtimeId; await (dependencies.recordChildSessionIdentity ?? recordChildSessionIdentity)(stateRoot, meshId, agentId, childSessionId, childSessionFile, runtimeId); } else throw new Error("Mesh child session requires durable session identity"); if (hasResolvedAgent && (invalid || !activatedExpected)) throw new Error(invalid || !expectedEnvelope ? "Mesh launch envelope is invalid" : `Child role ${expectedEnvelope.role} did not resolve from its launch envelope`); try { reserveTokens = dependencies.resolveCompactionReserveTokens?.(ctx) ?? SettingsManager.create(ctx.cwd ?? process.cwd(), getAgentDir()).getCompactionReserveTokens(); } catch { reserveTokens = undefined; } await publishActivity("starting"); await markReadyAfterPublication(stateRoot, meshId, agentId, launchEnvelopeDigest(expectedEnvelope!), runtimeId, dependencies); await publishActivity("idle"); const schedule = dependencies.setInterval ?? ((callback, intervalMs) => setInterval(() => { void callback(); }, intervalMs)); timer = schedule(() => tick().catch(() => {}), dependencies.retryIntervalMs ?? 100); await tick(); } catch (error) { await (dependencies.failAgent ?? failAgent)(stateRoot, meshId, agentId, error instanceof Error ? error.message : String(error), false, { expectedRuntimeId: runtimeId }).catch(() => {}); shutdownAfterStoreFailure = true; ctx?.shutdown(); } });
    pi.on("context", () => { enforcePromptOnlyTools(); });
    pi.on("before_agent_start", async event => { enforcePromptOnlyTools(); if (awaitingDelivery?.prompt === event.prompt) awaitingDelivery = undefined; await publishActivity("running"); }); pi.on("agent_start", async () => { awaitingDelivery = undefined; settled = false; await publishActivity("running"); });
    pi.on("session_before_compact", async event => { awaitingPostCompactionSettlement = false; compactionReason = event.reason; const observation = ++compactionObservation; await publishActivity("compacting"); event.signal.addEventListener("abort", () => { if (compactionObservation === observation && activityPhase === "compacting") { awaitingPostCompactionSettlement = false; void publishActivity(activeTaskId || !settled ? "running" : "idle").catch(() => {}); } }, { once: true }); });
    pi.on("session_compact", async event => { if (event.willRetry || activeTaskId || !settled) { awaitingPostCompactionSettlement = false; compactionReason = undefined; await publishActivity("running"); } else awaitingPostCompactionSettlement = true; });
    pi.on("input", async event => { if (event.source !== "interactive") return { action: "continue" as const }; settled = false; const mode = event.streamingBehavior ?? (activeTaskId ? "followUp" : "idle"); await recordIntervention(stateRoot, meshId, agentId, { taskId: activeTaskId, text: event.text, deliveryMode: mode, images: imageTypes(event.images) }, runtimeId); return { action: "continue" as const }; });
    pi.on("message_end", async event => { const message = record(event.message); if (message.role === "assistant") { if (activeTaskId) { addUsage(taskUsage, usage(message.usage)); turns += 1; output = text(message); stopReason = typeof message.stopReason === "string" ? message.stopReason as StopReason : undefined; errorMessage = typeof message.errorMessage === "string" ? message.errorMessage : undefined; } else { const idle = emptyUsage(); addUsage(idle, usage(message.usage)); await recordIdleUsage(stateRoot, meshId, agentId, idle, runtimeId); } } else if (message.role === "toolResult") { if (activeTaskId) addUsage(taskUsage, usage(message.usage)); else { const idle = emptyUsage(); addUsage(idle, usage(message.usage)); await recordIdleUsage(stateRoot, meshId, agentId, idle, runtimeId); } } });
    pi.on("agent_settled", async () => { awaitingDelivery = undefined; awaitingPostCompactionSettlement = false; compactionReason = undefined; settled = true; if (activeTaskId && !pendingCompletion) queueCompletion(activeTaskId, { ...terminal(stopReason, errorMessage), output, usage: taskUsage, turns }); await tick().catch(() => {}); await publishActivity("idle").catch(() => {}); });
    pi.on("session_shutdown", async event => { try { if (timer !== undefined) (dependencies.clearInterval ?? (value => clearInterval(value as NodeJS.Timeout)))(timer); awaitingDelivery = undefined; await publishActivity("offline").catch(() => {}); if (shutdownAfterStoreFailure) return; if (pendingCompletion) await persistCompletion().catch(() => {}); if (event.reason !== "quit") { if (activeTaskId) await finishTask(stateRoot, meshId, activeTaskId, { outcome: "failed", error: `Child Pi session was replaced (${event.reason}) during the task` }, runtimeId); return; } const status = await readAgentStatus({ directory, agent: `${directory}/agent.json`, status: `${directory}/status.json`, stop: `${directory}/stop.json`, events: `${directory}/events.jsonl`, session: `${directory}/session` }, meshId).catch(() => undefined); if (status && status.state !== "stopping" && status.state !== "stopped" && status.state !== "failed") await failAgent(stateRoot, meshId, agentId, "Child Pi session shut down", false, { expectedRuntimeId: runtimeId }); } finally { await unbindAgentRuntime(stateRoot, meshId, agentId, runtimeId).catch(() => {}); } });
    return true;
}
export default registerMeshChildBridge;
