import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { StringEnum, type Usage } from "@earendil-works/pi-ai";
import { defineTool, formatSkillsForPrompt, getAgentDir, type ExtensionAPI, type ExtensionContext, type ToolDefinition } from "@earendil-works/pi-coding-agent";
import { truncateToWidth, wrapTextWithAnsi, type Component } from "@earendil-works/pi-tui";
import { Type, type Static } from "typebox";
import { emitResolvedAgent } from "./utilities/agent_events.ts";
import { buildLaunchEnvelope, projectLaunchEnvelope, validateAgentCatalog, validateLaunchEnvelope, validateOrchestrationConfig, type AgentCatalog, type AgentDefinition, type AgentLaunchEnvelope } from "./utilities/agent_types.ts";
import { createActiveModeBarrier, onActiveMode, type ActiveModeBarrier, type ActiveModeEvent } from "./utilities/mode_events.ts";
import { assertAgentAccepting } from "./utilities/orchestration_activity.ts";
import { resolveHarnessAdapter } from "./utilities/orchestration_harness.ts";
import { cleanupMeshAgents, failStartedMeshAgent, readReconciledAgentSnapshot, recoverPendingAgentStops, stopMeshAgentWithDisposition, stopMeshTask, stopMeshTaskWithDisposition } from "./utilities/orchestration_management.ts";
import { reserveNewAgentCapacityWithPressure, runPeriodicAgentGc } from "./utilities/orchestration_gc.ts";
import { awaitPressureAdmission, failOpenPressureAdmissions, processPressureAdmissions, reconcilePressureAdmissions } from "./utilities/orchestration_admission.ts";
import { projectDebugSnapshot, projectMinimalAgentTask, projectMinimalSubmitResult, projectMinimalWaitResult, sanitizeSnapshot, serializeModelVisibleJson, type AgentToolDetails, type SubmitDetails, type WaitDetails } from "./utilities/orchestration_projection.ts";
import { acknowledgeMeshEvents, bindMeshEndpoint, isLiveMeshEndpointBinding, markMeshEventInjected, pollMeshEvents, registerMeshSignal, registerMeshWatch, resolveRouteEndpoint, setMeshEndpointOffline, type MeshEndpoint } from "./utilities/orchestration_events.ts";
import { attachRootMesh, beginMeshClose, claimTaskUsage, completeMeshClose, createTask, ensurePolicyEpoch, heartbeatRootLease, initializeMesh, prepareAgent, publishAgent, readAgentSnapshot, readMesh, readPolicyEpoch, readTask, reconcileMeshReservations, reconcileMeshState, reconcileMeshUsageClaims, releaseMeshReservation, removePreparedAgent, taskPaths, validateStopReason } from "./utilities/orchestration_store.ts";
import { AgentLaunchCleanupError, inspectAgentTmux, inspectMeshAgentWindow, launchAgentSession, probeTmux, stopAgentSession, type CommandExecutor } from "./utilities/orchestration_tmux.ts";
import { addUsage, emptyUsage, isTerminalAgent, isTerminalTask, type AgentSnapshot, type PolicyEpoch, type SubagentRuntimeConfig, type UsageClaim } from "./utilities/orchestration_types.ts";
import { MeshAgentsPaletteComponent, type MeshPaletteDependencies } from "./utilities/orchestration_palette.ts";
import { MESH_BOOTSTRAP_TOOL_NAME, MESH_PEER_TOOL_NAMES } from "./utilities/orchestration_pi.ts";
import { renderAgentToolResult, renderEnableCall, renderEnableResult, renderGetCall, renderRouteCall, renderRouteResult, renderRunCall, renderRunResult, renderStopCall, renderStopResult, renderSubmitCall, renderSubmitResult, renderWaitCall, renderWaitResult } from "./utilities/orchestration_cards.ts";
import { openPopupView, providePopupView } from "./popup.ts";
import { loadPaletteKeymap } from "./utilities/command_palette_keymap.ts";
import { loadFeatureKeybindings } from "./utilities/extension_keybindings.ts";
import { provideCommandPaletteContribution } from "./utilities/command_palette_contributions.ts";
import { acknowledgeDisplayedTuiNotice, listPendingTuiNotices, type TuiNotice } from "./utilities/orchestration_notices.ts";
import { bindAgentRuntime } from "./utilities/orchestration_runtime.ts";

const CONFIG = join(getAgentDir(), "orchestration.json"); const CATALOG = join(getAgentDir(), "agent-catalog.json");
const ROOT_BINDING = "mesh-root-binding"; const POLICY_BINDING = "mesh-policy-epoch"; const PARENT_STATUS = "mesh-parent-navigation"; const PUMP_STATUS = "mesh-event-pump"; const NOTICE_PUMP_STATUS = "mesh-notice-pump"; const NOTICE_ENTRY = "mesh-tui-notice";
interface RootBinding { schemaVersion: 1; meshId: string }
interface EpochBinding { schemaVersion: 1; meshId: string; mode: string; epochId: string; policyDigest: string }
export interface ActiveCaller { identity: string; meshId: string; epoch: PolicyEpoch; catalog: AgentCatalog; envelope?: AgentLaunchEnvelope; agentId?: string; runtimeId?: string; endpointId: string; sessionFile?: string; error?: string }
export interface OrchestrationDependencies { configPath: string; catalogPath?: string; env: NodeJS.ProcessEnv; exec: CommandExecutor; activeCaller?: () => ActiveCaller | undefined; authorityBarrier?: () => Promise<void>; rootLeaseId?: () => string | undefined; natureHandleWords?: () => readonly string[]; sleep?: (ms: number, signal?: AbortSignal) => Promise<void>; now?: () => number }
export interface OrchestrationRegistrationOptions extends Partial<Pick<OrchestrationDependencies, "configPath" | "catalogPath" | "env">> { setInterval?: (callback: () => void | Promise<void>, delay: number) => unknown; clearInterval?: (timer: unknown) => void }
export async function loadOrchestrationConfig(path: string): Promise<SubagentRuntimeConfig> { try { return validateOrchestrationConfig(JSON.parse(await readFile(path, "utf8"))); } catch (error) { throw new Error(`Cannot read orchestration config ${path}: ${error instanceof Error ? error.message : String(error)}`); } }
export async function loadAgentCatalog(path: string): Promise<AgentCatalog> { try { return validateAgentCatalog(JSON.parse(await readFile(path, "utf8"))); } catch (error) { throw new Error(`Cannot read agent catalog ${path}: ${error instanceof Error ? error.message : String(error)}`); } }
function sleep(ms: number, signal?: AbortSignal): Promise<void> { return new Promise((resolve, reject) => { if (signal?.aborted) return reject(signal.reason); const timer = setTimeout(resolve, ms); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(signal.reason); }, { once: true }); }); }
function active(deps: OrchestrationDependencies): ActiveCaller { const value = deps.activeCaller?.(); if (!value) throw new Error("Mesh unavailable: runtime identity is not attached"); if (value.error) throw new Error(`Mesh unavailable: ${value.error}`); return value; }
async function authorized(deps: OrchestrationDependencies): Promise<ActiveCaller> { await deps.authorityBarrier?.(); return active(deps); }
function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? { ...(value as Record<string, unknown>) } : {}; }
function branchData<T>(ctx: ExtensionContext, customType: string): T | undefined { const entry = [...ctx.sessionManager.getBranch()].reverse().find(item => item.type === "custom" && item.customType === customType) as { data?: unknown } | undefined; return entry?.data as T | undefined; }
function errorText(value: unknown): string { return value instanceof Error ? value.message : typeof value === "string" ? value : JSON.stringify(value) ?? "Unknown error"; }
function roleTargets(caller: ActiveCaller): Record<string, AgentDefinition> { return Object.fromEntries(caller.epoch.roleSet.map(name => [name, caller.epoch.roles[name]!]).filter(([, definition]) => definition)); }
function authorizeRole(caller: ActiveCaller, snapshot: AgentSnapshot, action: string): void { if (!caller.epoch.roleSet.includes(snapshot.agent.agent)) throw new Error(`${caller.identity} epoch is not allowed to ${action} role ${snapshot.agent.agent}`); }
function rejectSelfAgent(caller: ActiveCaller, agentId: string, operation: string): void { if (caller.agentId === agentId) throw new Error(`mesh_${operation} cannot target the calling agent itself (${agentId})`); }
export function tuiNoticeText(notice: TuiNotice, expanded = false): string {
    if (notice.kind === "explicit-stop") {
        const summary = `Agent stopped · ${notice.payload.role} · ${notice.payload.reason}`;
        return expanded ? `${summary}\nagentId: ${notice.payload.agentId}\nsource: ${notice.payload.source}\nnoticeId: ${notice.noticeId}` : summary;
    }
    const summary = `Mesh GC · ${notice.payload.confirmed.length} stopped · ${notice.payload.failedCount} failed · ${notice.payload.pendingCount} pending`;
    const agents = notice.payload.confirmed.map(item => `${item.role} ${item.agentId} · ${item.source} · ${item.reason}`);
    return expanded ? [summary, ...agents, `noticeId: ${notice.noticeId}`].join("\n") : summary;
}
export function renderTuiNotice(notice: TuiNotice, expanded: boolean, theme: ExtensionContext["ui"]["theme"]): Component {
    return { invalidate() {}, render(width: number) { const text = theme.fg(notice.kind === "explicit-stop" ? "warning" : "accent", tuiNoticeText(notice, expanded)); return wrapTextWithAnsi(text, Math.max(1, width)).map(line => truncateToWidth(line, Math.max(1, width), "")); } };
}

const taskParametersFor = (targets: Readonly<Record<string, AgentDefinition>>) => Type.Object({ agent: Type.Optional(StringEnum(Object.keys(targets), { description: Object.entries(targets).map(([name, definition]) => `${name}: ${definition.description}`).join("; ") || "No roles available" })), agentId: Type.Optional(Type.String()), prompt: Type.String({ minLength: 1 }) }, { additionalProperties: false });
type TaskParameters = Static<ReturnType<typeof taskParametersFor>>;
const getParameters = Type.Object({ taskId: Type.Optional(Type.String()), agentId: Type.Optional(Type.String()), debug: Type.Optional(Type.Boolean({ default: false })) }, { additionalProperties: false });
const waitParameters = Type.Object({ taskIds: Type.Array(Type.String(), { minItems: 1, maxItems: 128, uniqueItems: true }), condition: StringEnum(["any", "all"] as const) }, { additionalProperties: false });
const stopParameters = Type.Object({ agentId: Type.Optional(Type.String()), taskId: Type.Optional(Type.String()), reason: Type.Optional(Type.String()) }, { additionalProperties: false });
const routeParameters = Type.Object({ action: StringEnum(["watch", "signal"] as const), receiver: Type.String(), delivery: StringEnum(["steer", "followUp"] as const), taskIds: Type.Optional(Type.Array(Type.String(), { minItems: 1, maxItems: 128, uniqueItems: true })), condition: Type.Optional(StringEnum(["any", "all"] as const)), topic: Type.Optional(Type.String()), text: Type.Optional(Type.String()) }, { additionalProperties: false });
const enableParameters = Type.Object({}, { additionalProperties: false });
function exactSelector(value: { agent?: string; agentId?: string }, tool: string): { kind: "new"; agent: string } | { kind: "existing"; agentId: string } { const fresh = value.agent !== undefined; const existing = value.agentId !== undefined; if (fresh === existing) throw new Error(`${tool} requires exactly one of agent or agentId`); return fresh ? { kind: "new", agent: value.agent! } : { kind: "existing", agentId: value.agentId! }; }

type Accounting = { usage?: Usage; claimedTaskIds: string[] };
async function claim(config: SubagentRuntimeConfig, caller: ActiveCaller, snapshot: AgentSnapshot, toolCallId: string, toolName: UsageClaim["toolName"]): Promise<Accounting> { const task = snapshot.task; if (!caller.sessionFile || !snapshot.agent.capabilities.usage || !task?.result || !isTerminalTask(task.status.state)) return { claimedTaskIds: [] }; const value = await claimTaskUsage(config.stateRoot, caller.meshId, task.request.taskId, caller.sessionFile, toolCallId, toolName); return value.created ? { usage: value.result.usage, claimedTaskIds: [task.request.taskId] } : { claimedTaskIds: [] }; }
function agentResult(raw: AgentSnapshot, accounting: Accounting, debug = false) { const snapshot = sanitizeSnapshot(raw); const details: AgentToolDetails = { ...snapshot, accounting }; return { content: [{ type: "text" as const, text: serializeModelVisibleJson(debug ? projectDebugSnapshot(snapshot) : projectMinimalAgentTask(snapshot)) }], details, usage: accounting.usage }; }
function submitResult(raw: AgentSnapshot, accounting: Accounting) { const snapshot = sanitizeSnapshot(raw); const details: SubmitDetails = { ...snapshot, accounting }; return { content: [{ type: "text" as const, text: serializeModelVisibleJson(projectMinimalSubmitResult(snapshot)) }], details, usage: accounting.usage }; }
function waitResult(snapshots: AgentSnapshot[], condition: "any" | "all", outcome: "completed" | undefined, accounting: Accounting) { const agents = snapshots.map(sanitizeSnapshot); const details: WaitDetails = { condition, ...(outcome ? { outcome } : {}), agents, accounting }; return { content: [{ type: "text" as const, text: serializeModelVisibleJson(outcome ? projectMinimalWaitResult(agents, "completed") : { tasks: agents.map(projectMinimalAgentTask) }) }], details, usage: accounting.usage }; }
async function pollTasks(input: { read: () => Promise<AgentSnapshot[]>; condition: "any" | "all"; signal?: AbortSignal; sleep: typeof sleep; claim: (snapshot: AgentSnapshot) => Promise<Accounting>; update?: (snapshots: AgentSnapshot[]) => void }): Promise<{ snapshots: AgentSnapshot[]; accounting: Accounting }> { while (true) { if (input.signal?.aborted) throw input.signal.reason; const snapshots = await input.read(); const done = snapshots.filter(item => item.task && isTerminalTask(item.task.status.state)); if (input.condition === "any" ? done.length > 0 : done.length === snapshots.length) { const accounting: Accounting = { claimedTaskIds: [] }; for (const snapshot of snapshots) { const item = await input.claim(snapshot); accounting.claimedTaskIds.push(...item.claimedTaskIds); if (item.usage) { accounting.usage ??= emptyUsage(); addUsage(accounting.usage, item.usage); } } return { snapshots, accounting }; } input.update?.(snapshots); await input.sleep(250, input.signal); } }
async function stopPreparedLaunch(deps: OrchestrationDependencies, tmuxCommand: string, tmux: NonNullable<Awaited<ReturnType<typeof launchAgentSession>>>): Promise<void> { let stopFailure: unknown; try { if (await stopAgentSession(deps.exec, tmuxCommand, tmux)) return; } catch (error) { stopFailure = error; } const inspected = await inspectAgentTmux(deps.exec, tmuxCommand, tmux).catch(error => { stopFailure ??= error; return undefined; }); const confirmed = inspected && (inspected.server === "absent" || inspected.server === "mismatch" || inspected.server === "match" && inspected.paneState === "dead"); if (!confirmed) throw new Error("Could not confirm that the pre-publication agent process stopped", { cause: stopFailure }); }

async function startAgentSubmission(deps: OrchestrationDependencies, config: SubagentRuntimeConfig, caller: ActiveCaller, params: TaskParameters & { agent: string }, signal: AbortSignal | undefined, ctx: ExtensionContext, onTaskCreated?: (snapshot: AgentSnapshot) => void, preserveOnAbort = false): Promise<AgentSnapshot> {
    if (signal?.aborted) throw signal.reason; const definition = caller.epoch.roles[params.agent]; if (!definition || !caller.epoch.roleSet.includes(params.agent)) throw new Error(`${caller.identity} epoch is not allowed to start role ${params.agent}`);
    const reservation = caller.agentId
        ? await awaitPressureAdmission(config.stateRoot, caller.meshId, { requestId: randomUUID(), requesterAgentId: caller.agentId, requesterRuntimeId: caller.runtimeId ?? "", signal, sleep: milliseconds => (deps.sleep ?? sleep)(milliseconds) })
        : await reserveNewAgentCapacityWithPressure({ stateRoot: config.stateRoot, meshId: caller.meshId, leaseId: deps.rootLeaseId?.() ?? "", gc: config.gc, exec: deps.exec, tmux: config.tmux }); const agentId = randomUUID(); const taskId = randomUUID(); const harness = resolveHarnessAdapter(config, definition.harness, definition); const tmuxContext = await probeTmux(deps.exec, config.tmux, deps.env); if (!tmuxContext) { await releaseMeshReservation(config.stateRoot, caller.meshId, reservation.reservationId, "tmux unavailable"); throw new Error("Mesh agent start requires a usable current tmux context"); }
    const childExtensions = Object.fromEntries(caller.epoch.roleSet.map(name => [name, caller.envelope?.childExtensions[name] ?? [config.popupExtension, config.orchestrationExtension, ...(caller.epoch.roles[name]?.childExtensionContributions ?? []), config.childBridgeExtension]]));
    const envelope = caller.envelope ? projectLaunchEnvelope(params.agent, agentId, caller.envelope) : buildLaunchEnvelope({ meshId: caller.meshId, agentId, epochId: caller.epoch.epochId, agent: params.agent, mode: caller.epoch.mode, roleSet: caller.epoch.roleSet, catalog: caller.catalog, childExtensions });
    const prepared = await prepareAgent(config.stateRoot, caller.meshId, { reservationId: reservation.reservationId, agentId, agent: params.agent, harness: definition.harness, cwd: ctx.cwd, agentSnapshot: definition, launchEnvelope: "pending", epochId: caller.epoch.epochId, provenance: { parentAgentId: caller.agentId, creatorSessionId: ctx.sessionManager.getSessionId(), ...(caller.sessionFile ? { creatorSessionFile: caller.sessionFile } : {}) }, capabilities: harness.adapter.capabilities });
    const envelopePath = join(prepared.paths.directory, "launch-envelope.json"); let tmux; let published = false; let taskCreated = false;
    try {
        await writeFile(envelopePath, `${JSON.stringify(envelope, null, 2)}\n`, { mode: 0o600 });
        const launch = harness.adapter.launch(config, harness.harness, { meshId: caller.meshId, agentId, agentDirectory: prepared.paths.directory, agent: params.agent, taskPath: taskPaths(config.stateRoot, caller.meshId, taskId).directory, launchEnvelope: envelopePath, epochSnapshot: envelope, cwd: ctx.cwd });
        tmux = await launchAgentSession(deps.exec, config.tmux, tmuxContext, { meshId: caller.meshId, epochId: caller.epoch.epochId, agentId, agent: params.agent, cwd: ctx.cwd, launch });
        await publishAgent(config.stateRoot, caller.meshId, prepared.paths, { agentId, epochId: caller.epoch.epochId, agent: params.agent, harness: definition.harness, cwd: ctx.cwd, agentSnapshot: definition, launchEnvelope: envelopePath, tmux, tmuxOwnership: "mesh-hub", capabilities: harness.adapter.capabilities, parentAgentId: caller.agentId, creatorSessionId: ctx.sessionManager.getSessionId(), ...(caller.sessionFile ? { creatorSessionFile: caller.sessionFile } : {}) }); published = true;
        const task = await createTask(config.stateRoot, caller.meshId, agentId, params.prompt, reservation.reservationId, taskId); taskCreated = true; let snapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, agentId, task.request.taskId); onTaskCreated?.(snapshot);
        const deadline = (deps.now ?? (() => performance.now()))() + (harness.harness.bridgeReadyTimeoutMs ?? 5000); while ((deps.now ?? (() => performance.now()))() < deadline) { if (signal?.aborted) throw signal.reason; snapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, agentId, taskId); if (isTerminalAgent(snapshot.status.state)) throw new Error(snapshot.status.exitReason ?? `Agent became ${snapshot.status.state} during startup`); if (snapshot.status.bridgeReady) return readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, agentId, taskId); await (deps.sleep ?? sleep)(50, signal); } throw new Error("Agent bridge readiness timed out");
    } catch (error) {
        if (preserveOnAbort && taskCreated && signal?.aborted) throw error; let cleanupError: unknown;
        if (published) try { await failStartedMeshAgent({ stateRoot: config.stateRoot, meshId: caller.meshId, agentId, exec: deps.exec, tmux: config.tmux }, errorText(error)); } catch (failure) { cleanupError = failure; }
        else { let confirmed = tmux === undefined && !(error instanceof AgentLaunchCleanupError); if (tmux) try { await stopPreparedLaunch(deps, config.tmux, tmux); confirmed = true; } catch (failure) { cleanupError = failure; } else if (!confirmed) cleanupError = error; if (confirmed) await removePreparedAgent(config.stateRoot, caller.meshId, agentId, reservation.reservationId, "launch failed"); }
        if (cleanupError) throw new Error(`${errorText(error)}; cleanup for agent ${agentId} remains incomplete: ${errorText(cleanupError)}`); if (!taskCreated) await releaseMeshReservation(config.stateRoot, caller.meshId, reservation.reservationId, "launch failed before task commit").catch(() => {}); throw error;
    }
}

export function createMeshRunTool(deps: OrchestrationDependencies, targets: Readonly<Record<string, AgentDefinition>> = {}): ToolDefinition { return defineTool({ name: "mesh_run", label: "Run mesh task", description: "Run one task on exactly one new role or existing idle mesh agent and wait for terminal completion.", promptSnippet: "Run one foreground mesh task", promptGuidelines: ["Use `mesh_run` when the result is the next dependency; do not wait again after it.", "For a bounded instruction after a running or compacting agent's current activity, use `mesh_route` signal delivery `followUp`; it does not create a queued task or outcome."], parameters: taskParametersFor(targets), renderCall: renderRunCall, renderResult: (result, options, theme, context) => renderRunResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params, signal, update, ctx) { const target = exactSelector(params, "mesh_run"); const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); let snapshot: AgentSnapshot | undefined; try { if (target.kind === "new") snapshot = await startAgentSubmission(deps, config, caller, { ...params, agent: target.agent }, signal, ctx, value => { snapshot = value; }, true); else { rejectSelfAgent(caller, target.agentId, "run"); const stored = await readAgentSnapshot(config.stateRoot, caller.meshId, target.agentId); authorizeRole(caller, stored, "reuse"); const reconciled = await readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, target.agentId); assertAgentAccepting(reconciled.activity, reconciled.status); const task = await createTask(config.stateRoot, caller.meshId, target.agentId, params.prompt); snapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, target.agentId, task.request.taskId); } const taskId = snapshot.task!.request.taskId; update?.(agentResult(snapshot, { claimedTaskIds: [] })); const waited = await pollTasks({ read: async () => [await readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, snapshot!.agent.agentId, taskId)], condition: "all", signal, sleep: deps.sleep ?? sleep, claim: value => claim(config, caller, value, id, "mesh_run"), update: values => update?.(agentResult(values[0]!, { claimedTaskIds: [] })) }); return agentResult(waited.snapshots[0]!, waited.accounting); } catch (error) { if (!signal?.aborted || !snapshot?.task) throw error; try { await stopMeshTask({ stateRoot: config.stateRoot, meshId: caller.meshId, taskId: snapshot.task.request.taskId, reason: "Foreground mesh run aborted" }); } catch (cleanup) { throw new Error(`mesh_run abort cleanup failed for task ${snapshot.task.request.taskId}: ${errorText(cleanup)}`, { cause: error }); } throw error; } } }); }
export function createMeshSubmitTool(deps: OrchestrationDependencies, targets: Readonly<Record<string, AgentDefinition>> = {}): ToolDefinition { return defineTool({ name: "mesh_submit", label: "Submit mesh task", description: "Submit one task to exactly one new role or existing idle mesh agent and return stable agentId/taskId immediately.", promptSnippet: "Submit one background mesh task", parameters: taskParametersFor(targets), executionMode: "sequential", renderCall: renderSubmitCall, renderResult: (result, options, theme, context) => renderSubmitResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params, signal, _update, ctx) { const target = exactSelector(params, "mesh_submit"); const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); let snapshot: AgentSnapshot; if (target.kind === "new") snapshot = await startAgentSubmission(deps, config, caller, { ...params, agent: target.agent }, signal, ctx); else { rejectSelfAgent(caller, target.agentId, "submit"); const stored = await readAgentSnapshot(config.stateRoot, caller.meshId, target.agentId); authorizeRole(caller, stored, "reuse"); const reconciled = await readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, target.agentId); assertAgentAccepting(reconciled.activity, reconciled.status); const task = await createTask(config.stateRoot, caller.meshId, target.agentId, params.prompt); snapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, target.agentId, task.request.taskId); } return submitResult(snapshot, await claim(config, caller, snapshot, id, "mesh_submit")); } }); }
export function createMeshGetTool(deps: OrchestrationDependencies): ToolDefinition<typeof getParameters, unknown> { return defineTool({ name: "mesh_get", label: "Get mesh task or agent", description: "Inspect exactly one same-mesh taskId or agentId. debug is valid only with agentId.", promptSnippet: "Inspect mesh task or agent state", parameters: getParameters, executionMode: "sequential", prepareArguments: args => asRecord(args) as Static<typeof getParameters>, renderCall: renderGetCall, renderResult: (result, options, theme, context) => renderAgentToolResult(result, options, theme, context, undefined, context.args.debug === true, deps.natureHandleWords?.()), async execute(id, params) { const task = params.taskId !== undefined; const agent = params.agentId !== undefined; if (task === agent) throw new Error("mesh_get requires exactly one of taskId or agentId"); if (params.debug && task) throw new Error("mesh_get debug is only valid with agentId"); const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); let snapshot: AgentSnapshot; if (params.taskId) { const record = await readTask(config.stateRoot, caller.meshId, params.taskId); snapshot = await readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, record.request.agentId, params.taskId); } else snapshot = await readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, params.agentId!); return agentResult(snapshot, await claim(config, caller, snapshot, id, "mesh_get"), params.debug === true); } }); }
export function createMeshWaitTool(deps: OrchestrationDependencies): ToolDefinition<typeof waitParameters, unknown> { return defineTool({ name: "mesh_wait", label: "Wait for mesh tasks", description: "Wait for unique same-mesh task IDs until any/all become terminal. Aborting leaves tasks alive.", promptSnippet: "Wait for background mesh tasks", parameters: waitParameters, executionMode: "sequential", prepareArguments: args => asRecord(args) as Static<typeof waitParameters>, renderCall: renderWaitCall, renderResult: (result, options, theme, context) => renderWaitResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params, signal, update) { const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); const tasks = await Promise.all(params.taskIds.map(taskId => readTask(config.stateRoot, caller.meshId, taskId))); for (const task of tasks) if (caller.agentId === task.request.agentId && !isTerminalTask(task.status.state)) throw new Error(`mesh_wait cannot wait on the calling agent's own active task ${task.request.taskId}`); const read = () => Promise.all(tasks.map(task => readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, task.request.agentId, task.request.taskId))); const waited = await pollTasks({ read, condition: params.condition, signal, sleep: deps.sleep ?? sleep, claim: snapshot => claim(config, caller, snapshot, id, "mesh_wait"), update: snapshots => update?.(waitResult(snapshots, params.condition, undefined, { claimedTaskIds: [] })) }); return waitResult(waited.snapshots, params.condition, "completed", waited.accounting); } }); }
export function createMeshStopTool(deps: OrchestrationDependencies): ToolDefinition<typeof stopParameters, unknown> { return defineTool({ name: "mesh_stop", label: "Stop mesh task or agent", description: "Stop exactly one taskId or agentId. Task stop leaves its agent reusable.", promptSnippet: "Stop one mesh task or agent", parameters: stopParameters, executionMode: "sequential", prepareArguments: args => asRecord(args) as Static<typeof stopParameters>, renderCall: renderStopCall, renderResult: (result, options, theme, context) => renderStopResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params) { const hasAgent = params.agentId !== undefined; const hasTask = params.taskId !== undefined; if (hasAgent === hasTask) throw new Error("mesh_stop requires exactly one of agentId or taskId"); if (hasTask && params.reason !== undefined) throw new Error("mesh_stop taskId rejects reason"); const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); let snapshot: AgentSnapshot; let disposition; if (params.agentId) { rejectSelfAgent(caller, params.agentId, "stop"); const stored = await readAgentSnapshot(config.stateRoot, caller.meshId, params.agentId); authorizeRole(caller, stored, "stop"); const reason = validateStopReason(params.reason); const result = await stopMeshAgentWithDisposition({ stateRoot: config.stateRoot, meshId: caller.meshId, agentId: params.agentId, exec: deps.exec, tmux: config.tmux, source: "peer", reason, requesterEndpointId: caller.endpointId }); snapshot = result.snapshot; disposition = result.disposition; } else { const task = await readTask(config.stateRoot, caller.meshId, params.taskId!); const stored = await readAgentSnapshot(config.stateRoot, caller.meshId, task.request.agentId, params.taskId); authorizeRole(caller, stored, "stop"); const result = await stopMeshTaskWithDisposition({ stateRoot: config.stateRoot, meshId: caller.meshId, taskId: params.taskId! }); snapshot = result.snapshot; disposition = result.disposition; } const result = agentResult(snapshot, await claim(config, caller, snapshot, id, "mesh_stop")); return { ...result, details: { ...result.details, stopDisposition: disposition } }; } }); }

function utf8(value: string): number { return Buffer.byteLength(value, "utf8"); }
export function createMeshRouteTool(deps: OrchestrationDependencies): ToolDefinition<typeof routeParameters, unknown> { return defineTool({ name: "mesh_route", label: "Route mesh event", description: "Register a terminal task watch or send a bounded signal to a durable same-mesh Pi endpoint.", promptSnippet: "Route a watch or signal to a mesh peer", parameters: routeParameters, executionMode: "sequential", prepareArguments: args => asRecord(args) as Static<typeof routeParameters>, renderCall: renderRouteCall, renderResult: renderRouteResult, async execute(toolCallId, params) { const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); const endpoint = await resolveRouteEndpoint(config.stateRoot, caller.meshId, params.receiver, caller.agentId); let result: Record<string, unknown>; if (params.action === "watch") { if (!params.taskIds?.length || !params.condition) throw new Error("mesh_route watch requires taskIds and condition"); if (params.topic !== undefined || params.text !== undefined) throw new Error("mesh_route watch rejects topic and text"); result = await registerMeshWatch(config.stateRoot, caller.meshId, { callerEndpointId: caller.endpointId, toolCallId, endpoint, delivery: params.delivery, taskIds: params.taskIds, condition: params.condition, canonicalArguments: params }); } else { if (params.condition !== undefined) throw new Error("mesh_route signal rejects condition"); if (typeof params.topic !== "string" || utf8(params.topic) < 1 || utf8(params.topic) > 64) throw new Error("mesh_route signal topic must be 1-64 UTF-8 bytes"); if (typeof params.text !== "string" || utf8(params.text) < 1 || utf8(params.text) > 8192) throw new Error("mesh_route signal text must be 1-8192 UTF-8 bytes"); if (params.taskIds && params.taskIds.length > 16) throw new Error("mesh_route signal accepts at most 16 taskIds"); result = await registerMeshSignal(config.stateRoot, caller.meshId, { callerEndpointId: caller.endpointId, toolCallId, endpoint, delivery: params.delivery, topic: params.topic, text: params.text, ...(params.taskIds ? { taskIds: params.taskIds } : {}), canonicalArguments: params }); } return { content: [{ type: "text" as const, text: serializeModelVisibleJson(result) }], details: result }; } }); }

export async function stopPaletteMeshAgent(deps: OrchestrationDependencies, config: SubagentRuntimeConfig, request: { meshId: string; agentId: string; reason: string }): Promise<AgentSnapshot> { const caller = await authorized(deps); const snapshot = await readAgentSnapshot(config.stateRoot, request.meshId, request.agentId); authorizeRole(caller, snapshot, "stop"); rejectSelfAgent(caller, request.agentId, "stop"); const reason = validateStopReason(request.reason, "Palette stop reason"); return (await stopMeshAgentWithDisposition({ stateRoot: config.stateRoot, meshId: request.meshId, agentId: request.agentId, exec: deps.exec, tmux: config.tmux, source: "user", reason, requesterEndpointId: caller.endpointId })).snapshot; }

export function createMeshEnableTool(pi: ExtensionAPI, deps: OrchestrationDependencies, persist: () => Promise<void>): ToolDefinition<typeof enableParameters, unknown> { return defineTool({ name: MESH_BOOTSTRAP_TOOL_NAME, label: "Enable peer mesh tools", description: "Add peer observation, launch, wait, stop, and routing tools when this task requires coordination. Existing role tools are preserved.", promptSnippet: "Enable peer mesh coordination tools", parameters: enableParameters, renderCall: renderEnableCall, renderResult: renderEnableResult, async execute() { const caller = await authorized(deps); const all = new Set(pi.getAllTools().map(tool => tool.name)); const missing = MESH_PEER_TOOL_NAMES.filter(name => !all.has(name)); if (missing.length) throw new Error(`Mesh activation unavailable; tools not registered: ${missing.join(", ")}`); const current = pi.getActiveTools(); const next = [...new Set([...current, ...MESH_PEER_TOOL_NAMES])]; pi.setActiveTools(next); const activeNow = new Set(pi.getActiveTools()); const failed = MESH_PEER_TOOL_NAMES.filter(name => !activeNow.has(name)); if (failed.length) throw new Error(`Mesh activation incomplete: ${failed.join(", ")}`); if (caller.agentId) await persist(); return { content: [{ type: "text" as const, text: serializeModelVisibleJson({ enabled: true, activeTools: pi.getActiveTools() }) }], details: { enabled: true, activeTools: pi.getActiveTools() } }; } }); }

export async function registerOrchestration(pi: ExtensionAPI, options: OrchestrationRegistrationOptions = {}): Promise<boolean> {
    pi.registerEntryRenderer(NOTICE_ENTRY, (entry, renderOptions, theme) => renderTuiNotice(entry.data as TuiNotice, renderOptions.expanded, theme));
    loadFeatureKeybindings("meshPalette"); loadFeatureKeybindings("tmuxPreview"); const configPath = options.configPath ?? CONFIG; const catalogPath = options.catalogPath ?? CATALOG; const env = options.env ?? process.env; const runtime = await loadOrchestrationConfig(configPath); const catalog = await loadAgentCatalog(catalogPath); const exec: CommandExecutor = async (command, args) => { const value = await pi.exec(command, args); return { stdout: value.stdout, stderr: value.stderr, code: value.code }; };
    let current: ActiveCaller | undefined; let rootLeaseId: string | undefined; let endpoint: MeshEndpoint | undefined; let sessionContext: ExtensionContext | undefined; let latestMode: ActiveModeEvent | undefined; let timer: unknown; let pumping = false; let noticePumping = false; let rootPass: Promise<unknown> | undefined; let nextGcAt = 0; let shuttingDown = false; let lastPumpError: string | undefined; let lastNoticePumpError: string | undefined; let modeBarrier: ActiveModeBarrier; const maintenance = new AbortController(); const injectedThisRuntime = new Set<string>(); const appendedNotices = new Set<string>(); const notifiedNotices = new Set<string>(); const reportedNoticeErrors = new Set<string>(); let resolvedEnvelope: AgentLaunchEnvelope | undefined; const childAgentId = env.PI_MESH_AGENT_ID; const childMeshId = env.PI_MESH_ID;
    if (env.PI_AGENT_RESOLVED_AGENT) try { resolvedEnvelope = validateLaunchEnvelope(JSON.parse(await readFile(env.PI_AGENT_RESOLVED_AGENT, "utf8"))); } catch (error) { current = { identity: "agent:invalid", meshId: childMeshId ?? randomUUID(), epoch: {} as PolicyEpoch, catalog, endpointId: "invalid", error: errorText(error) }; }
    const deps: OrchestrationDependencies = { configPath, catalogPath, env, exec, activeCaller: () => current, authorityBarrier: () => modeBarrier.wait(), rootLeaseId: () => rootLeaseId, natureHandleWords: () => runtime.natureHandleWords };
    const inspectRootLease = (sessionId: string, sessionFile: string | undefined, tmux: Awaited<ReturnType<typeof probeTmux>>) => async (existing: Parameters<NonNullable<Parameters<typeof attachRootMesh>[2]["inspectExisting"]>>[0]) => { let pidAlive = true; try { process.kill(existing.pid, 0); } catch { pidAlive = false; } const sameSession = existing.rootSessionId === sessionId && existing.rootSessionFile === sessionFile; const tmuxMatches = existing.tmuxServerPid === undefined && existing.tmuxSessionId === undefined ? tmux === null : Boolean(tmux && existing.tmuxServerPid === tmux.serverPid && existing.tmuxSessionId === tmux.sessionId); return { pidAlive, sameSession, tmuxMatches }; };
    const registerDispatch = (targets: Record<string, AgentDefinition>) => { pi.registerTool(createMeshRunTool(deps, targets)); pi.registerTool(createMeshSubmitTool(deps, targets)); };
    registerDispatch(resolvedEnvelope ? resolvedEnvelope.catalog : {}); pi.registerTool(createMeshGetTool(deps)); pi.registerTool(createMeshWaitTool(deps)); pi.registerTool(createMeshStopTool(deps)); pi.registerTool(createMeshRouteTool(deps));
    const persistEnabled = async () => { const caller = active(deps); if (caller.agentId) { const { patchAgentStatus } = await import("./utilities/orchestration_store.ts"); await patchAgentStatus(runtime.stateRoot, caller.meshId, caller.agentId, { meshToolsEnabled: true }); } };
    if (childAgentId) pi.registerTool(createMeshEnableTool(pi, deps, persistEnabled));
    const activateMesh = async () => { const all = new Set(pi.getAllTools().map(tool => tool.name)); const missing = MESH_PEER_TOOL_NAMES.filter(name => !all.has(name)); if (missing.length) throw new Error(`Mesh activation unavailable; tools not registered: ${missing.join(", ")}`); const next = [...new Set([...pi.getActiveTools(), ...MESH_PEER_TOOL_NAMES])]; pi.setActiveTools(next); const failed = MESH_PEER_TOOL_NAMES.filter(name => !pi.getActiveTools().includes(name)); if (failed.length) throw new Error(`Mesh activation incomplete: ${failed.join(", ")}`); await persistEnabled(); };
    const applyMode = async (event: ActiveModeEvent) => { latestMode = event; if (!sessionContext || childAgentId || !current) return; const names = runtime.roleSets[`mode:${event.name}`]; if (!names) throw new Error(`Mode ${event.name} has no mesh role set`); const roles = Object.fromEntries(names.map(name => [name, catalog.agents[name]!])); const restored = branchData<EpochBinding>(sessionContext, POLICY_BINDING); const epoch = await ensurePolicyEpoch(runtime.stateRoot, current.meshId, { mode: event.name, roleSet: names, roles, ...(restored?.meshId === current.meshId && restored.mode === event.name ? { restoreEpochId: restored.epochId } : {}) }); current = { ...current, identity: `mode:${event.name}`, epoch, error: undefined }; registerDispatch(roleTargets(current)); if (!restored || restored.epochId !== epoch.epochId) pi.appendEntry(POLICY_BINDING, { schemaVersion: 1, meshId: current.meshId, mode: event.name, epochId: epoch.epochId, policyDigest: epoch.policyDigest } satisfies EpochBinding); };
    modeBarrier = createActiveModeBarrier(applyMode, error => { if (current) current = { ...current, error: errorText(error) }; });
    onActiveMode(pi, event => modeBarrier.enqueue(event), error => { if (current) current = { ...current, error: errorText(error) }; });
    const pumpEvents = async (): Promise<boolean> => { if (shuttingDown || pumping || !endpoint || !current || !endpoint.online) return false; pumping = true; try { const events = await pollMeshEvents(runtime.stateRoot, current.meshId, endpoint); if (shuttingDown) return false; for (const event of events) { if (shuttingDown) return false; if (injectedThisRuntime.has(event.eventId)) continue; if (childAgentId) await activateMesh(); if (shuttingDown) return false; const content = `[mesh-event ${event.eventId}] ${event.kind}\n${serializeModelVisibleJson(event.payload)}`; pi.sendMessage({ customType: "mesh-event", content, display: true, details: { eventId: event.eventId, kind: event.kind, payload: event.payload } }, { deliverAs: event.delivery, triggerTurn: sessionContext?.isIdle() ?? false }); await markMeshEventInjected(runtime.stateRoot, current.meshId, event.eventId); injectedThisRuntime.add(event.eventId); } return true; } finally { pumping = false; } };
    const pumpWithDiagnostics = async () => { try { if (await pumpEvents() && lastPumpError !== undefined) { lastPumpError = undefined; try { sessionContext?.ui.setStatus(PUMP_STATUS, undefined); } catch {} } } catch (error) { const text = errorText(error).replace(/\s+/gu, " ").trim(); if (text !== lastPumpError) { lastPumpError = text; const diagnostic = `Mesh event pump: ${text}`; try { sessionContext?.ui.setStatus(PUMP_STATUS, diagnostic); } catch {} try { sessionContext?.ui.notify(diagnostic, "error"); } catch {} } } };
    const reportNoticeError = (error: unknown) => { const text = errorText(error).replace(/\s+/gu, " ").trim(); lastNoticePumpError = text; if (reportedNoticeErrors.has(text)) return; reportedNoticeErrors.add(text); const diagnostic = `Mesh notice pump: ${text}`; try { sessionContext?.ui.setStatus(NOTICE_PUMP_STATUS, diagnostic); } catch {} try { sessionContext?.ui.notify(diagnostic, "error"); } catch {} };
    const pumpTuiNotices = async (): Promise<void> => {
        if (shuttingDown || noticePumping || sessionContext?.mode !== "tui" || !endpoint || !current) return;
        noticePumping = true; let failed = false;
        try {
            if (!await isLiveMeshEndpointBinding(runtime.stateRoot, current.meshId, endpoint)) return;
            const notices = await listPendingTuiNotices(runtime.stateRoot, current.meshId, { endpointId: endpoint.endpointId });
            for (const notice of notices) try {
                if (shuttingDown || sessionContext.mode !== "tui" || !await isLiveMeshEndpointBinding(runtime.stateRoot, current.meshId, endpoint)) return;
                if (!appendedNotices.has(notice.noticeId)) { pi.appendEntry(NOTICE_ENTRY, notice); appendedNotices.add(notice.noticeId); }
                if (!notifiedNotices.has(notice.noticeId)) { sessionContext.ui.notify(tuiNoticeText(notice), "info"); notifiedNotices.add(notice.noticeId); }
                if (shuttingDown || !await isLiveMeshEndpointBinding(runtime.stateRoot, current.meshId, endpoint)) return;
                await acknowledgeDisplayedTuiNotice(runtime.stateRoot, current.meshId, notice.noticeId, { endpointId: endpoint.endpointId, binding: endpoint }, new Date().toISOString());
            } catch (error) { failed = true; reportNoticeError(error); }
            if (!failed && lastNoticePumpError !== undefined) { lastNoticePumpError = undefined; try { sessionContext.ui.setStatus(NOTICE_PUMP_STATUS, undefined); } catch {} }
        } catch (error) { reportNoticeError(error); } finally { noticePumping = false; }
    };
    if (childAgentId) pi.registerCommand("parent", { description: "Return to this mesh agent's inviter tmux window", async handler(_args, ctx) { const result = await exec(runtime.returnParentCommand, []); if (result.code !== 0) ctx.ui.notify(result.stderr.trim() || "Could not return to the inviter window", "error"); } });
    pi.on("session_start", async (_event, ctx) => {
        sessionContext = ctx; const sessionId = ctx.sessionManager.getSessionId(); const sessionFile = ctx.sessionManager.getSessionFile();
        if (resolvedEnvelope && childMeshId && childAgentId) { if (resolvedEnvelope.meshId !== childMeshId || resolvedEnvelope.agentId !== childAgentId) throw new Error("Mesh child environment does not match launch envelope"); if (!sessionFile) throw new Error("Mesh child session requires a durable session file"); const binding = await bindAgentRuntime(runtime.stateRoot, childMeshId, childAgentId, { runtimeId: randomUUID(), kind: "pi", sessionId, sessionFile }); const epochRecord = await readPolicyEpoch(runtime.stateRoot, childMeshId, resolvedEnvelope.epochId); current = { identity: resolvedEnvelope.identity, meshId: childMeshId, epoch: epochRecord, catalog: { schemaVersion: 1, agents: resolvedEnvelope.catalog }, envelope: resolvedEnvelope, agentId: childAgentId, runtimeId: binding.runtimeId, endpointId: `agent:${childAgentId}`, sessionFile }; emitResolvedAgent(pi, resolvedEnvelope); if (sessionFile) endpoint = await bindMeshEndpoint(runtime.stateRoot, childMeshId, { endpointId: current.endpointId, kind: "agent", agentId: childAgentId, harness: "pi", sessionId, sessionFile }); const status = await readAgentSnapshot(runtime.stateRoot, childMeshId, childAgentId).then(value => value.status); const roleTools = resolvedEnvelope.self.tools.filter(name => name !== MESH_BOOTSTRAP_TOOL_NAME && !MESH_PEER_TOOL_NAMES.includes(name as typeof MESH_PEER_TOOL_NAMES[number])); pi.setActiveTools([...new Set([...roleTools, MESH_BOOTSTRAP_TOOL_NAME, ...(status.meshToolsEnabled ? MESH_PEER_TOOL_NAMES : [])])]); ctx.ui.setStatus(PARENT_STATUS, runtime.parentNavigationHint); if (sessionFile) await reconcileMeshUsageClaims(runtime.stateRoot, childMeshId, sessionFile); }
        else {
            const persisted = Boolean(sessionFile); const restored = branchData<RootBinding>(ctx, ROOT_BINDING); let mesh = restored ? await readMesh(runtime.stateRoot, restored.meshId).catch(() => undefined) : undefined; if (mesh?.state === "closing" && persisted) { const recoveryTmux = await probeTmux(exec, runtime.tmux, env); const recoveryLease = await attachRootMesh(runtime.stateRoot, mesh.meshId, { rootSessionId: sessionId, budgets: runtime.budgets, ...(sessionFile ? { rootSessionFile: sessionFile } : {}), inspectExisting: inspectRootLease(sessionId, sessionFile, recoveryTmux) }); await cleanupMeshAgents({ stateRoot: runtime.stateRoot, meshId: mesh.meshId, exec, tmux: runtime.tmux, shutdownReason: "recovery", hubContext: recoveryTmux ?? undefined }); await completeMeshClose(runtime.stateRoot, mesh.meshId, recoveryLease.leaseId); mesh = undefined; } if (!mesh || mesh.state !== "open" || !mesh.recoverable || !persisted) { mesh = await initializeMesh(runtime.stateRoot, { rootSessionId: sessionId, ...(sessionFile ? { rootSessionFile: sessionFile } : {}), recoverable: persisted, budgets: runtime.budgets }); if (persisted) pi.appendEntry(ROOT_BINDING, { schemaVersion: 1, meshId: mesh.meshId } satisfies RootBinding); }
            const tmux = await probeTmux(exec, runtime.tmux, env); const lease = await attachRootMesh(runtime.stateRoot, mesh.meshId, { rootSessionId: sessionId, budgets: runtime.budgets, ...(sessionFile ? { rootSessionFile: sessionFile } : {}), ...(tmux ? { tmuxServerPid: tmux.serverPid, tmuxSessionId: tmux.sessionId } : {}), inspectExisting: inspectRootLease(sessionId, sessionFile, tmux) }); rootLeaseId = lease.leaseId; const fallbackEpoch = mesh.currentEpochId ? await readPolicyEpoch(runtime.stateRoot, mesh.meshId, mesh.currentEpochId) : { schemaVersion: 1 as const, meshId: mesh.meshId, epochId: randomUUID(), mode: "pending", roleSet: [], roles: {}, policyDigest: "", createdAt: new Date().toISOString() }; current = { identity: "mode:pending", meshId: mesh.meshId, epoch: fallbackEpoch, catalog, endpointId: `root:${mesh.meshId}`, ...(sessionFile ? { sessionFile } : {}) }; if (sessionFile) endpoint = await bindMeshEndpoint(runtime.stateRoot, mesh.meshId, { endpointId: current.endpointId, kind: "root", harness: "pi", sessionId, sessionFile }); if (latestMode) await applyMode(latestMode); await reconcileMeshState(runtime.stateRoot, mesh.meshId); if (sessionFile) await reconcileMeshUsageClaims(runtime.stateRoot, mesh.meshId, sessionFile); const protectedReservations = await reconcilePressureAdmissions(runtime.stateRoot, mesh.meshId, async requester => { const inspected = await inspectAgentTmux(exec, runtime.tmux, requester.agent.tmux); if (inspected.server === "unavailable" || inspected.server === "match" && inspected.paneState === "unavailable") throw new Error("Requester tmux evidence is temporarily unavailable"); return inspected.server === "match" && inspected.sessionAlive && inspected.paneState === "alive"; }); await reconcileMeshReservations(runtime.stateRoot, mesh.meshId, agentId => inspectMeshAgentWindow(exec, runtime.tmux, tmux, mesh.meshId, agentId), protectedReservations); await recoverPendingAgentStops({ stateRoot: runtime.stateRoot, meshId: mesh.meshId, exec, tmux: runtime.tmux });
        }
        const scheduleInterval = options.setInterval ?? ((callback: () => void | Promise<void>, delay: number) => globalThis.setInterval(() => { void callback(); }, delay));
        if (rootLeaseId) nextGcAt = Date.now() + runtime.gc.periodicIntervalMs;
        timer = scheduleInterval(async () => { if (rootLeaseId && current) { void heartbeatRootLease(runtime.stateRoot, current.meshId, rootLeaseId).catch(() => {}); const now = Date.now(); if (!shuttingDown && !rootPass) { const periodicDue = now >= nextGcAt; if (periodicDue) nextGcAt = now + runtime.gc.periodicIntervalMs; const options = { stateRoot: runtime.stateRoot, meshId: current.meshId, leaseId: rootLeaseId, gc: runtime.gc, exec, tmux: runtime.tmux, signal: maintenance.signal }; rootPass = (async () => { await processPressureAdmissions(options); if (periodicDue) { await recoverPendingAgentStops(options); await runPeriodicAgentGc(options); } })().catch(error => { if (!maintenance.signal.aborted) sessionContext?.ui.setStatus("mesh-agent-gc", `Mesh agent GC: ${errorText(error)}`); }).finally(() => { rootPass = undefined; }); } } await pumpWithDiagnostics(); await pumpTuiNotices(); }, 250); await pumpWithDiagnostics(); await pumpTuiNotices();
    });
    pi.on("context", async event => { const ids = event.messages.flatMap(message => { const raw = message as unknown as Record<string, unknown>; const details = raw.details && typeof raw.details === "object" ? raw.details as Record<string, unknown> : undefined; return raw.customType === "mesh-event" && typeof details?.eventId === "string" ? [details.eventId] : []; }); if (current && ids.length) await acknowledgeMeshEvents(runtime.stateRoot, current.meshId, ids); });
    if (resolvedEnvelope) pi.on("before_agent_start", (event, ctx) => { const definition = resolvedEnvelope!.self; const opted = new Set(definition.skillOptIns); const loaded = event.systemPromptOptions.skills ?? []; const names = new Set(loaded.map(skill => skill.name)); const missing = definition.skillOptIns.filter(name => !names.has(name)); if (missing.length) ctx.ui.notify(`Agent ${resolvedEnvelope!.identity}: opted-in skills unavailable: ${missing.join(", ")}`, "warning"); const skills = loaded.filter(skill => opted.has(skill.name) && skill.disableModelInvocation).map(skill => ({ ...skill, disableModelInvocation: false })); const addition = [formatSkillsForPrompt(skills), definition.instructions].filter(Boolean).join("\n\n"); if (addition) return { systemPrompt: `${event.systemPrompt}\n\n${addition}` }; });
    const paletteDeps = (): MeshPaletteDependencies => { const caller = active(deps); return { meshId: caller.meshId, exec, tmux: runtime.tmux, historyViewerExtension: runtime.historyViewerExtension, piCommand: runtime.harnesses.pi!.command, natureHandleWords: runtime.natureHandleWords, tmuxPreviewActions: loadFeatureKeybindings("tmuxPreview").actions, discover: async identity => { const store = await import("./utilities/orchestration_store.ts"); const items = await store.listMeshAgents(runtime.stateRoot, identity.meshId); const values = await Promise.all(items.map(item => readReconciledAgentSnapshot(exec, runtime.tmux, runtime.stateRoot, identity.meshId, item.agent.agentId).then(value => ({ ok: true as const, value })).catch(() => ({ ok: false as const })))); return { agents: values.flatMap(item => item.ok ? [item.value] : []), malformedCount: values.filter(item => !item.ok).length }; }, stopAgent: request => stopPaletteMeshAgent(deps, runtime, request) }; };
    providePopupView(pi, { id: "agent-sessions", title: "Mesh Agents", create(view) { const component = new MeshAgentsPaletteComponent({ tui: view.tui, theme: view.theme, ui: view.extensionContext.ui, keymap: loadPaletteKeymap(undefined, "meshPalette").keymap, deps: paletteDeps(), done: disposition => view.done(disposition === "close" ? "close-all" : "back") }); component.start(); return component; } }); const open = async (ctx: ExtensionContext, placement: "root" | "push" = "root") => openPopupView(pi, "agent-sessions", ctx, placement); const unregister = provideCommandPaletteContribution(pi.events, { owner: "mesh", id: "agents", label: "/mesh  Manage mesh agents", description: "Open, unlink, inspect, or stop mesh agent sessions.", keywords: ["mesh", "agents", "tmux"], run: async ctx => (await open(ctx, "push")) === "close-all" ? "close" : "return" }); pi.registerCommand("mesh", { description: "Manage persistent mesh agents", handler: async (_args, ctx) => { await open(ctx); } });
    pi.on("session_shutdown", async event => { shuttingDown = true; maintenance.abort(new Error("Mesh root maintenance stopped for session shutdown")); unregister(); if (timer !== undefined) (options.clearInterval ?? (value => globalThis.clearInterval(value as NodeJS.Timeout)))(timer); await rootPass?.catch(() => {}); if (endpoint && current) await setMeshEndpointOffline(runtime.stateRoot, current.meshId, endpoint.endpointId, endpoint).catch(() => {}); if (!childAgentId && current && rootLeaseId) await failOpenPressureAdmissions(runtime.stateRoot, current.meshId).catch(() => {}); if (childAgentId || !current || !rootLeaseId || event.reason === "reload") return; await beginMeshClose(runtime.stateRoot, current.meshId, rootLeaseId); const hubContext = await probeTmux(exec, runtime.tmux, env) ?? undefined; await cleanupMeshAgents({ stateRoot: runtime.stateRoot, meshId: current.meshId, exec, tmux: runtime.tmux, shutdownReason: event.reason, hubContext }); await completeMeshClose(runtime.stateRoot, current.meshId, rootLeaseId); });
    return true;
}
export default registerOrchestration;
