import { randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { StringEnum, type Usage } from "@earendil-works/pi-ai";
import { defineTool, getAgentDir, type ExtensionAPI, type ExtensionContext, type ToolDefinition } from "@earendil-works/pi-coding-agent";
import { truncateToWidth, wrapTextWithAnsi, type Component } from "@earendil-works/pi-tui";
import { Type, type Static } from "typebox";
import { emitResolvedAgent } from "./utilities/agent_events.ts";
import { buildLaunchEnvelope, canonicalJson, projectLaunchEnvelope, validateExecutionProfileConfig, validateLaunchEnvelope, validateOrchestrationConfig, validateOrchestrationReferences, validateRoleCatalog, type AgentDefinition, type AgentLaunchEnvelope, type RoleCatalog } from "./utilities/agent_types.ts";
import { validateModeConfig, type AgentModeConfig, type ExecutionProfileConfig } from "./utilities/mode_types.ts";
import { createActiveModeBarrier, onActiveMode, type ActiveModeBarrier, type ActiveModeEvent } from "./utilities/mode_events.ts";
import { resolveHarnessAdapter } from "./utilities/orchestration_harness.ts";
import { cleanupMeshAgents, failStartedMeshAgent, readReconciledAgentSnapshot, recoverPendingAgentStops, stopMeshAgentWithDisposition, stopMeshTaskWithDisposition } from "./utilities/orchestration_management.ts";
import { reserveNewAgentCapacityWithPressure, runPeriodicAgentGc } from "./utilities/orchestration_gc.ts";
import { awaitPressureAdmission, failOpenPressureAdmissions, processPressureAdmissions, reconcilePressureAdmissions } from "./utilities/orchestration_admission.ts";
import { exceedsModelVisibleLimit, projectDebugSnapshot, projectMeshCompletionContext, projectMeshRetrievalTask, projectMinimalAgentTask, projectMinimalSubmitResult, receiptIdsFromToolResults, sanitizeSnapshot, serializeModelVisibleJson, type AgentToolDetails, type MeshOutputMode, type SubmitDetails } from "./utilities/orchestration_projection.ts";
import { acknowledgeMeshContextInterventions, acknowledgeMeshEvents, bindMeshEndpoint, isLiveMeshEndpointBinding, markMeshEventsInjected, materializeMeshCompletionEvents, readEndpointDeliverySnapshot, registerMeshReport, registerStateAwareMeshSend, reserveNewAgentMeshSendSubmission, resolveRouteEndpoint, setMeshEndpointOffline, type FrozenTask, type MeshEndpoint, type MeshSendResult } from "./utilities/orchestration_events.ts";
import { OrchestrationDeadlineScheduler } from "./utilities/orchestration_cadence.ts";
import { createCompletionReceipt, readCompletionLedger, reconcileCompletionReceipts, rollbackCompletionReceipt, type CompletionReceiptCreationResult } from "./utilities/orchestration_completion.ts";
import { attachRootMesh, beginMeshClose, claimTaskUsage, completeMeshClose, createTask, ensurePolicyEpoch, heartbeatRootLease, initializeMesh, prepareAgent, publishAgent, readAgentSnapshot, readMesh, readPersistedCompletionReceiptEvidence, readPolicyEpoch, readTask, reconcileMeshReservations, reconcileMeshState, reconcileMeshUsageClaims, releaseMeshReservation, removePreparedAgent, taskPaths, validateStopReason } from "./utilities/orchestration_store.ts";
import { AgentLaunchCleanupError, inspectAgentTmux, inspectMeshAgentWindow, launchAgentSession, probeTmux, stopAgentSession, type CommandExecutor } from "./utilities/orchestration_tmux.ts";
import { addUsage, emptyUsage, isTerminalAgent, isTerminalTask, type AgentSnapshot, type CompletionReceiptToolName, type CompletionTarget, type PolicyEpoch, type SubagentRuntimeConfig } from "./utilities/orchestration_types.ts";
import { MeshAgentsPaletteComponent, type MeshPaletteDependencies } from "./utilities/orchestration_palette.ts";
import { MESH_PEER_TOOL_NAMES, MESH_REPORT_TOOL_NAME } from "./utilities/orchestration_pi.ts";
import { renderAgentToolResult, renderGetCall, renderMeshEventMessage, renderReportCall, renderReportResult, renderSendCall, renderSendResult, renderStopCall, renderStopResult, renderWaitCall, renderWaitResult } from "./utilities/orchestration_cards.ts";
import { openPopupView, providePopupView } from "./popup.ts";
import { loadPaletteKeymap } from "./utilities/command_palette_keymap.ts";
import { loadFeatureKeybindings } from "./utilities/extension_keybindings.ts";
import { provideCommandPaletteContribution } from "./utilities/command_palette_contributions.ts";
import { acknowledgeDisplayedTuiNotice, listPendingTuiNotices, type TuiNotice } from "./utilities/orchestration_notices.ts";
import { bindAgentRuntime } from "./utilities/orchestration_runtime.ts";
import { assertExpectedEndpointBinding } from "./utilities/orchestration_binding.ts";
import { displayIdentityForSnapshot, type AgentDisplayIdentity } from "./utilities/orchestration_identity.ts";

const CONFIG = join(getAgentDir(), "orchestration.json"); const CATALOG = join(getAgentDir(), "role-catalog.json"); const PROFILES = join(getAgentDir(), "execution-profiles.json"); const MODES = join(getAgentDir(), "agent-modes.json");
const ROOT_BINDING = "mesh-root-binding"; const POLICY_BINDING = "mesh-policy-epoch"; const PARENT_STATUS = "mesh-parent-navigation"; const PUMP_STATUS = "mesh-event-pump"; const NOTICE_PUMP_STATUS = "mesh-notice-pump"; const NOTICE_ENTRY = "mesh-tui-notice";
interface RootBinding { schemaVersion: 1; meshId: string }
interface EpochBinding { schemaVersion: 1; meshId: string; mode: string; epochId: string; policyDigest: string }
export interface ActiveCaller { identity: string; meshId: string; epoch: PolicyEpoch; catalog: RoleCatalog; envelope?: AgentLaunchEnvelope; agentId?: string; runtimeId?: string; endpointId: string; sessionFile?: string; error?: string }
export interface OrchestrationDependencies { configPath: string; catalogPath?: string; profilePath?: string; modePath?: string; env: NodeJS.ProcessEnv; exec: CommandExecutor; activeCaller?: () => ActiveCaller | undefined; authorityBarrier?: () => Promise<void>; rootLeaseId?: () => string | undefined; natureHandleWords?: () => readonly string[]; sleep?: (ms: number, signal?: AbortSignal) => Promise<void>; now?: () => number }
export interface OrchestrationRegistrationOptions extends Partial<Pick<OrchestrationDependencies, "configPath" | "catalogPath" | "profilePath" | "modePath" | "env">> { setInterval?: (callback: () => void | Promise<void>, delay: number) => unknown; clearInterval?: (timer: unknown) => void; now?: () => number; onAuthorityWait?: () => void }
export async function loadOrchestrationConfig(path: string): Promise<SubagentRuntimeConfig> { try { return validateOrchestrationConfig(JSON.parse(await readFile(path, "utf8"))); } catch (error) { throw new Error(`Cannot read orchestration config ${path}: ${error instanceof Error ? error.message : String(error)}`); } }
export async function loadRoleCatalog(path: string): Promise<RoleCatalog> { try { return validateRoleCatalog(JSON.parse(await readFile(path, "utf8"))); } catch (error) { throw new Error(`Cannot read role catalog ${path}: ${error instanceof Error ? error.message : String(error)}`); } }
export const loadAgentCatalog = loadRoleCatalog;
export async function loadExecutionProfiles(path: string): Promise<ExecutionProfileConfig> { try { return validateExecutionProfileConfig(JSON.parse(await readFile(path, "utf8"))); } catch (error) { throw new Error(`Cannot read execution profiles ${path}: ${error instanceof Error ? error.message : String(error)}`); } }
export async function loadAgentModes(path: string): Promise<AgentModeConfig> { try { return validateModeConfig(JSON.parse(await readFile(path, "utf8"))); } catch (error) { throw new Error(`Cannot read agent modes ${path}: ${error instanceof Error ? error.message : String(error)}`); } }
function sleep(ms: number, signal?: AbortSignal): Promise<void> { return new Promise((resolve, reject) => { if (signal?.aborted) return reject(signal.reason); const timer = setTimeout(resolve, ms); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(signal.reason); }, { once: true }); }); }
function active(deps: OrchestrationDependencies): ActiveCaller { const value = deps.activeCaller?.(); if (!value) throw new Error("Mesh unavailable: runtime identity is not attached"); if (value.error) throw new Error(`Mesh unavailable: ${value.error}`); return value; }
async function authorized(deps: OrchestrationDependencies): Promise<ActiveCaller> { await deps.authorityBarrier?.(); return active(deps); }
async function reauthorizeCaller(deps: OrchestrationDependencies, captured: ActiveCaller): Promise<ActiveCaller> { const current = await authorized(deps); if (current.meshId !== captured.meshId || current.agentId !== captured.agentId || current.endpointId !== captured.endpointId || current.sessionFile !== captured.sessionFile) throw new Error("Mesh caller principal changed before mutation"); return current; }
async function reauthorizeReservedCaller(deps: OrchestrationDependencies, captured: ActiveCaller): Promise<ActiveCaller> { const current = await reauthorizeCaller(deps, captured); if (current.epoch.epochId !== captured.epoch.epochId || current.epoch.policyDigest !== captured.epoch.policyDigest) throw new Error("Mesh caller authority changed after capacity reservation"); return current; }
function asRecord(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? { ...(value as Record<string, unknown>) } : {}; }
function prepareRetrievalArguments<T>(value: unknown): T { const args = asRecord(value); return { ...args, outputMode: args.outputMode ?? "compact" } as T; }
function canonicalRetrievalArguments<T extends { outputMode?: MeshOutputMode }>(value: T): Omit<T, "outputMode"> | T { if (value.outputMode !== "compact") return value; const { outputMode: _default, ...legacyCompatible } = value; return legacyCompatible; }
function branchData<T>(ctx: ExtensionContext, customType: string): T | undefined { const entry = [...ctx.sessionManager.getBranch()].reverse().find(item => item.type === "custom" && item.customType === customType) as { data?: unknown } | undefined; return entry?.data as T | undefined; }
function errorText(value: unknown): string { return value instanceof Error ? value.message : typeof value === "string" ? value : JSON.stringify(value) ?? "Unknown error"; }
function callerPolicy(caller: ActiveCaller) { return caller.agentId ? caller.envelope?.policies[caller.envelope.role] ?? { targets: {} } : { targets: caller.epoch.directTargets }; }
function callerRoles(caller: ActiveCaller): Record<string, AgentDefinition> { return caller.agentId ? caller.envelope?.roles ?? {} : caller.epoch.roles; }
function callerProfiles(caller: ActiveCaller) { return caller.agentId ? caller.envelope?.profiles ?? {} : caller.epoch.profiles; }
function roleTargets(caller: ActiveCaller): Record<string, AgentDefinition> { const roles = callerRoles(caller); return Object.fromEntries(Object.keys(callerPolicy(caller).targets).map(name => [name, roles[name]!]).filter(([, definition]) => definition)); }
function targetProfiles(caller: ActiveCaller): Record<string, string[]> { return Object.fromEntries(Object.entries(callerPolicy(caller).targets).map(([name, edge]) => [name, [...edge.profiles]])); }
function requester(caller: ActiveCaller): { requesterEndpointId: string; requesterAgentId?: string } { return { requesterEndpointId: caller.endpointId, ...(caller.agentId ? { requesterAgentId: caller.agentId } : {}) }; }
function dispatchAuthority(caller: ActiveCaller, targetRole: string, selectedProfile: string) { return { ...requester(caller), ...(caller.sessionFile ? { requesterEndpointSessionFile: caller.sessionFile } : {}), ...(caller.agentId && caller.runtimeId ? { requesterRuntimeId: caller.runtimeId } : {}), epochId: caller.epoch.epochId, policyDigest: caller.epoch.policyDigest, targetRole, selectedProfile }; }
function authorizeDirectRole(caller: ActiveCaller, role: string, action: string): { definition: AgentDefinition; profiles: string[] } { const definition = callerRoles(caller)[role]; const edge = callerPolicy(caller).targets[role]; if (!definition || !edge) throw new Error(`${caller.identity} is not allowed to ${action} role ${role}`); return { definition, profiles: edge.profiles }; }
function resolveSelectedProfile(caller: ActiveCaller, role: string, requestedProfile: string | undefined, action: string) { const edge = authorizeDirectRole(caller, role, action); let selectedProfile: string; if (edge.profiles.length === 1) { if (requestedProfile !== undefined) throw new Error(`Role ${role} has a fixed profile and rejects an explicit profile`); selectedProfile = edge.profiles[0]!; } else { if (requestedProfile === undefined) throw new Error(`Role ${role} requires an explicit profile`); if (!edge.profiles.includes(requestedProfile)) throw new Error(`${caller.identity} is not allowed to ${action} role ${role} with profile ${requestedProfile}`); selectedProfile = requestedProfile; } const profile = callerProfiles(caller)[selectedProfile]; if (!profile) throw new Error(`Profile ${selectedProfile} is outside the immutable caller policy`); return { definition: edge.definition, selectedProfile, profile, authorizedProfiles: edge.profiles }; }
function authorizeTask(caller: ActiveCaller, task: Awaited<ReturnType<typeof readTask>>, action: string): void { if (!caller.agentId) return; if (task.request.requesterAgentId !== caller.agentId || task.request.requesterEndpointId !== caller.endpointId) throw new Error(`${caller.identity} is not allowed to ${action} task ${task.request.taskId}`); }
function authorizeAgent(caller: ActiveCaller, snapshot: AgentSnapshot, action: string): void { if (!caller.agentId) return; if (snapshot.agent.parentAgentId !== caller.agentId) throw new Error(`${caller.identity} is not allowed to ${action} agent ${snapshot.agent.agentId}; caller is not its direct parent`); }
function authorizeReuse(caller: ActiveCaller, snapshot: AgentSnapshot): void { const edge = authorizeDirectRole(caller, snapshot.agent.role, "reuse"); const profile = callerProfiles(caller)[snapshot.agent.selectedProfile]; if (!edge.profiles.includes(snapshot.agent.selectedProfile) || canonicalJson(snapshot.agent.roleSnapshot) !== canonicalJson(edge.definition) || canonicalJson(snapshot.agent.profileSnapshot) !== canonicalJson(profile)) throw new Error(`Agent ${snapshot.agent.agentId} does not match the current immutable role/profile edge`); }
function rejectSelfAgent(caller: ActiveCaller, agentId: string, operation: string): void { if (caller.agentId === agentId) throw new Error(`mesh_${operation} cannot target the calling agent itself (${agentId})`); }
export function tuiNoticeText(notice: TuiNotice, expanded = false): string {
    if (notice.kind === "explicit-stop") {
        const summary = `Agent stopped · ${notice.payload.role} · ${notice.payload.reason}`;
        return expanded ? `${summary}\nagentId: ${notice.payload.agentId}\nsource: ${notice.payload.source}\nnoticeId: ${notice.noticeId}` : summary;
    }
    const summary = `Mesh GC · ${notice.payload.confirmed.length} stopped · ${notice.payload.failedCount} failed · ${notice.payload.pendingCount} pending`;
    const agents = notice.payload.confirmed.map(item => `${item.role} ${item.agentId} · ${item.source} · ${item.reason}`);
    return expanded ? [summary, ...agents, `noticeId: ${notice.noticeId}`].join("\n") : summary;
}
export function renderTuiNotice(notice: TuiNotice, expanded: boolean, theme: ExtensionContext["ui"]["theme"]): Component {
    return { invalidate() {}, render(width: number) { const text = theme.fg(notice.kind === "explicit-stop" ? "warning" : "accent", tuiNoticeText(notice, expanded)); return wrapTextWithAnsi(text, Math.max(1, width)).map(line => truncateToWidth(line, Math.max(1, width), "")); } };
}

type MeshSendParameters = { agent?: string; agentId?: string; profile?: string; message: string };
const sendParametersFor = (targets: Readonly<Record<string, AgentDefinition>>, profiles: Readonly<Record<string, readonly string[]>>) => {
    const message = Type.String({ minLength: 1 });
    const variants = Object.entries(targets).map(([name, definition]) => {
        const authorized = profiles[name] ?? [];
        return Type.Object({ agent: Type.Literal(name, { description: definition.description }), ...(authorized.length > 1 ? { profile: StringEnum(authorized, { description: `Authorized execution profile for ${name}` }) } : {}), message }, { additionalProperties: false });
    });
    variants.push(Type.Object({ agentId: Type.String(), message }, { additionalProperties: false }) as never);
    return Type.Union(variants);
};
const outputMode = () => Type.Optional(StringEnum(["compact", "full"] as const, { default: "compact", description: "Terminal result projection; compact may advertise fullOutputAvailable." }));
const getParameters = Type.Object({ taskId: Type.String(), outputMode: outputMode() }, { additionalProperties: false });
const waitParameters = Type.Object({ taskIds: Type.Array(Type.String(), { minItems: 1, maxItems: 16, uniqueItems: true }), outputMode: outputMode() }, { additionalProperties: false });
const stopParameters = Type.Object({ agentId: Type.Optional(Type.String()), taskId: Type.Optional(Type.String()), reason: Type.Optional(Type.String()) }, { additionalProperties: false });
const reportParameters = Type.Object({ summary: Type.String({ minLength: 1 }) }, { additionalProperties: false });
type SendSelector = { kind: "new"; agent: string; profile?: string } | { kind: "existing"; agentId: string };
function exactSelector(value: { agent?: string; agentId?: string; profile?: string }, tool: string): SendSelector { if (value.agentId !== undefined) { if (value.agent !== undefined || value.profile !== undefined) throw new Error(`${tool} agentId cannot be combined with agent or profile`); return { kind: "existing", agentId: value.agentId }; } if (value.agent === undefined) throw new Error(`${tool} requires agent or agentId`); return { kind: "new", agent: value.agent, ...(value.profile === undefined ? {} : { profile: value.profile }) }; }

type Accounting = { usage?: Usage; claimedTaskIds: string[]; receiptIds: string[]; receivedTaskIds: string[] };
const emptyAccounting = (): Accounting => ({ claimedTaskIds: [], receiptIds: [], receivedTaskIds: [] });
type TerminalReception = { snapshots: AgentSnapshot[]; accounting: Accounting };
async function receiveTerminalSnapshots(config: SubagentRuntimeConfig, caller: ActiveCaller, toolCallId: string, toolName: CompletionReceiptToolName, canonicalArguments: unknown, rawSnapshots: readonly AgentSnapshot[], receiptResult?: CompletionReceiptCreationResult, signal?: AbortSignal): Promise<TerminalReception> {
    signal?.throwIfAborted();
    let snapshots = rawSnapshots.map(sanitizeSnapshot);
    for (const snapshot of snapshots) if (!snapshot.task?.result || !isTerminalTask(snapshot.task.status.state)) throw new Error(`Task ${snapshot.task?.request.taskId ?? "unknown"} is not terminal`);
    const routed = snapshots.filter(snapshot => snapshot.task?.request.completion !== undefined);
    if (routed.length !== 0 && routed.length !== snapshots.length) throw new Error(`${toolName} cannot combine routed and historical tasks`);
    if (!caller.sessionFile) { if (routed.length) throw new Error(`${toolName} requires a durable caller session`); return { snapshots, accounting: emptyAccounting() }; }
    const mesh = await readMesh(config.stateRoot, caller.meshId);
    signal?.throwIfAborted();
    let receipt = receiptResult;
    if (!receipt && routed.length) receipt = await createCompletionReceipt(config.stateRoot, caller.meshId, { endpointId: caller.endpointId, endpointSessionFile: caller.sessionFile, claimantSessionFile: caller.sessionFile, toolCallId, toolName, canonicalArguments, taskIds: snapshots.map(snapshot => snapshot.task!.request.taskId), maxTasksPerMesh: mesh.budgets.maxTasksPerMesh });
    if (toolName === "mesh_get" && receipt?.receipt && !receipt.created && receipt.receipt.taskIds.some((taskId, index) => snapshots[index]?.task?.request.taskId !== taskId)) snapshots = await Promise.all(receipt.receipt.taskIds.map(async taskId => { const task = await readTask(config.stateRoot, caller.meshId, taskId); authorizeTask(caller, task, "retry receipt task"); return sanitizeSnapshot(await readAgentSnapshot(config.stateRoot, caller.meshId, task.request.agentId, taskId)); }));
    const newlyReceived = receipt ? new Set(receipt.receivedTaskIds) : new Set(snapshots.map(snapshot => snapshot.task!.request.taskId));
    const claimedTaskIds: string[] = []; const aggregate = emptyUsage();
    try {
        signal?.throwIfAborted();
        for (const snapshot of snapshots) { serializeModelVisibleJson(projectMinimalAgentTask(snapshot)); serializeModelVisibleJson(projectDebugSnapshot(snapshot)); }
        serializeModelVisibleJson({ tasks: snapshots.map(projectMinimalAgentTask) });
        for (const snapshot of snapshots) {
            signal?.throwIfAborted();
            const taskId = snapshot.task!.request.taskId;
            if (!newlyReceived.has(taskId) || !snapshot.agent.capabilities.usage) continue;
            const claimed = await claimTaskUsage(config.stateRoot, caller.meshId, taskId, caller.sessionFile, toolCallId, toolName);
            signal?.throwIfAborted();
            if (claimed.created) { claimedTaskIds.push(taskId); addUsage(aggregate, claimed.result.usage); }
        }
        signal?.throwIfAborted();
    } catch (error) {
        if (receipt?.created && receipt.receipt) await rollbackCompletionReceipt(config.stateRoot, caller.meshId, { endpointId: caller.endpointId, endpointSessionFile: caller.sessionFile, receiptId: receipt.receipt.receiptId }).catch(() => {});
        throw error;
    }
    const accounting: Accounting = { claimedTaskIds, receiptIds: receipt?.receipt ? [receipt.receipt.receiptId] : [], receivedTaskIds: receipt?.receivedTaskIds ?? [], ...(claimedTaskIds.length ? { usage: aggregate } : {}) };
    return { snapshots, accounting };
}
function agentResult(raw: AgentSnapshot, accounting: Accounting, debug = false, outputMode: MeshOutputMode = "compact") { const snapshot = sanitizeSnapshot(raw); const details: AgentToolDetails = { ...snapshot, accounting }; const projected = debug ? projectDebugSnapshot(snapshot) : snapshot.task?.result && isTerminalTask(snapshot.task.status.state) ? projectMeshRetrievalTask(snapshot, outputMode) : projectMinimalAgentTask(snapshot); return { content: [{ type: "text" as const, text: serializeModelVisibleJson(projected, { fullOutputAvailableOnTruncation: !debug && outputMode === "compact" }) }], details, usage: accounting.usage }; }
function attachDisplayIdentity<T extends object>(details: T, snapshot: AgentSnapshot, words?: readonly string[]): T & { displayIdentity: AgentDisplayIdentity } {
    return { ...details, displayIdentity: displayIdentityForSnapshot(snapshot, words) };
}
function attachDisplayIdentities<T extends object>(details: T, identities: Record<string, AgentDisplayIdentity>): T & { identities: Record<string, AgentDisplayIdentity> } {
    return { ...details, identities };
}
async function liveCompletionTarget(config: SubagentRuntimeConfig, caller: ActiveCaller): Promise<CompletionTarget> { if (!caller.sessionFile) throw new Error("mesh_send requires a durable caller session"); const endpoint = await resolveRouteEndpoint(config.stateRoot, caller.meshId, "self", caller.agentId); if (!endpoint.online || endpoint.endpointId !== caller.endpointId || endpoint.sessionFile !== caller.sessionFile || !await isLiveMeshEndpointBinding(config.stateRoot, caller.meshId, endpoint)) throw new Error("mesh_send requires a live durable self endpoint"); return { endpointId: caller.endpointId, endpointSessionFile: caller.sessionFile }; }
async function stopPreparedLaunch(deps: OrchestrationDependencies, tmuxCommand: string, tmux: NonNullable<Awaited<ReturnType<typeof launchAgentSession>>>): Promise<void> { let stopFailure: unknown; try { if (await stopAgentSession(deps.exec, tmuxCommand, tmux)) return; } catch (error) { stopFailure = error; } const inspected = await inspectAgentTmux(deps.exec, tmuxCommand, tmux).catch(error => { stopFailure ??= error; return undefined; }); const confirmed = inspected && (inspected.server === "absent" || inspected.server === "mismatch" || inspected.server === "match" && inspected.paneState === "dead"); if (!confirmed) throw new Error("Could not confirm that the pre-publication agent process stopped", { cause: stopFailure }); }

async function startAgentSubmission(deps: OrchestrationDependencies, config: SubagentRuntimeConfig, capturedCaller: ActiveCaller, params: MeshSendParameters & { role: string; completion: CompletionTarget; requestedProfile?: string; agentId: string; taskId: string }, signal: AbortSignal | undefined, ctx: ExtensionContext): Promise<AgentSnapshot> {
    if (signal?.aborted) throw signal.reason;
    // Cross the current authority barrier again immediately before capacity reservation.
    // Everything persisted below is derived from this current caller, never the earlier tool snapshot.
    const caller = await reauthorizeCaller(deps, capturedCaller);
    const resolved = resolveSelectedProfile(caller, params.role, params.requestedProfile, "start");
    const { definition, selectedProfile, profile, authorizedProfiles } = resolved;
    const reservation = caller.agentId
        ? await awaitPressureAdmission(config.stateRoot, caller.meshId, { requestId: randomUUID(), requesterAgentId: caller.agentId, requesterRuntimeId: caller.runtimeId ?? "", expectedBinding: { endpointId: caller.endpointId, endpointSessionFile: caller.sessionFile! }, signal, sleep: milliseconds => (deps.sleep ?? sleep)(milliseconds) })
        : await reserveNewAgentCapacityWithPressure({ stateRoot: config.stateRoot, meshId: caller.meshId, leaseId: deps.rootLeaseId?.() ?? "", gc: config.gc, exec: deps.exec, tmux: config.tmux, expectedCurrentEpochId: caller.epoch.epochId }, undefined, undefined, undefined, { endpointId: caller.endpointId, endpointSessionFile: caller.sessionFile! });
    try { await reauthorizeReservedCaller(deps, caller); } catch (error) { await releaseMeshReservation(config.stateRoot, caller.meshId, reservation.reservationId, "authority changed after reservation"); throw error; }
    const { agentId, taskId } = params; const harness = resolveHarnessAdapter(config, profile.harness, profile); const tmuxContext = await probeTmux(deps.exec, config.tmux, deps.env); if (!tmuxContext) { await releaseMeshReservation(config.stateRoot, caller.meshId, reservation.reservationId, "tmux unavailable"); throw new Error("Mesh agent start requires a usable current tmux context"); }
    const roles = callerRoles(caller); const childExtensions = Object.fromEntries(Object.keys(roles).map(name => [name, caller.envelope?.childExtensions[name] ?? [config.popupExtension, config.orchestrationExtension, ...(roles[name]?.childExtensionContributions ?? []), config.childBridgeExtension]]));
    const envelope = caller.envelope
        ? projectLaunchEnvelope(params.role, agentId, caller.envelope, selectedProfile)
        : buildLaunchEnvelope({ meshId: caller.meshId, agentId, epochId: caller.epoch.epochId, role: params.role, selectedProfile, authorizedProfiles, snapshot: caller.epoch, childExtensions });
    const prepared = await prepareAgent(config.stateRoot, caller.meshId, { reservationId: reservation.reservationId, agentId, role: params.role, selectedProfile, harness: profile.harness, cwd: ctx.cwd, roleSnapshot: definition, profileSnapshot: profile, launchEnvelope: "pending", epochId: caller.epoch.epochId, provenance: { parentAgentId: caller.agentId, creatorSessionId: ctx.sessionManager.getSessionId(), ...(caller.sessionFile ? { creatorSessionFile: caller.sessionFile } : {}) }, capabilities: harness.adapter.capabilities, authority: dispatchAuthority(caller, params.role, selectedProfile) });
    const envelopePath = join(prepared.paths.directory, "launch-envelope.json"); let tmux; let published = false; let taskCreated = false;
    try {
        await writeFile(envelopePath, `${JSON.stringify(envelope, null, 2)}\n`, { mode: 0o600 });
        const launch = harness.adapter.launch(config, harness.harness, { meshId: caller.meshId, agentId, agentDirectory: prepared.paths.directory, role: params.role, taskPath: taskPaths(config.stateRoot, caller.meshId, taskId).directory, launchEnvelope: envelopePath, epochSnapshot: envelope, cwd: ctx.cwd });
        await assertExpectedEndpointBinding(config.stateRoot, caller.meshId, { endpointId: caller.endpointId, endpointSessionFile: caller.sessionFile! });
        tmux = await launchAgentSession(deps.exec, config.tmux, tmuxContext, { meshId: caller.meshId, epochId: caller.epoch.epochId, agentId, agent: params.role, cwd: ctx.cwd, launch });
        await publishAgent(config.stateRoot, caller.meshId, prepared.paths, { agentId, epochId: caller.epoch.epochId, role: params.role, selectedProfile, harness: profile.harness, cwd: ctx.cwd, roleSnapshot: definition, profileSnapshot: profile, launchEnvelope: envelopePath, tmux, tmuxOwnership: "mesh-hub", capabilities: harness.adapter.capabilities, parentAgentId: caller.agentId, creatorSessionId: ctx.sessionManager.getSessionId(), ...(caller.sessionFile ? { creatorSessionFile: caller.sessionFile } : {}) }, dispatchAuthority(caller, params.role, selectedProfile)); published = true;
        const task = await createTask(config.stateRoot, caller.meshId, agentId, params.message, { ...requester(caller), completion: params.completion }, reservation.reservationId, taskId, dispatchAuthority(caller, params.role, selectedProfile)); taskCreated = true; let snapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, agentId, task.request.taskId);
        const deadline = (deps.now ?? (() => performance.now()))() + (harness.harness.bridgeReadyTimeoutMs ?? 5000); while ((deps.now ?? (() => performance.now()))() < deadline) { if (signal?.aborted) throw signal.reason; snapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, agentId, taskId); if (isTerminalAgent(snapshot.status.state)) throw new Error(snapshot.status.exitReason ?? `Agent became ${snapshot.status.state} during startup`); if (snapshot.status.bridgeReady) return readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, agentId, taskId); await (deps.sleep ?? sleep)(50, signal); } throw new Error("Agent bridge readiness timed out");
    } catch (error) {
        let cleanupError: unknown;
        if (published) try { await failStartedMeshAgent({ stateRoot: config.stateRoot, meshId: caller.meshId, agentId, exec: deps.exec, tmux: config.tmux }, errorText(error)); } catch (failure) { cleanupError = failure; }
        else { let confirmed = tmux === undefined && !(error instanceof AgentLaunchCleanupError); if (tmux) try { await stopPreparedLaunch(deps, config.tmux, tmux); confirmed = true; } catch (failure) { cleanupError = failure; } else if (!confirmed) cleanupError = error; if (confirmed) await removePreparedAgent(config.stateRoot, caller.meshId, agentId, reservation.reservationId, "launch failed"); }
        if (cleanupError) throw new Error(`${errorText(error)}; cleanup for agent ${agentId} remains incomplete: ${errorText(cleanupError)}`); if (!taskCreated) await releaseMeshReservation(config.stateRoot, caller.meshId, reservation.reservationId, "launch failed before task commit").catch(() => {}); throw error;
    }
}

type StagedMeshSendActivation = (caller: ActiveCaller) => Promise<void>;
function submittedSendResult(raw: AgentSnapshot) { const snapshot = sanitizeSnapshot(raw); const details: SubmitDetails = { ...snapshot, accounting: emptyAccounting() }; return { content: [{ type: "text" as const, text: serializeModelVisibleJson({ disposition: "submitted", ...projectMinimalSubmitResult(snapshot) }) }], details }; }
function intervenedSendResult(result: Extract<MeshSendResult, { disposition: "intervened" }>, snapshot: AgentSnapshot, words?: readonly string[]) { return { content: [{ type: "text" as const, text: serializeModelVisibleJson(result) }], details: attachDisplayIdentity({ ...result }, snapshot, words) }; }
export function createMeshSendTool(deps: OrchestrationDependencies, targets: Readonly<Record<string, AgentDefinition>> = {}, profiles: Readonly<Record<string, readonly string[]>> = {}, stagedActivation?: StagedMeshSendActivation): ToolDefinition { return defineTool({ name: "mesh_send", label: "Send mesh work", description: "Create an authorized task or durably intervene in a direct child’s active task.", promptSnippet: "Send mesh work", promptGuidelines: ["Use mesh_send for independent work. An agent ID send is durably accepted as either a new task or an intervention; retain the returned IDs. Treat completion delivery as the result frontier and do not poll pending tasks."], parameters: sendParametersFor(targets, profiles), executionMode: "sequential", renderCall: renderSendCall, renderResult: (result, options, theme, context) => renderSendResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(toolCallId, rawParams, signal, _update, ctx) { const params = rawParams as MeshSendParameters; const target = exactSelector(params, "mesh_send"); const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); if (target.kind === "new") resolveSelectedProfile(caller, target.agent, target.profile, "start"); const completion = await liveCompletionTarget(config, caller); let storedTarget: AgentSnapshot | undefined; if (target.kind === "existing") { rejectSelfAgent(caller, target.agentId, "send"); storedTarget = await readAgentSnapshot(config.stateRoot, caller.meshId, target.agentId); authorizeAgent(caller, storedTarget, "send to"); authorizeReuse(caller, storedTarget); }
        const mutationCaller = stagedActivation ? await reauthorizeCaller(deps, caller) : caller; await stagedActivation?.(mutationCaller);
        if (target.kind === "new") { const reservation = await reserveNewAgentMeshSendSubmission(config.stateRoot, mutationCaller.meshId, { callerEndpointId: mutationCaller.endpointId, callerEndpointSessionFile: mutationCaller.sessionFile!, toolCallId, canonicalArguments: params }); if (!reservation.created) { const task = await readTask(config.stateRoot, mutationCaller.meshId, reservation.result.taskId).catch(error => (error as NodeJS.ErrnoException).code === "ENOENT" ? undefined : Promise.reject(error)); if (task) return submittedSendResult(await readAgentSnapshot(config.stateRoot, mutationCaller.meshId, task.request.agentId, task.request.taskId)); }
            const snapshot = await startAgentSubmission(deps, config, mutationCaller, { ...params, role: target.agent, requestedProfile: target.profile, completion, agentId: reservation.result.agentId, taskId: reservation.result.taskId }, signal, ctx); return submittedSendResult(snapshot); }
        authorizeAgent(mutationCaller, storedTarget!, "send to"); authorizeReuse(mutationCaller, storedTarget!); const endpoint = storedTarget!.agent.capabilities.interactiveInterventions ? await resolveRouteEndpoint(config.stateRoot, mutationCaller.meshId, target.agentId) : undefined; const result = await registerStateAwareMeshSend(config.stateRoot, mutationCaller.meshId, { callerEndpointId: mutationCaller.endpointId, callerEndpointSessionFile: mutationCaller.sessionFile!, toolCallId, canonicalArguments: params, ...(endpoint ? { endpoint } : {}), agentId: target.agentId, message: params.message, completion, authority: dispatchAuthority(mutationCaller, storedTarget!.agent.role, storedTarget!.agent.selectedProfile) });
        return result.disposition === "intervened" ? intervenedSendResult(result, storedTarget!, deps.natureHandleWords?.()) : submittedSendResult(await readAgentSnapshot(config.stateRoot, mutationCaller.meshId, result.agentId, result.taskId));
    } }); }
export function createMeshGetTool(deps: OrchestrationDependencies): ToolDefinition<typeof getParameters, unknown> { return defineTool({ name: "mesh_get", label: "Get mesh task result", description: "Receive one terminal mesh task result; pending tasks return not-ready without a receipt.", promptSnippet: "Receive a terminal mesh result", parameters: getParameters, executionMode: "sequential", prepareArguments: args => prepareRetrievalArguments<Static<typeof getParameters>>(args), renderCall: renderGetCall, renderResult: (result, options, theme, context) => renderAgentToolResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params, signal) { const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); const record = await readTask(config.stateRoot, caller.meshId, params.taskId); authorizeTask(caller, record, "inspect"); const snapshot = await readReconciledAgentSnapshot(deps.exec, config.tmux, config.stateRoot, caller.meshId, record.request.agentId, params.taskId); const terminal = Boolean(snapshot.task?.result && isTerminalTask(snapshot.task.status.state)); if (!terminal) return { content: [{ type: "text" as const, text: serializeModelVisibleJson({ taskId: params.taskId, taskState: snapshot.task?.status.state ?? "created", resultAvailable: false }) }], details: sanitizeSnapshot(snapshot) };
        const reception = await receiveTerminalSnapshots(config, caller, id, "mesh_get", canonicalRetrievalArguments(params), [snapshot], undefined, signal); return agentResult(reception.snapshots[0]!, reception.accounting, false, params.outputMode ?? "compact"); } }); }

type WaitForTerminalSnapshots = (config: SubagentRuntimeConfig, caller: ActiveCaller, taskIds: readonly string[], signal: AbortSignal | undefined) => Promise<AgentSnapshot[]>;
type WaitLifecycleSignal = () => AbortSignal;
async function immediateTerminalSnapshots(config: SubagentRuntimeConfig, caller: ActiveCaller, taskIds: readonly string[], signal?: AbortSignal): Promise<AgentSnapshot[]> { signal?.throwIfAborted(); const snapshots = await Promise.all(taskIds.map(async taskId => { const task = await readTask(config.stateRoot, caller.meshId, taskId); authorizeTask(caller, task, "wait for"); return readAgentSnapshot(config.stateRoot, caller.meshId, task.request.agentId, taskId); })); signal?.throwIfAborted(); if (snapshots.some(snapshot => !snapshot.task?.result || !isTerminalTask(snapshot.task.status.state))) throw new Error("mesh_wait runtime barrier is unavailable for nonterminal tasks"); return snapshots; }
export function createMeshWaitTool(deps: OrchestrationDependencies, waitForTerminal: WaitForTerminalSnapshots = immediateTerminalSnapshots, lifecycleSignal?: WaitLifecycleSignal): ToolDefinition<typeof waitParameters, unknown> { return defineTool({ name: "mesh_wait", label: "Wait for mesh tasks", description: "Wait for descendant tasks and return terminal results in input order; available only to nested callers with outbound edges.", promptSnippet: "Await descendant results", parameters: waitParameters, executionMode: "sequential", prepareArguments: args => prepareRetrievalArguments<Static<typeof waitParameters>>(args), renderCall: renderWaitCall, renderResult: (result, options, theme, context) => renderWaitResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params, signal) { const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); if (!caller.agentId || !caller.envelope || !caller.sessionFile || !authorizedMeshTools(caller).length) throw new Error("mesh_wait is available only to a durable nested Pi caller with outbound mesh edges"); const endpoint = await resolveRouteEndpoint(config.stateRoot, caller.meshId, "self", caller.agentId); if (!endpoint.online || endpoint.endpointId !== caller.endpointId || endpoint.sessionFile !== caller.sessionFile || !await isLiveMeshEndpointBinding(config.stateRoot, caller.meshId, endpoint)) throw new Error("mesh_wait requires a live durable child endpoint session"); const effectiveSignal = lifecycleSignal ? signal ? AbortSignal.any([signal, lifecycleSignal()]) : lifecycleSignal() : signal; effectiveSignal?.throwIfAborted(); const snapshots = await waitForTerminal(config, caller, params.taskIds, effectiveSignal); effectiveSignal?.throwIfAborted(); const reception = await receiveTerminalSnapshots(config, caller, id, "mesh_wait", canonicalRetrievalArguments(params), snapshots, undefined, effectiveSignal); const details = { tasks: reception.snapshots, accounting: reception.accounting }; const mode = params.outputMode ?? "compact"; return { content: [{ type: "text" as const, text: serializeModelVisibleJson({ tasks: reception.snapshots.map(snapshot => projectMeshRetrievalTask(snapshot, mode)) }, { fullOutputAvailableOnTruncation: mode === "compact" }) }], details, usage: reception.accounting.usage }; } }); }
export function createMeshStopTool(deps: OrchestrationDependencies): ToolDefinition<typeof stopParameters, unknown> { return defineTool({ name: "mesh_stop", label: "Stop mesh task or agent", description: "Stop one task or agent; stopping a task leaves its agent reusable.", promptSnippet: "Stop a mesh task or agent", parameters: stopParameters, executionMode: "sequential", prepareArguments: args => asRecord(args) as Static<typeof stopParameters>, renderCall: renderStopCall, renderResult: (result, options, theme, context) => renderStopResult(result, options, theme, context, deps.natureHandleWords?.()), async execute(id, params) { const hasAgent = params.agentId !== undefined; const hasTask = params.taskId !== undefined; if (hasAgent === hasTask) throw new Error("mesh_stop requires exactly one of agentId or taskId"); if (hasTask && params.reason !== undefined) throw new Error("mesh_stop taskId rejects reason"); const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); let snapshot: AgentSnapshot; let disposition; if (params.agentId) { rejectSelfAgent(caller, params.agentId, "stop"); const stored = await readAgentSnapshot(config.stateRoot, caller.meshId, params.agentId); authorizeAgent(caller, stored, "stop"); const reason = validateStopReason(params.reason ?? "Stopped by mesh peer"); const result = await stopMeshAgentWithDisposition({ stateRoot: config.stateRoot, meshId: caller.meshId, agentId: params.agentId, exec: deps.exec, tmux: config.tmux, source: "peer", reason, requesterEndpointId: caller.endpointId }); snapshot = result.snapshot; disposition = result.disposition; } else { const task = await readTask(config.stateRoot, caller.meshId, params.taskId!); authorizeTask(caller, task, "stop"); const result = await stopMeshTaskWithDisposition({ stateRoot: config.stateRoot, meshId: caller.meshId, taskId: params.taskId!, requesterEndpointId: caller.endpointId }); snapshot = result.snapshot; disposition = result.disposition; } const sanitized = sanitizeSnapshot(snapshot); const details = { ...sanitized, accounting: { claimedTaskIds: [] }, stopDisposition: disposition }; return { content: [{ type: "text" as const, text: serializeModelVisibleJson({ agentId: sanitized.agent.agentId, agent: sanitized.agent.role, agentState: sanitized.status.state, ...(sanitized.task ? { taskId: sanitized.task.request.taskId, taskState: sanitized.task.status.state } : {}), stopDisposition: disposition }) }], details }; } }); }

export function createMeshReportTool(deps: OrchestrationDependencies): ToolDefinition<typeof reportParameters, unknown> { return defineTool({ name: MESH_REPORT_TOOL_NAME, label: "Report mesh progress", description: "Report a decision-relevant progress summary to the direct parent of the active task.", promptSnippet: "Report mesh progress", promptGuidelines: ["Use mesh_report only when the parent requested progress or an intermediate result can change its parallel decision. Do not use it as a heartbeat, final result substitute, or synchronous question."], parameters: reportParameters, executionMode: "sequential", prepareArguments: args => asRecord(args) as Static<typeof reportParameters>, renderCall: renderReportCall, renderResult: renderReportResult, async execute(toolCallId, params) { const config = await loadOrchestrationConfig(deps.configPath); const caller = await authorized(deps); if (!caller.agentId || !caller.sessionFile) throw new Error("mesh_report is available only to a durable child active task"); const callerSnapshot = await readAgentSnapshot(config.stateRoot, caller.meshId, caller.agentId); const currentTaskId = callerSnapshot.status.activeTaskId; if (!currentTaskId) throw new Error("mesh_report requires an active task"); const task = await readTask(config.stateRoot, caller.meshId, currentTaskId); if (isTerminalTask(task.status.state) || task.request.requesterAgentId === caller.agentId || !task.request.completion) throw new Error("mesh_report requires a nonterminal task with a direct parent completion route"); const parent = await resolveRouteEndpoint(config.stateRoot, caller.meshId, "parent", caller.agentId); if (!parent.online || parent.endpointId !== task.request.completion.endpointId || parent.sessionFile !== task.request.completion.endpointSessionFile) throw new Error("mesh_report direct parent endpoint is unavailable or changed"); const result = await registerMeshReport(config.stateRoot, caller.meshId, { callerEndpointId: caller.endpointId, callerEndpointSessionFile: caller.sessionFile, toolCallId, endpoint: parent, agentId: caller.agentId, taskId: currentTaskId, summary: params.summary, canonicalArguments: params }); const details = attachDisplayIdentity({ reportId: result.reportId, taskId: currentTaskId, state: "queued" as const }, callerSnapshot, deps.natureHandleWords?.()); return { content: [{ type: "text" as const, text: serializeModelVisibleJson({ reportId: result.reportId, taskId: currentTaskId, state: "queued" }) }], details }; } }); }

export async function stopPaletteMeshAgent(deps: OrchestrationDependencies, config: SubagentRuntimeConfig, request: { meshId: string; agentId: string; reason: string }): Promise<AgentSnapshot> { const caller = await authorized(deps); const snapshot = await readAgentSnapshot(config.stateRoot, request.meshId, request.agentId); authorizeAgent(caller, snapshot, "stop"); rejectSelfAgent(caller, request.agentId, "stop"); const reason = validateStopReason(request.reason, "Palette stop reason"); return (await stopMeshAgentWithDisposition({ stateRoot: config.stateRoot, meshId: request.meshId, agentId: request.agentId, exec: deps.exec, tmux: config.tmux, source: "user", reason, requesterEndpointId: caller.endpointId })).snapshot; }

function authorizedMeshTools(caller: ActiveCaller): string[] { return Object.keys(callerPolicy(caller).targets).length ? [...MESH_PEER_TOOL_NAMES] : []; }
function activateMeshPeerTools(pi: ExtensionAPI, caller: ActiveCaller): void { const names = authorizedMeshTools(caller); if (!names.length) throw new Error(`${caller.identity} has no authorized mesh edges`); const all = new Set(pi.getAllTools().map(tool => tool.name)); const missing = names.filter(name => !all.has(name)); if (missing.length) throw new Error(`Mesh activation unavailable; child process restart required; tools not registered: ${missing.join(", ")}`); const current = pi.getActiveTools(); pi.setActiveTools([...new Set([...current, ...names])]); const activeNow = new Set(pi.getActiveTools()); const failed = names.filter(name => !activeNow.has(name)); if (failed.length) throw new Error(`Mesh activation incomplete: ${failed.join(", ")}`); }

export async function activateMeshPeerToolsForSend(pi: ExtensionAPI, caller: ActiveCaller, persist: () => Promise<void>): Promise<void> {
    const previous = pi.getActiveTools();
    try { activateMeshPeerTools(pi, caller); await persist(); }
    catch (error) {
        try {
            pi.setActiveTools(previous);
            const restored = pi.getActiveTools();
            if (restored.length !== previous.length || restored.some((name, index) => name !== previous[index])) throw new Error("active tool set did not return to its previous state");
        } catch (rollbackError) { throw new Error(`${errorText(error)}; mesh tool rollback failed: ${errorText(rollbackError)}`, { cause: error }); }
        throw error;
    }
}

export async function registerOrchestration(pi: ExtensionAPI, options: OrchestrationRegistrationOptions = {}): Promise<boolean> {
    pi.registerEntryRenderer(NOTICE_ENTRY, (entry, renderOptions, theme) => renderTuiNotice(entry.data as TuiNotice, renderOptions.expanded, theme));
    loadFeatureKeybindings("meshPalette"); loadFeatureKeybindings("tmuxPreview"); const configPath = options.configPath ?? CONFIG; const catalogPath = options.catalogPath ?? CATALOG; const profilePath = options.profilePath ?? (configPath === CONFIG ? PROFILES : join(dirname(configPath), "execution-profiles.json")); const modePath = options.modePath ?? (configPath === CONFIG ? MODES : join(dirname(configPath), "agent-modes.json")); const env = options.env ?? process.env; const [runtime, catalog, profiles, modes] = await Promise.all([loadOrchestrationConfig(configPath), loadRoleCatalog(catalogPath), loadExecutionProfiles(profilePath), loadAgentModes(modePath)]); validateOrchestrationReferences(runtime, catalog, profiles, Object.keys(modes.modes)); const exec: CommandExecutor = async (command, args) => { const value = await pi.exec(command, args); return { stdout: value.stdout, stderr: value.stderr, code: value.code }; };
    pi.registerMessageRenderer("mesh-event", (message, renderOptions, theme) => renderMeshEventMessage(message, renderOptions, theme, runtime.natureHandleWords));
    let current: ActiveCaller | undefined; let rootLeaseId: string | undefined; let endpoint: MeshEndpoint | undefined; let sessionContext: ExtensionContext | undefined; let latestMode: ActiveModeEvent | undefined; let cadence: OrchestrationDeadlineScheduler | undefined; let materializationPass: Promise<void> | undefined; let pumpPass: Promise<boolean> | undefined; let waitForTerminalSnapshots: WaitForTerminalSnapshots = async () => { throw new Error("mesh_wait completion pump is not initialized"); }; const pumpWaiters = new Set<{ resolve: () => void; reject: (error: unknown) => void }>(); let noticePumping = false; let shuttingDown = false; let lastPumpError: string | undefined; let lastNoticePumpError: string | undefined; let modeBarrier: ActiveModeBarrier; const maintenance = new AbortController(); const waitLifecycle = new AbortController(); const injectedThisRuntime = new Set<string>(); const confirmedReceiptIds = new Set<string>(); const appendedNotices = new Set<string>(); const notifiedNotices = new Set<string>(); const reportedNoticeErrors = new Set<string>(); let resolvedEnvelope: AgentLaunchEnvelope | undefined; const childAgentId = env.PI_MESH_AGENT_ID; const childMeshId = env.PI_MESH_ID;
    if (env.PI_AGENT_RESOLVED_AGENT) try { resolvedEnvelope = validateLaunchEnvelope(JSON.parse(await readFile(env.PI_AGENT_RESOLVED_AGENT, "utf8"))); } catch (error) { current = { identity: "agent:invalid", meshId: childMeshId ?? randomUUID(), epoch: {} as PolicyEpoch, catalog, endpointId: "invalid", error: errorText(error) }; }
    const isolatedPromptOnly = resolvedEnvelope?.selfRole.contextPolicy === "prompt-only";
    const deps: OrchestrationDependencies = { configPath, catalogPath, profilePath, modePath, env, exec, activeCaller: () => current, authorityBarrier: () => { options.onAuthorityWait?.(); return modeBarrier.wait(); }, rootLeaseId: () => rootLeaseId, natureHandleWords: () => runtime.natureHandleWords };
    const inspectRootLease = (sessionId: string, sessionFile: string | undefined, tmux: Awaited<ReturnType<typeof probeTmux>>) => async (existing: Parameters<NonNullable<Parameters<typeof attachRootMesh>[2]["inspectExisting"]>>[0]) => { let pidAlive = true; try { process.kill(existing.pid, 0); } catch { pidAlive = false; } const sameSession = existing.rootSessionId === sessionId && existing.rootSessionFile === sessionFile; const tmuxMatches = existing.tmuxServerPid === undefined && existing.tmuxSessionId === undefined ? tmux === null : Boolean(tmux && existing.tmuxServerPid === tmux.serverPid && existing.tmuxSessionId === tmux.sessionId); return { pidAlive, sameSession, tmuxMatches }; };
    const initialPolicy = resolvedEnvelope ? resolvedEnvelope.policies[resolvedEnvelope.role] ?? { targets: {} } : { targets: {} };
    const childHasOutboundEdges = Boolean(childAgentId && !isolatedPromptOnly && Object.keys(initialPolicy.targets).length);
    let stagedMeshToolsEnabled = false;
    const stagedActivation: StagedMeshSendActivation | undefined = childHasOutboundEdges ? async caller => {
        if (stagedMeshToolsEnabled) return;
        await activateMeshPeerToolsForSend(pi, caller, async () => {
            const { patchAgentStatus } = await import("./utilities/orchestration_store.ts");
            await patchAgentStatus(runtime.stateRoot, caller.meshId, caller.agentId!, { meshToolsEnabled: true });
        });
        stagedMeshToolsEnabled = true;
    } : undefined;
    const registerDispatch = (targets: Record<string, AgentDefinition>, profiles: Record<string, readonly string[]> = {}) => { pi.registerTool(createMeshSendTool(deps, targets, profiles, stagedActivation)); };
    if (!isolatedPromptOnly) { registerDispatch(resolvedEnvelope ? Object.fromEntries(Object.keys(initialPolicy.targets).map(name => [name, resolvedEnvelope!.roles[name]!])) : {}, Object.fromEntries(Object.entries(initialPolicy.targets).map(([name, edge]) => [name, edge.profiles]))); pi.registerTool(createMeshGetTool(deps)); if (childHasOutboundEdges) pi.registerTool(createMeshWaitTool(deps, (...args) => waitForTerminalSnapshots(...args), () => waitLifecycle.signal)); pi.registerTool(createMeshStopTool(deps)); pi.registerTool(createMeshReportTool(deps)); }
    const applyMode = async (event: ActiveModeEvent) => { latestMode = event; if (!sessionContext || childAgentId || !current) return; const restored = branchData<EpochBinding>(sessionContext, POLICY_BINDING); const epoch = await ensurePolicyEpoch(runtime.stateRoot, current.meshId, { mode: event.name, catalog, profiles, callPolicy: runtime.callPolicy, ...(restored?.meshId === current.meshId && restored.mode === event.name ? { restoreEpochId: restored.epochId } : {}) }); current = { ...current, identity: `mode:${event.name}`, epoch, error: undefined }; registerDispatch(roleTargets(current), targetProfiles(current)); if (!restored || restored.epochId !== epoch.epochId) pi.appendEntry(POLICY_BINDING, { schemaVersion: 1, meshId: current.meshId, mode: event.name, epochId: epoch.epochId, policyDigest: epoch.policyDigest } satisfies EpochBinding); };
    modeBarrier = createActiveModeBarrier(applyMode, error => { if (current) current = { ...current, error: errorText(error) }; });
    onActiveMode(pi, event => modeBarrier.enqueue(event), error => { if (current) current = { ...current, error: errorText(error) }; });
    const eventIdentityCache = new Map<string, AgentDisplayIdentity>();
    const eventDisplayIdentities = async (agentIds: readonly string[]): Promise<Record<string, AgentDisplayIdentity>> => {
        if (!current) return {};
        const meshId = current.meshId;
        const resolved = await Promise.all([...new Set(agentIds)].map(async agentId => {
            const cacheKey = `${meshId}:${agentId}`;
            const cached = eventIdentityCache.get(cacheKey);
            if (cached) return [agentId, cached] as const;
            try {
                const identity = displayIdentityForSnapshot(await readAgentSnapshot(runtime.stateRoot, meshId, agentId), runtime.natureHandleWords);
                eventIdentityCache.set(cacheKey, identity);
                return [agentId, identity] as const;
            } catch { return undefined; }
        }));
        return Object.fromEntries(resolved.filter((entry): entry is readonly [string, AgentDisplayIdentity] => entry !== undefined));
    };
    const pumpEvents = async (): Promise<boolean> => {
        if (isolatedPromptOnly || shuttingDown || !endpoint || !current || !endpoint.online) return false;
        const snapshot = await readEndpointDeliverySnapshot(runtime.stateRoot, current.meshId, endpoint);
        if (shuttingDown) return false;
        const deliverable = snapshot.events.filter(event => !injectedThisRuntime.has(event.eventId));
        const completions = deliverable.filter(event => event.kind === "completion");
        const deliveryAcks = deliverable.filter(event => event.kind === "delivery-ack");
        const firstCompletionId = completions[0]?.eventId; const firstDeliveryAckId = deliveryAcks[0]?.eventId;
        for (const event of deliverable) {
            if (shuttingDown) return false;
            if (event.kind === "completion") {
                if (event.eventId !== firstCompletionId) continue;
                const sources = completions.map(source => source.payload);
                const completedById = new Map<string, FrozenTask>();
                for (const source of sources) for (const task of source.tasks as FrozenTask[]) {
                    if (completedById.has(task.taskId)) throw new Error(`Completion task ${task.taskId} appears in multiple source events`);
                    completedById.set(task.taskId, task);
                }
                const pendingTasks = snapshot.pendingTasks.filter(task => !completedById.has(task.taskId));
                const content = JSON.stringify({ tasks: [...completedById.values()], pendingTasks });
                if (exceedsModelVisibleLimit(content)) throw new Error("Completion identity bundle exceeds the model-visible budget");
                const identities = await eventDisplayIdentities([...completedById.values(), ...pendingTasks].map(task => task.agentId));
                const details = attachDisplayIdentities({ kind: "completion", sources, frontier: { observedAt: snapshot.observedAt, pendingTasks } }, identities);
                pi.sendMessage({ customType: "mesh-event", content, display: true, details }, { deliverAs: "steer", triggerTurn: sessionContext?.isIdle() ?? false });
                await markMeshEventsInjected(runtime.stateRoot, current.meshId, endpoint, completions.map(source => source.eventId));
                for (const source of completions) injectedThisRuntime.add(source.eventId);
                continue;
            }
            if (event.kind === "delivery-ack") {
                if (event.eventId !== firstDeliveryAckId) continue;
                const eventIds = deliveryAcks.map(source => source.eventId); const payloads = deliveryAcks.map(source => source.payload); const content = serializeModelVisibleJson({ acknowledgments: payloads });
                const identities = await eventDisplayIdentities(payloads.map(payload => typeof payload.agentId === "string" ? payload.agentId : "").filter(Boolean));
                const details = attachDisplayIdentities({ eventIds, kind: "delivery-ack", payloads }, identities);
                pi.sendMessage({ customType: "mesh-event", content, display: true, details }, { deliverAs: "steer", triggerTurn: sessionContext?.isIdle() ?? false });
                await markMeshEventsInjected(runtime.stateRoot, current.meshId, endpoint, eventIds);
                for (const source of deliveryAcks) injectedThisRuntime.add(source.eventId);
                continue;
            }
            const content = `[mesh-event ${event.eventId}] ${event.kind}\n${serializeModelVisibleJson(event.payload)}`;
            const agentId = typeof event.payload.agentId === "string" ? event.payload.agentId : undefined;
            const identities = agentId ? await eventDisplayIdentities([agentId]) : {};
            const details = attachDisplayIdentities({ eventId: event.eventId, kind: event.kind, payload: event.payload }, identities);
            pi.sendMessage({ customType: "mesh-event", content, display: true, details }, { deliverAs: event.delivery, triggerTurn: sessionContext?.isIdle() ?? false });
            await markMeshEventsInjected(runtime.stateRoot, current.meshId, endpoint, [event.eventId]);
            injectedThisRuntime.add(event.eventId);
        }
        return true;
    };
    const requestMaterializationPass = (): Promise<void> => {
        if (!rootLeaseId || !current) return Promise.resolve();
        if (materializationPass) return materializationPass;
        const pass = materializeMeshCompletionEvents(runtime.stateRoot, current.meshId, rootLeaseId); materializationPass = pass;
        const clear = () => { if (materializationPass === pass) materializationPass = undefined; };
        void pass.then(clear, clear);
        return pass;
    };
    const materializeWithDiagnostics = async (): Promise<boolean> => { try { await requestMaterializationPass(); return true; } catch (error) { if (!maintenance.signal.aborted) sessionContext?.ui.setStatus(PUMP_STATUS, `Mesh completion materialization: ${errorText(error)}`); return false; } };
    const settlePumpWaiters = (error?: unknown) => { const waiters = [...pumpWaiters]; pumpWaiters.clear(); cadence?.setEnabled("wait-delivery", false); for (const waiter of waiters) { if (error === undefined) waiter.resolve(); else waiter.reject(error); } };
    const requestPumpPass = (): Promise<boolean> => { if (pumpPass) return pumpPass; const pass = pumpEvents(); pumpPass = pass; void pass.then(() => { if (pumpPass === pass) pumpPass = undefined; settlePumpWaiters(); }, error => { if (pumpPass === pass) pumpPass = undefined; settlePumpWaiters(error); }); return pass; };
    const nextPumpPass = (signal?: AbortSignal): Promise<void> => new Promise((resolve, reject) => { if (shuttingDown) { reject(new Error("mesh_wait stopped for session shutdown")); return; } if (signal?.aborted) { reject(signal.reason); return; } const waiter = { resolve: () => { signal?.removeEventListener("abort", abort); resolve(); }, reject: (error: unknown) => { signal?.removeEventListener("abort", abort); reject(error); } }; const abort = () => { pumpWaiters.delete(waiter); if (!pumpWaiters.size) cadence?.setEnabled("wait-delivery", false); reject(signal?.reason); }; signal?.addEventListener("abort", abort, { once: true }); pumpWaiters.add(waiter); cadence?.setEnabled("wait-delivery", true); });
    waitForTerminalSnapshots = async (config, caller, taskIds, signal) => { while (true) { if (signal?.aborted) throw signal.reason; const currentCaller = await reauthorizeCaller(deps, caller); if (!currentCaller.agentId || currentCaller.runtimeId !== caller.runtimeId) throw new Error("mesh_wait caller runtime rotated"); await requestPumpPass(); signal?.throwIfAborted(); const snapshots = await Promise.all(taskIds.map(async taskId => { const task = await readTask(config.stateRoot, caller.meshId, taskId); authorizeTask(currentCaller, task, "wait for"); return readAgentSnapshot(config.stateRoot, caller.meshId, task.request.agentId, taskId); })); signal?.throwIfAborted(); if (snapshots.every(snapshot => snapshot.task?.result && isTerminalTask(snapshot.task.status.state))) return snapshots; await nextPumpPass(signal); } };
    const pumpWithDiagnostics = async () => { try { if (await requestPumpPass() && lastPumpError !== undefined) { lastPumpError = undefined; try { sessionContext?.ui.setStatus(PUMP_STATUS, undefined); } catch {} } } catch (error) { const text = errorText(error).replace(/\s+/gu, " ").trim(); if (text !== lastPumpError) { lastPumpError = text; const diagnostic = `Mesh event pump: ${text}`; try { sessionContext?.ui.setStatus(PUMP_STATUS, diagnostic); } catch {} try { sessionContext?.ui.notify(diagnostic, "error"); } catch {} } } };
    const reportNoticeError = (error: unknown) => { const text = errorText(error).replace(/\s+/gu, " ").trim(); lastNoticePumpError = text; if (reportedNoticeErrors.has(text)) return; reportedNoticeErrors.add(text); const diagnostic = `Mesh notice pump: ${text}`; try { sessionContext?.ui.setStatus(NOTICE_PUMP_STATUS, diagnostic); } catch {} try { sessionContext?.ui.notify(diagnostic, "error"); } catch {} };
    const pumpTuiNotices = async (): Promise<void> => {
        if (isolatedPromptOnly || shuttingDown || noticePumping || sessionContext?.mode !== "tui" || !endpoint || !current) return;
        noticePumping = true; let failed = false;
        try {
            if (!await isLiveMeshEndpointBinding(runtime.stateRoot, current.meshId, endpoint)) return;
            const notices = await listPendingTuiNotices(runtime.stateRoot, current.meshId, { endpointId: endpoint.endpointId });
            for (const notice of notices) try {
                if (shuttingDown || sessionContext.mode !== "tui" || !await isLiveMeshEndpointBinding(runtime.stateRoot, current.meshId, endpoint)) return;
                if (!appendedNotices.has(notice.noticeId)) { pi.appendEntry(NOTICE_ENTRY, notice); appendedNotices.add(notice.noticeId); }
                if (!notifiedNotices.has(notice.noticeId)) { sessionContext.ui.notify(tuiNoticeText(notice), "info"); notifiedNotices.add(notice.noticeId); }
                if (shuttingDown || !await isLiveMeshEndpointBinding(runtime.stateRoot, current.meshId, endpoint)) return;
                await acknowledgeDisplayedTuiNotice(runtime.stateRoot, current.meshId, notice.noticeId, { endpointId: endpoint.endpointId, binding: endpoint }, new Date().toISOString());
            } catch (error) { failed = true; reportNoticeError(error); }
            if (!failed && lastNoticePumpError !== undefined) { lastNoticePumpError = undefined; try { sessionContext.ui.setStatus(NOTICE_PUMP_STATUS, undefined); } catch {} }
        } catch (error) { reportNoticeError(error); } finally { noticePumping = false; }
    };
    if (childAgentId && !isolatedPromptOnly) pi.registerCommand("parent", { description: "Return to this mesh agent's inviter tmux window", async handler(_args, ctx) { const result = await exec(runtime.returnParentCommand, []); if (result.code !== 0) ctx.ui.notify(result.stderr.trim() || "Could not return to the inviter window", "error"); } });
    pi.on("session_start", async (_event, ctx) => {
        sessionContext = ctx; const sessionId = ctx.sessionManager.getSessionId(); const sessionFile = ctx.sessionManager.getSessionFile();
        if (resolvedEnvelope && childMeshId && childAgentId) { if (resolvedEnvelope.meshId !== childMeshId || resolvedEnvelope.agentId !== childAgentId) throw new Error("Mesh child environment does not match launch envelope"); if (!sessionFile) throw new Error("Mesh child session requires a durable session file"); const binding = await bindAgentRuntime(runtime.stateRoot, childMeshId, childAgentId, { runtimeId: randomUUID(), kind: "pi", sessionId, sessionFile }); const epochRecord = await readPolicyEpoch(runtime.stateRoot, childMeshId, resolvedEnvelope.epochId); current = { identity: resolvedEnvelope.identity, meshId: childMeshId, epoch: epochRecord, catalog: { schemaVersion: 4, roles: resolvedEnvelope.roles }, envelope: resolvedEnvelope, agentId: childAgentId, runtimeId: binding.runtimeId, endpointId: `agent:${childAgentId}`, sessionFile }; emitResolvedAgent(pi, resolvedEnvelope); if (sessionFile && !isolatedPromptOnly) endpoint = await bindMeshEndpoint(runtime.stateRoot, childMeshId, { endpointId: current.endpointId, kind: "agent", agentId: childAgentId, harness: "pi", sessionId, sessionFile }); const status = await readAgentSnapshot(runtime.stateRoot, childMeshId, childAgentId).then(value => value.status); stagedMeshToolsEnabled = !isolatedPromptOnly && status.meshToolsEnabled; const roleTools = resolvedEnvelope.selfRole.tools.filter(name => !MESH_PEER_TOOL_NAMES.includes(name as typeof MESH_PEER_TOOL_NAMES[number])); const staged = childHasOutboundEdges ? stagedMeshToolsEnabled ? authorizedMeshTools(current) : ["mesh_send", MESH_REPORT_TOOL_NAME] : [MESH_REPORT_TOOL_NAME]; pi.setActiveTools(isolatedPromptOnly ? [] : [...new Set([...roleTools, ...staged])]); if (stagedMeshToolsEnabled) { const activeTools = new Set(pi.getActiveTools()); const missing = authorizedMeshTools(current).filter(name => !activeTools.has(name)); if (missing.length) throw new Error(`Persisted mesh activation could not be restored; child process restart required: ${missing.join(", ")}`); } if (!isolatedPromptOnly) ctx.ui.setStatus(PARENT_STATUS, runtime.parentNavigationHint); if (sessionFile) await reconcileMeshUsageClaims(runtime.stateRoot, childMeshId, sessionFile); }
        else {
            const persisted = Boolean(sessionFile); const restored = branchData<RootBinding>(ctx, ROOT_BINDING); let mesh = restored ? await readMesh(runtime.stateRoot, restored.meshId).catch(() => undefined) : undefined; if (mesh?.state === "closing" && persisted) { const recoveryTmux = await probeTmux(exec, runtime.tmux, env); const recoveryLease = await attachRootMesh(runtime.stateRoot, mesh.meshId, { rootSessionId: sessionId, budgets: runtime.budgets, ...(sessionFile ? { rootSessionFile: sessionFile } : {}), inspectExisting: inspectRootLease(sessionId, sessionFile, recoveryTmux) }); await cleanupMeshAgents({ stateRoot: runtime.stateRoot, meshId: mesh.meshId, exec, tmux: runtime.tmux, shutdownReason: "recovery", hubContext: recoveryTmux ?? undefined }); await completeMeshClose(runtime.stateRoot, mesh.meshId, recoveryLease.leaseId); mesh = undefined; } if (!mesh || mesh.state !== "open" || !mesh.recoverable || !persisted) { mesh = await initializeMesh(runtime.stateRoot, { rootSessionId: sessionId, ...(sessionFile ? { rootSessionFile: sessionFile } : {}), recoverable: persisted, budgets: runtime.budgets }); if (persisted) pi.appendEntry(ROOT_BINDING, { schemaVersion: 1, meshId: mesh.meshId } satisfies RootBinding); }
            const tmux = await probeTmux(exec, runtime.tmux, env); const lease = await attachRootMesh(runtime.stateRoot, mesh.meshId, { rootSessionId: sessionId, budgets: runtime.budgets, ...(sessionFile ? { rootSessionFile: sessionFile } : {}), ...(tmux ? { tmuxServerPid: tmux.serverPid, tmuxSessionId: tmux.sessionId } : {}), inspectExisting: inspectRootLease(sessionId, sessionFile, tmux) }); rootLeaseId = lease.leaseId; const fallbackEpoch = mesh.currentEpochId ? await readPolicyEpoch(runtime.stateRoot, mesh.meshId, mesh.currentEpochId) : { schemaVersion: 4 as const, meshId: mesh.meshId, epochId: randomUUID(), mode: "pending", directTargets: {}, roles: {}, profiles: {}, policies: {}, roleSet: [], policyDigest: "", createdAt: new Date().toISOString() }; current = { identity: "mode:pending", meshId: mesh.meshId, epoch: fallbackEpoch, catalog, endpointId: `root:${mesh.meshId}`, ...(sessionFile ? { sessionFile } : {}) }; if (sessionFile) endpoint = await bindMeshEndpoint(runtime.stateRoot, mesh.meshId, { endpointId: current.endpointId, kind: "root", harness: "pi", sessionId, sessionFile }); if (latestMode) await applyMode(latestMode); await reconcileMeshState(runtime.stateRoot, mesh.meshId); if (sessionFile) await reconcileMeshUsageClaims(runtime.stateRoot, mesh.meshId, sessionFile); const protectedReservations = await reconcilePressureAdmissions(runtime.stateRoot, mesh.meshId, async requester => { const inspected = await inspectAgentTmux(exec, runtime.tmux, requester.agent.tmux); if (inspected.server === "unavailable" || inspected.server === "match" && inspected.paneState === "unavailable") throw new Error("Requester tmux evidence is temporarily unavailable"); return inspected.server === "match" && inspected.sessionAlive && inspected.paneState === "alive"; }); await reconcileMeshReservations(runtime.stateRoot, mesh.meshId, agentId => inspectMeshAgentWindow(exec, runtime.tmux, tmux, mesh.meshId, agentId), protectedReservations); await recoverPendingAgentStops({ stateRoot: runtime.stateRoot, meshId: mesh.meshId, exec, tmux: runtime.tmux });
        }
        if (sessionFile && current && endpoint) { const persistedReceipts = await readPersistedCompletionReceiptEvidence(sessionFile); await reconcileCompletionReceipts(runtime.stateRoot, current.meshId, { endpointId: current.endpointId, endpointSessionFile: sessionFile, claimantSessionFile: sessionFile, persistedReceipts }); confirmedReceiptIds.clear(); for (const receiptId of persistedReceipts.keys()) confirmedReceiptIds.add(receiptId); }
        let injectedNow = 0;
        const schedule = options.setInterval ? (callback: () => void | Promise<void>, delay: number) => options.setInterval!(() => { injectedNow += delay; return callback(); }, delay) : (callback: () => void | Promise<void>, delay: number) => globalThis.setTimeout(() => { void callback(); }, delay);
        const cancel = options.clearInterval ?? (timer => globalThis.clearTimeout(timer as NodeJS.Timeout));
        cadence = new OrchestrationDeadlineScheduler({ now: options.now ?? (options.setInterval ? () => injectedNow : undefined), setTimeout: schedule, clearTimeout: cancel });
        if (rootLeaseId && current) {
            const rootOptions = () => ({ stateRoot: runtime.stateRoot, meshId: current!.meshId, leaseId: rootLeaseId!, gc: runtime.gc, exec, tmux: runtime.tmux, signal: maintenance.signal });
            cadence.add("materialize", 1000, async () => { await materializeWithDiagnostics(); });
            cadence.add("root-heartbeat", 2000, async () => { await heartbeatRootLease(runtime.stateRoot, current!.meshId, rootLeaseId!).catch(() => {}); });
            cadence.add("pressure", 3000, async () => { try { await processPressureAdmissions(rootOptions()); } catch (error) { if (!maintenance.signal.aborted) sessionContext?.ui.setStatus("mesh-agent-gc", `Mesh agent GC: ${errorText(error)}`); } });
            cadence.add("gc", runtime.gc.periodicIntervalMs, async () => { try { const maintenanceOptions = rootOptions(); await recoverPendingAgentStops(maintenanceOptions); await runPeriodicAgentGc(maintenanceOptions); } catch (error) { if (!maintenance.signal.aborted) sessionContext?.ui.setStatus("mesh-agent-gc", `Mesh agent GC: ${errorText(error)}`); } });
        }
        cadence.add("delivery", 2000, async () => { if (!await materializeWithDiagnostics()) return; await pumpWithDiagnostics(); });
        cadence.add("wait-delivery", 250, pumpWithDiagnostics, { enabled: false });
        cadence.add("notices", 3000, pumpTuiNotices);
        if (!rootLeaseId || !current || await materializeWithDiagnostics()) await pumpWithDiagnostics();
        await pumpTuiNotices();
        cadence.start();
    });
    if (!isolatedPromptOnly) pi.on("context", async event => {
        if (!current?.sessionFile) return;
        const receiptIds = new Set(receiptIdsFromToolResults(event.messages)); for (const receiptId of receiptIds) confirmedReceiptIds.add(receiptId);
        const ledger = await readCompletionLedger(runtime.stateRoot, current.meshId, current.endpointId, current.sessionFile);
        const receivedTaskIds = new Set((ledger?.receipts ?? []).filter(receipt => confirmedReceiptIds.has(receipt.receiptId)).flatMap(receipt => receipt.taskIds));
        const projection = projectMeshCompletionContext(event.messages, receivedTaskIds);
        const normalEventIds: string[] = []; const interventionIds: string[] = [];
        for (const message of event.messages) {
            const raw = message as unknown as Record<string, unknown>; const details = raw.details && typeof raw.details === "object" && !Array.isArray(raw.details) ? raw.details as Record<string, unknown> : undefined;
            if (raw.customType !== "mesh-event" || !details) continue;
            if (details.kind === "intervention" && typeof details.eventId === "string") interventionIds.push(details.eventId);
            else if (["signal", "report"].includes(String(details.kind)) && typeof details.eventId === "string") normalEventIds.push(details.eventId);
            else if (details.kind === "delivery-ack" && Array.isArray(details.eventIds)) for (const eventId of details.eventIds) if (typeof eventId === "string") normalEventIds.push(eventId);
        }
        if (endpoint) {
            const acknowledged = [...new Set([...projection.eventIds, ...normalEventIds])];
            if (acknowledged.length) await acknowledgeMeshEvents(runtime.stateRoot, current.meshId, endpoint, acknowledged);
            if (interventionIds.length && endpoint.kind === "agent") await acknowledgeMeshContextInterventions(runtime.stateRoot, current.meshId, endpoint, interventionIds);
        }
        return { messages: projection.messages };
    });
    if (resolvedEnvelope) pi.on("before_agent_start", event => { const instructions = resolvedEnvelope!.self.instructions; return { systemPrompt: `${event.systemPrompt}\n\n${instructions}` }; });
    const paletteDeps = (): MeshPaletteDependencies => { const caller = active(deps); return { meshId: caller.meshId, exec, tmux: runtime.tmux, historyViewerExtension: runtime.historyViewerExtension, piCommand: runtime.harnesses.pi!.command, natureHandleWords: runtime.natureHandleWords, tmuxPreviewActions: loadFeatureKeybindings("tmuxPreview").actions, discover: async identity => { const store = await import("./utilities/orchestration_store.ts"); const allItems = await store.listMeshAgents(runtime.stateRoot, identity.meshId); const items = caller.agentId ? allItems.filter(item => item.agent.parentAgentId === caller.agentId) : allItems; const values = await Promise.all(items.map(item => readReconciledAgentSnapshot(exec, runtime.tmux, runtime.stateRoot, identity.meshId, item.agent.agentId).then(value => ({ ok: true as const, value })).catch(() => ({ ok: false as const })))); return { agents: values.flatMap(item => item.ok ? [item.value] : []), malformedCount: values.filter(item => !item.ok).length }; }, stopAgent: request => stopPaletteMeshAgent(deps, runtime, request) }; };
    let unregister = () => {};
    if (!isolatedPromptOnly) { providePopupView(pi, { id: "agent-sessions", title: "Mesh Agents", create(view) { const component = new MeshAgentsPaletteComponent({ tui: view.tui, theme: view.theme, ui: view.extensionContext.ui, keymap: loadPaletteKeymap(undefined, "meshPalette").keymap, deps: paletteDeps(), done: disposition => view.done(disposition === "close" ? "close-all" : "back") }); component.start(); return component; } }); const open = async (ctx: ExtensionContext, placement: "root" | "push" = "root") => openPopupView(pi, "agent-sessions", ctx, placement); unregister = provideCommandPaletteContribution(pi.events, { owner: "mesh", id: "agents", label: "/mesh  Manage mesh agents", description: "Open, unlink, inspect, or stop mesh agent sessions.", keywords: ["mesh", "agents", "tmux"], run: async ctx => (await open(ctx, "push")) === "close-all" ? "close" : "return" }); pi.registerCommand("mesh", { description: "Manage persistent mesh agents", handler: async (_args, ctx) => { await open(ctx); } }); }
    pi.on("session_shutdown", async event => { shuttingDown = true; const shutdownError = new Error("mesh_wait stopped for session shutdown"); waitLifecycle.abort(shutdownError); settlePumpWaiters(shutdownError); maintenance.abort(new Error("Mesh root maintenance stopped for session shutdown")); unregister(); await cadence?.stop(); if (endpoint && current) await setMeshEndpointOffline(runtime.stateRoot, current.meshId, endpoint.endpointId, endpoint).catch(() => {}); if (!childAgentId && current && rootLeaseId) await failOpenPressureAdmissions(runtime.stateRoot, current.meshId).catch(() => {}); if (childAgentId || !current || !rootLeaseId || event.reason === "reload") return; await beginMeshClose(runtime.stateRoot, current.meshId, rootLeaseId); const hubContext = await probeTmux(exec, runtime.tmux, env) ?? undefined; await cleanupMeshAgents({ stateRoot: runtime.stateRoot, meshId: current.meshId, exec, tmux: runtime.tmux, shutdownReason: event.reason, hubContext }); await completeMeshClose(runtime.stateRoot, current.meshId, rootLeaseId); });
    return true;
}
export default registerOrchestration;
